### ISSUE TITLE
Ability to set default video quality in settings

### ISSUE THREAD

**Issue by waqas** [yuliskov/SmartYouTubeTV#1]
For users with metered connections, it would be great to able to set a default resolution for playback. For example, 360p. Even if someone selects 1080p as default and current video is max at 720p then default to max availavle.

**Comment by waqas** [comment]
Ability to set video quality at playback screen would also be nice.

**Comment by yuliskov** [comment]
Added into TODO list.

**Comment by yuliskov** [comment]
Fixed.
