### ISSUE TITLE
I like your software

### ISSUE THREAD

**Issue by xiaoxihu2017** [yuliskov/SmartYouTubeTV#10]
I like your software very much.
I come from China, the software to solve the Chinese smart TV (Xiaomi TV) can not login YouTube account.
Use the SmartYouTubeTV_Exoplayer_v6.8.22_r.apk version now.
Question: 
1, the interface is not the same as in the past, can not adjust the quality of the picture.
2, the statistical information is gone, as follows.
![eahxz8qn_ nlza ouzkuaws](https://user-images.githubusercontent.com/31083939/29390983-87e568c4-8326-11e7-9319-de44e9771e03.png)

3, 4K 60fps support?.
4, YouTube live channel can not play

**Comment by xiaoxihu2017** [comment]
4, YouTube live channel can not play

**Comment by yuliskov** [comment]
Hi. This version is under development. I hope that such issues will be
fixed soon.

**Comment by yuliskov** [comment]
Hi, please test new version.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.32/SmartYouTubeTV_Exoplayer_v6.8.32_r.apk

**Comment by yuliskov** [comment]
Latest version reworked to bypass this issue.
