### ISSUE TITLE
Stats for nerds is very weird in 4k version

### ISSUE THREAD

**Issue by a3kov** [yuliskov/SmartYouTubeTV#100]
1080p TV. Enabled stats for nerds in 1080p, ok. Then tried 4k version.
1) 4k stats look different (why ?) and disabled by default even if you had 1080p stats enabled.
2) 1080p stats still show up when transitioning to/from video, even with 4k stats disabled. As far as I see there's no way to disable 1080p stats in 4k mode ?

I guess it's very confusing for an average user.

**Comment by yuliskov** [comment]
@corehack thanks for the feedback. I'm totally agree that stats need some improvement.

**Comment by yuliskov** [comment]
4K has been improved since last comment
