### ISSUE TITLE
Support new Youtube AndroidTV UI

### ISSUE THREAD

**Issue by rodalpho** [yuliskov/SmartYouTubeTV#101]
On my Shield TV (and presumably other AndroidTV devices) Google now shows an updated UI which is much more usable and useful. Can SmartYouTubeTV offer this UI?

Screenshots:
https://9to5google.com/2018/02/22/youtube-android-tv-redesign-video-quality/

**Comment by devslava** [comment]
It seems Youtube is testing it randomly now.
I've had new interface in SmartYoutube few times too.
I've not tested widely, but I did not meet any bugs at first glance.

**Comment by rodalpho** [comment]
Well that's encouraging! I haven't seen the new UI in SmartYouTubeTV yet, but it's good to hear it can work there.

**Comment by devslava** [comment]
You can try to clear SmartYoutube app data completely and launch the app. From my experience you get new design 1 of ~5 launches after clearing app data.

**Comment by rodalpho** [comment]
I tried that a full 10 times and no go. My guess is it needs to send YouTube a different user-agent, so the website sends the app the new UI. Here's a picture of the user agent on the Shield TV:

https://imgur.com/a/fh4c8

**Comment by rodalpho** [comment]
Just tried it again and now I got the new UI! Guess we'll see if they switch me back again.

https://imgur.com/a/y8wTx

**Comment by rodalpho** [comment]
So far they haven't switched me back! I guess this can be closed.
