### ISSUE TITLE
Does smart youtube support Android 4.1?

### ISSUE THREAD

**Issue by itrustmchow** [yuliskov/SmartYouTubeTV#102]
i have a xiaomi TV,the os is Android 4.1.2,The obvious,the Android version is very old,i try to run the newest smart youtube on it,but failure，is the smart youtube support Android 4.1?

thanks a lot.

**Comment by yuliskov** [comment]
@itrustmchow kinda or I would say, it depends...

**Comment by itrustmchow** [comment]
when i launch the app,tv remind me:this device not support youtube for tv.
have another way to use smart youtube on this tv?

thanks a lot.

**Comment by moritenw** [comment]
it work on my letv X60 android 4.1.2
