### ISSUE TITLE
grey screen

### ISSUE THREAD

**Issue by ak1dd** [yuliskov/SmartYouTubeTV#103]
After playing a video the screen goes grey afterward.  Sometimes there will be no sound afterward, sometimes the audio for the video I just played will replay.   This happens very often.

In previous builds I used to get the "error" screen and the only way to get the player to behave as expected was to completely restart the FireTV - restarting the app will invoke the error message every time otherwise.

My daughter likes to watch playlists and it is rare that they will play more than 5 videos without this happening.

I suspect this has something to do skipping the ad?

**Comment by yuliskov** [comment]
duplicate of issue #76

**Comment by ak1dd** [comment]
I wrote this up separately as it isn't exactly the same as the "black screen"  The black screen just stops.  The grey screen replays the audio of the video I just watched.

**Comment by devslava** [comment]
Same as #83. 
Black/grey screen, audio of the last video is playing.
