### ISSUE TITLE
Ads getting through

### ISSUE THREAD

**Issue by rodalpho** [yuliskov/SmartYouTubeTV#105]
On rare occasions, I've been seeing ads when playing a video. When I back up out of the video and try again the ad doesn't play. My guess is YouTube added a couple new servers or patterns to their ads and SmartYouTubeTV needs to be updated to catch them.

**Comment by yuliskov** [comment]
@rodalpho such ads happened to me one time and then gone. I'm not sure what it was.

**Comment by rodalpho** [comment]
I've seen ads maybe 6 or 7 times in the past two weeks. The ad plays, I back out of it, start the video again, and it plays without the ad. 

I'm running the latest SmartYouTubeTV and also running DNS through a pi-hole. So maybe the ad comes directly from a YouTube server?

**Comment by yuliskov** [comment]
> So maybe the ad comes directly from a YouTube server?

Maybe, but that is not a problem since any ads could be blocked. I'm only need a way to catch it.

**Comment by rodalpho** [comment]
Well, I'm happy to help any way I can.

**Comment by yuliskov** [comment]
@rodalpho ok, please, let me know if ads popup again.

**Comment by rodalpho** [comment]
Yes, I just had an ad this morning. I consistently see 1-2 per day.

**Comment by yuliskov** [comment]
> Yes, I just had an ad this morning. I consistently see 1-2 per day.
If you don't mind, give me a names (or links) of some of the videos where ads popup most often.

**Comment by rodalpho** [comment]
Sure, next time I see an ad I'll write it down for you.

**Comment by yuliskov** [comment]
@rodalpho thanks for the help. Bunch of the ads has been added to the black list. Please test.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.83/SmartYouTubeTV_Orig_v6.12.83_r.apk

**Comment by rodalpho** [comment]
Nice! I'll test it tonight.

**Comment by rodalpho** [comment]
Saw an ad last night on this video:

https://www.youtube.com/watch?v=6EFXhjdcFhk&t=34s

**Comment by rodalpho** [comment]
Saw ads last night on these two videos:

https://www.youtube.com/watch?v=Pws0ys2p18s&t=28s

https://www.youtube.com/watch?v=uhNFRYKRGco

**Comment by yuliskov** [comment]
@rodalpho thanks. Did you notice any differences after last updates? Maybe ads rate is changed a bit?

**Comment by rodalpho** [comment]
The ad 3 days ago was running 6.12.83; the ads last night were running 6.12.84. 

Before 6.12.83 I only saw around one or two ads per day, so it seems about the same.

**Comment by yuliskov** [comment]
@rodalpho ok, lets change strategy. Below the hosts that I've blocked in my app. What do you think? Maybe I forgot something to add?

```
"video-stats.video.google.com",
"www.adwords.google.lloymlincs.com",
"ads.adadapted.com",
"www.doubleclickbygoogle.com",
"adservice.google.ca",
"adservice.google.com",
"adservice.google.com.au",
"adservices.google.com",
"feedads.googleadservices.com",
"imasdk.googleapis.com",
"m4.afs.googleadservices.com",
"unblockyoutube.biz",
"unblockyoutubeproxy.com",
"unblockyoutube.tv",
"youtube-proxy.info",
"youtuberid.com",
"gotoyoutube.us",
"s2.youtube.com",
"s.youtube.com",
"youtube.112.2o7.net",
"ads.youtube.com",
"youtube.com/api/stats/ads",
"ad.doubleclick.net",
"partnerad.l.doubleclick.net",
"pubads.g.doubleclick.net",
"securepubads.g.doubleclick.net",
"googleads.g.doubleclick.net",
"googleads2.g.doubleclick.net",
"googleads4.g.doubleclick.net",
"static.doubleclick.net",
"pagead-googlehosted.l.google.com",
"pagead.l.doubleclick.net",
"pagead.l.google.com",
"partnerad.l.google.com",
"cm.g.doubleclick.net",
"googlesyndication.com",
"pagead.googlesyndication.com",
"pagead1.googlesyndication.com",
"pagead2.googlesyndication.com",
"pagead3.googlesyndication.com",
"video-ad-stats.googlesyndication.com",
"tpc.googlesyndication.com",
"googleadservices.com",
"www.googleadservices.com",
"partner.googleadservices.com",
"www.partner.googleadservices.com",
"pagead2.googleadservices.com",
"domains.googlesyndication.com",
"4.afs.googleadservices.com",
"syndication.exoclick.com",
"ads.exoclick.com",
"cdn11.contentabc.com"
```

**Comment by yuliskov** [comment]
test release: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.86/SmartYouTubeTV_Orig_v6.12.86_r.apk

**Comment by rodalpho** [comment]
Thanks, will test the latest release tonight.

Not sure if hosts-level blocking will ultimately do it, might need to either look at behavior (ie, if it pops up that "skip ad in 5 seconds" link, then block that video) or do more granular blocking like uBlock Origin. Here's a link to YouTube blocking rules for uBO, but many of them are granular, blocking patterns inside youtube.com and so on.

https://www.reddit.com/r/uBlockOrigin/comments/6sgwcr/youtube_video_ads_as_of_8817/

**Comment by yuliskov** [comment]
@rodalpho thanks for the link. I'll keep that in mind.

**Comment by rodalpho** [comment]
Got another ad last night, but I did not note the link. 

Also starting videos takes a couple seconds now where previously it was instant. If that's necessary to get rid of ads, it's a good tradeoff, but I'm still seeing ads.

**Comment by yuliskov** [comment]
@rodalpho hmm, strange. There must be a minimum influence on overall performance.

**Comment by rodalpho** [comment]
Speed seems fine now, but I am still seeing 1-2 ads per day. Not a huge deal, but like the issue says, they're still getting through.

**Comment by yuliskov** [comment]
@rodalpho I think that ads is related to your country/city or something. You should catch it by yourself.  One f the ways to do this by install uBlock Chrome extension. It could display blocked hosts. Post them below.

**Comment by rodalpho** [comment]
OK, here's what's blocked in uBO advanced mode when I go to youtube.com/tv and try to watch a monetized video.

doubleclick.net
youtube.com (not red in uBO, but I don't allow all scripts either)
googlesyndication.com

**Comment by yuliskov** [comment]
@rodalpho these hosts already blocked (except second one off course). Try to find more.

**Comment by rodalpho** [comment]
On the regular YouTube site, I went to a bunch of videos and only found one additional blocked domain, but it was yellow not red, meaning some requests were blocked and others not-- googlevideo.com.

**Comment by rodalpho** [comment]
Unfortunately, it doesn't have a 10-foot (android TV) UI.

**Comment by yuliskov** [comment]
Still not fixed?

**Comment by co5mo** [comment]
fixed for me no reginal ads ether

**Comment by yuliskov** [comment]
Seems ads are gone for now

**Comment by SatWiz** [comment]
Annoying Youtube Music ads popping up between each music video plays from Google Home play instruction on the SHIELD.
Can those ads be eliminated like this local version: https://www.youtube.com/watch?v=DLxE4L5N4RA
