### ISSUE TITLE
Sometimes fails to start on Amazon Fire TV stick

### ISSUE THREAD

**Issue by olzhasar** [yuliskov/SmartYouTubeTV#106]
I have been successfully using this app for several months, but last week it constantly freezes on loading screen and fails to start. Is there any recent issues with fire stick tv compatibility?

**Comment by yuliskov** [comment]
@olzhasar thanks, friend. Have you tried other launchers, like 1080?

**Comment by olzhasar** [comment]
@yuliskov yes, I have tried 1080 as well. Result is the same.

**Comment by olzhasar** [comment]
I have investigated that the problem was totally related to my internet connection. I have used this app in Kazakhstan and local authorities have been blocking telegram and youtube for several days. Everything works fine now, sorry for disturbing.
