### ISSUE TITLE
Bug with fire remote app

### ISSUE THREAD

**Issue by gh0ztie** [yuliskov/SmartYouTubeTV#108]
If I multitask on my phone whilst using the fire remote app with smartyoutubetv it makes smartyoutubetv freeze and when it freezes it also makes the fire stick disappear from fire remote app so I have to unplug the fire stick I am not complaining as it is a free app but thought u would like to know all the same thank you for the time and effort you put in to smartyoutubetv

**Comment by yuliskov** [comment]
@gh0ztie hmm, didn't know about that. What launcher are you using?

**Comment by yuliskov** [comment]
@gh0ztie what about last update?

**Comment by gh0ztie** [comment]
Sorry for late reply I was using 720  have just updated will let you know thanks for getting back to me

**Comment by gh0ztie** [comment]
Works great thank you
