### ISSUE TITLE
screen get dark when playing

### ISSUE THREAD

**Issue by jaccsr** [yuliskov/SmartYouTubeTV#11]
apk version: SmartYouTubeTV_Exoplayer_v6.8.30_r.apk
TV: haier mooka U55H3 
Hi, thank you for creating such a good app. I like it very much. 
When playing video, screen often get dark for about 1 second and then recovered. Just like when playing video on pc, suddenly the screensaver begin to work, after moving the mouse, the video shows again. I tried several videos. It did not happen on older 6.8.14 version.

**Comment by yuliskov** [comment]
Hi, check the latest version.

**Comment by yuliskov** [comment]
Dont know what to fix there. My app already uses [keepScreenOn](https://github.com/google/ExoPlayer/blob/195a93e5af12715c4d92b376fb6f40d8fd8885d8/demo/src/main/res/layout/player_activity.xml#L21) feature. I'm pretty sure that it is your firmware issue.
