### ISSUE TITLE
Xiaomi Laser Projector 150"

### ISSUE THREAD

**Issue by SurvivorDV** [yuliskov/SmartYouTubeTV#110]
Good afternoon!
SmartYouTubeTV latest version 6.12.83
I'm having problems with playing 4K HDR clips on my device.
Device Specification:
Android 6.0.1 (MIUI TV version 1.3.74)
CPU ARM Amlogic T968 (4-core Cortex A53 1.8GHz / 64bit)
RAM 2GB DDR3
GPU Mali-830 MP2
The problem is that it's impossible to reproduce the next quality videos:
1. 2160p, 60 fps, vp9; - loading is performed, the movie is played, but the picture freezes.
2. 2160p, 60 fps, vp9.2, HDR; - video does not load.
3. 2160p, 30 fps, vp9; - loading is performed, the movie is played, but the picture freezes.
4. 1440p, 60 fps, vp9; - loading is performed, the movie is played, but the picture freezes.
5. 1440p, 60 fps, vp9.2, HDR; - video does not load.
6. vp9; etc.

When using avc playback problems do not occur, only with vp9.
I hope for the speedy elimination of problems with 4K HDR content playback on my device.
Thank you for the excellent application!

**Comment by yuliskov** [comment]
@SurvivorDV I have some doubts that your device capable to play vp9 videos smoothly.

**Comment by SurvivorDV** [comment]
Yes, it looks like a problem in my device. Running test videos (vp9) by other players showed the same results. Thanks for the help!

**Comment by yuliskov** [comment]
@SurvivorDV you're welcome
