### ISSUE TITLE
How is this app able to determine the actual location of the IP ??? It isn't suppose to in my case

### ISSUE THREAD

**Issue by ghost** [yuliskov/SmartYouTubeTV#111]
I'm using a VPN and they are no DNS leaks at all. Netflix is also unable to identify it as VPN and playing all the content. Strangely, only Youtube app determines my country without signing in and provides trending content of my country. How is that possible ?? In all other devices like laptop and mobile, Youtube is proving the VPN IP address country content. Is some country hardcoded into this app ??? *I didn't sign in

**Comment by yuliskov** [comment]
@Sreekantt I don't know actually. I'm just using info provided from youtube api.

**Comment by yuliskov** [comment]
Not related to my app.
