### ISSUE TITLE
SmartYouTubeTV_Vlive_v6.12.72_r.apk running at 480p and 30fps

### ISSUE THREAD

**Issue by javagirl209** [yuliskov/SmartYouTubeTV#112]
thank you for SmartYouTubeTV_Vlive_v6.12.72_r.apk.... so far its the only way to get youtube live tv running on fire tv.   However is there going to be any updates to the youtube live tv currently the apk is running on 480p and 30fps ..   An update to 1080p and 60fps would be very much appreciated

**Comment by yuliskov** [comment]
@javagirl209 yup, its because of drm protection in higher qualities. I'm not sure what I can do with that.

**Comment by javagirl209** [comment]
Thank you for replying..but u said yep...does that mean u will be updating
the apk but won't be able to get higher resolution due to drm

On May 3, 2018 10:12 PM, "Yuriy Lyskov" <notifications@github.com> wrote:

@javagirl209 <https://github.com/javagirl209> yup, its because of drm
protection in higher qualities. I'm not sure what I can do with that.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yuliskov/SmartYouTubeTV/issues/112#issuecomment-386507108>,
or mute the thread

**Comment by yuliskov** [comment]
@javagirl209 off course there will be updates when I find a solution.

**Comment by yuliskov** [comment]
Wont fix
