### ISSUE TITLE
play 4K picture is not moving

### ISSUE THREAD

**Issue by xiaoxihu2017** [yuliskov/SmartYouTubeTV#113]
Xiaomi TV 55 and xiaomitv 65
2 TV, play 4K picture is not moving, play 1080P normal, play 2.5K normal.
Remember that the oldest version can be played, and the latest version can not play 4K..

**Comment by yuliskov** [comment]
@xiaoxihu2017 its widely known problem with vp9 codec. If someone has a solution, pls let me know.

**Comment by e68862230** [comment]
Maybe MiTV doesn't support VP9 hardware decoding and it leads to vp9 codec can't work well....

**Comment by yuliskov** [comment]
Closed, since its internal hw issue
