### ISSUE TITLE
Video quality options

### ISSUE THREAD

**Issue by kinngjatt** [yuliskov/SmartYouTubeTV#115]
In my tv videos play only in "Mi TV & Legacy" mode. But the options to select video quality are difficult. Please add simple options like 240p 360p 720p etc...  Like they are in FireTV mode.
I tried FireTV mode but it says "Loading Video..." always. So please add simple options in FireTV & Legacy. Thanks!

**Comment by kinngjatt** [comment]
Ome more thing. Why My TV only play videos on "mitv and legacy (4k) mode" 
Why on on the first mode that is firetv ?

**Comment by yuliskov** [comment]
@kinngjatt its ok. FireTV not always means all devices, just most of them.

**Comment by rodalpho** [comment]
The different mode names are indeed very confusing. The 720 mode plays 1080p just fine, and in fact is the right choice for my streamer. Would be better to remove the 720/1080/4k labels and just name them by the playback engine and/or examples of devices they work on.

**Comment by yuliskov** [comment]
> name them by the playback engine and/or examples of devices they work on.

Maybe other suggestions? I know that current solution isn't perfect, but naming as engines... Personally, I don't like that idea.

**Comment by rodalpho** [comment]
Maybe a better option would be to given them cute names like types of vegetables, Butternut Squash, Pumpkin, Zucchini, etc, and then list examples of popular devices they work on below that. Really anything other than labeling one "720" when it works at 1080p/4k would be an improvement.

**Comment by yuliskov** [comment]
Launchers have been renamed according to max quality supported.
