### ISSUE TITLE
What version i should use for android boxes. 

### ISSUE THREAD

**Issue by veluvoludba** [yuliskov/SmartYouTubeTV#116]
2GB RAM box. 
running android version 5.1.1

**Comment by yuliskov** [comment]
@veluvoludba start with latest. Try each launcher one by one until you find something useful.
https://drive.google.com/uc?id=1PNL6uaRdKZS56f0fqtd9QZUU5WE-75ob

**Comment by veluvoludba** [comment]
thanks for the advice.
