### ISSUE TITLE
Pre-buffer next video

### ISSUE THREAD

**Issue by GOZARCK** [yuliskov/SmartYouTubeTV#120]
I would like once the current video loaded in buffer, pre-buffer the next video a few seconds for a smooth start the next video.

**Comment by yuliskov** [comment]
@GOZARCK thanks for the feedback. You're talking about stutters on 4K launcher, right?

**Comment by GOZARCK** [comment]
That's right. Thanks!

**Comment by yuliskov** [comment]
@GOZARCK this difficult to fix. I meet some technical limitations there.

**Comment by GOZARCK** [comment]
Don´t  worry, it's just a cosmetic suggestion.  your project is awesome! GO ON!

**Comment by yuliskov** [comment]
Closed. Behavior couldn't be changed.
