### ISSUE TITLE
The Smart YouTube TV for the offical YouTube app needs to run for a better frame rate at all times

### ISSUE THREAD

**Issue by zakaboy2000** [yuliskov/SmartYouTubeTV#122]
OK, so the problem to me on Amazon Fire TV Stick 2nd Generation for YouTube is that I wanted to bring back the moving image to 60fps, and also the video playback issue that should have to get 30fps and 60fps for the official app that should continue working on them too. Can you please fix the situations as well? The device model is: MT8127D

**Comment by yuliskov** [comment]
@zakaboy2000 thanks.

**Comment by zakaboy2000** [comment]
You're welcome. Hope the 2017 interface 
and the logos houldd be super better much bugs & improvements.

**Comment by zakaboy2000** [comment]
You're welcome. Hope the 2017 interface 
and the logo should be super better much 
bugs and improvements like that for always.

**Comment by zakaboy2000** [comment]
Anything else that's been very good yet, yuliskov?

**Comment by yuliskov** [comment]
@zakaboy2000 I'll let you know in case there will be changes

**Comment by zakaboy2000** [comment]
Thank you for replying to me.

**Comment by zakaboy2000** [comment]
Can you please and try to fix the problem issue one more time? I found the model number on the back of the firestick from it and I'll you that right now. It's LY73PR

**Comment by zakaboy2000** [comment]
Actually, no. It's G070L80971662B4D

**Comment by zakaboy2000** [comment]
Nope, actually the model that I have it says LY73PR.

**Comment by yuliskov** [comment]
Do anyone experience the same? It would be good to have input from other users too.

**Comment by TheLegendaryKillerXD** [comment]
You can delete this to put invalid now. Cause he doesn't really need it anymore.
