### ISSUE TITLE
Video pauses suddenly

### ISSUE THREAD

**Issue by 1an6** [yuliskov/SmartYouTubeTV#124]
have been using this app for a while in my mibox, work smooth until recently
in 6.8.2 version, video pause occasionally, i suspect it pause when reach ads?
in latest version, app jump out occasionally, suspect the same reason, and interface load extremely slow
can you fix it please?

**Comment by yuliskov** [comment]
@1an6 hello. Please, give me detailed feedback on latest version. I need an info about all four included launchers.

**Comment by 1an6** [comment]
@yuliskov hi sir, sorry layman here, how should i get the feedback for you?

**Comment by yuliskov** [comment]
@1an6 bump

**Comment by 1an6** [comment]
@yuliskov Yes, it happens in all the launchers.

**Comment by yuliskov** [comment]
@1an6 even on 4K launcher? Then it couldn't be an ads because 4K launchers have standalone player. Or maybe you're talking about stutters inside UI?

**Comment by yuliskov** [comment]
@1an6 pls attach screens from CPU-Z

**Comment by 1an6** [comment]
@yuliskov here u go
![img_9007](https://user-images.githubusercontent.com/29710203/40401193-df6dadcc-5e77-11e8-8aaf-3876d3803ef3.JPG)
![img_9008](https://user-images.githubusercontent.com/29710203/40401195-df9c89bc-5e77-11e8-93a7-ff0a8c848a8b.JPG)
![img_9009](https://user-images.githubusercontent.com/29710203/40401196-dfca7714-5e77-11e8-9a48-7ca364b2f2eb.JPG)

**Comment by yuliskov** [comment]
@1an6 thanks. Pls test, especially 720 and 1080 launchers. https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.92/SmartYouTubeTV_Orig_v6.12.92_r.apk

**Comment by yuliskov** [comment]
Should be fixed
