### ISSUE TITLE
HDR is not work on Sony TV XE9305

### ISSUE THREAD

**Issue by Scoty43** [yuliskov/SmartYouTubeTV#125]
I have install latest Version on my Sony XE9305 and whene i play a HDR Video the TV show me HDR but its a fake HDR. The Picture settings are not switched in HDR, they stay on standard and not on maximum as it should be with HDR. I have use 4K old.

**Comment by yuliskov** [comment]
@Scoty43 thanks for the feedback. Can't test it at a moment.

**Comment by Kaan88** [comment]
That's the fault of the tv, happens with all of the players when you use a VP9 hdr file. Kodi, vlc, official player etc. You need to go into video settings and switch video format to hdr10 manually to get real HDR unfortunately.

**Comment by yuliskov** [comment]
@Kaan88 sorry, I've done all I've could. Without the device I cannot fix the bug.
