### ISSUE TITLE
Thomson smart tv my video error. 

### ISSUE THREAD

**Issue by manrock111** [yuliskov/SmartYouTubeTV#126]
First of all, 
Thanks god that you running this project, thanks brother i like it alot, I come to know about it 4 days back. Till now i enjoyed it alot. Now back to issues.

1. Getting 'unable to initiate omx.amlogic.awesome.player.decoder' error on videos but somehow able to view video most of the times. 

2. I'm not able to watch my videos? 

3. 4k video not working, picture hang still when start playing. 

To troubleshoot i downloaded from version. 83 to latest 91.

I tried all launcher, till date I found 4k alt version with 1080p vp9/aac codec restriction working great.

I really want to see atleast 2k video if not 4k and my account videos. 

Cause i upload all of my family videos unlisted under my account. For backup.

**Comment by yuliskov** [comment]
@manrock111 appreciate your support.
1. This messages can be disabled via settings (right near quality options).
2. Are sure that your device capable of handling 4k@vp9?
3. Confirmed. Thanks.

**Comment by manrock111** [comment]
1. Done.

2. I think 4k vp9 not possible but 1080 no problem. Even 4k,2k aac,x 265, x264 no problem.

3. I want to see my personal uploaded account videos on player.

**Comment by manrock111** [comment]
1. Done.

2. I think 4k vp9 not possible but 1080 no problem. Even 4k,2k aac,x 265, x264 no problem.

3. I want to see my personal uploaded account videos on player.

**Comment by manrock111** [comment]
Thanks bro, but app just crash as I click on video on my upload.

Otherwise everything working. I tried every launcher with all resolution settings.

**Comment by yuliskov** [comment]
@manrock111 strange, I've uploaded couple of videos. And all worked fine. Could I ask you to give me a sample of your video?

**Comment by manrock111** [comment]
Those are personal family videos. Some are shoot in 4k and most of are in lower res.

But I chose 1080 codec restriction.

I will make one video tommorow and gave you the link.

**Comment by manrock111** [comment]
https://youtu.be/BFtMQUB6f20

Sorry for bad quality, I hope you get the idea.

**Comment by yuliskov** [comment]
@manrock111 nothing suspicious here. I don't have any troubles. Anyway, next try is below.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.94/SmartYouTubeTV_Orig_v6.12.94_r.apk

**Comment by manrock111** [comment]
Only audio is playing and no seek bar coming. One boolean error showing.

Kindly check this out. 
https://youtu.be/dD10Gu-YO9A

**Comment by yuliskov** [comment]
@manrock111 thanks again for the great feedback! Another update to address this issue is here.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.95/SmartYouTubeTV_Orig_v6.12.95_r.apk

**Comment by manrock111** [comment]
Thanks bro this version seems to work. I'm able to watch it on tv.

But I have noticed. When video ends then its taking too long to come back to previous screen. Otherwise it stays At 'loading' screen.

**Comment by manrock111** [comment]
I have notice 2 minor bugs.

1. Phone youtube app Seek bar and play button not working or syncing with tv playback time.

2. Volume control through app not working.

**Comment by yuliskov** [comment]
@manrock111 thanks, but this couldn't be fixed right now. Sorry, friend.
