### ISSUE TITLE
The Smart YouTube TV for the official YouTube app has to show the buttons on the right button corner of the screen that says go back and everything else

### ISSUE THREAD

**Issue by zakaboy2000** [yuliskov/SmartYouTubeTV#127]
So currently, they have to show up on the Amazon Fire TV stick 2nd gen that they tell me which where I go to and how to exit out of there too. Hopefully it's be fixed as well as possible when I get to chance to see it.

**Comment by yuliskov** [comment]
@zakaboy2000 hi, could you post a screenshot with needed buttons?

**Comment by zakaboy2000** [comment]
Yeah, I will

**Comment by zakaboy2000** [comment]
![img_20180603_194204](https://user-images.githubusercontent.com/39468120/40893472-f51bf262-6766-11e8-99b7-93926103512b.jpg) It tells us like "Go Back" still I would say and "Exit".

**Comment by zakaboy2000** [comment]
Hello, are you still there?

**Comment by yuliskov** [comment]
> Hello, are you still there?

anytime

**Comment by zakaboy2000** [comment]
I already showed you the back button where it needs to be added to Amazon Fire TV & TV stick devices

**Comment by zakaboy2000** [comment]
And it's the one with the screenshot that you can see right now.

**Comment by yuliskov** [comment]
@zakaboy2000 got it. Thanks.

**Comment by yuliskov** [comment]
Done
