### ISSUE TITLE
Could not find fabric.aar (io.fabric.sdk.android:fabric:1.4.1). Searched in the following locations:     https://jcenter.bintray.com/io/fabric/sdk/android/fabric/1.4.1/fabric-1.4.1.aar

### ISSUE THREAD

**Issue by liufuqiang453** [yuliskov/SmartYouTubeTV#128]
Could not find fabric.aar (io.fabric.sdk.android:fabric:1.4.1).
Searched in the following locations:
    https://jcenter.bintray.com/io/fabric/sdk/android/fabric/1.4.1/fabric-1.4.1.aar

**Comment by yuliskov** [comment]
@liufuqiang453 donno why is that. Setup is done according to the manual:
https://docs.fabric.io/android/crashlytics/build-tools.html

**Comment by abhijeetbhosale** [comment]
I am also getting same issue. 
After updating the Android studio. Below are Android studio version details.
Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by Diwakar1988** [comment]
I am also getting same issue
