### ISSUE TITLE
a bit little more lag when subtitle opened

### ISSUE THREAD

**Issue by firewiki** [yuliskov/SmartYouTubeTV#13]
I try the verstion 6.8.2 and the version 6.8.29, when subtitle(auto-generating english subtitle) is opened, the voice and the video is a little more lag.

My tv box  is M8S+ which is using Amlogic S812 chipset.

**Comment by firewiki** [comment]
Still has bad performance compared to official app. May be the exoplayer version will be more better, but it does't surpport subtitle. I really love this app, waiting for your improvement, thank you.

**Comment by yuliskov** [comment]
Its decoder issue. I've added more versions to address such issue.
