### ISSUE TITLE
Fire TV Stick: Lagging/Stuttering after >30 Minutes Playback

### ISSUE THREAD

**Issue by molabs** [yuliskov/SmartYouTubeTV#133]
Version: 6.12.96 (Also affects the versions before that)
Fire TV Stick 1. Generation
If I watch a lets play of 45-60 minutes, the video usually starts after ~30 minutes to lag/stutter and the app is barely usable. Reproducible on 2 FireTV Sticks.

**Comment by yuliskov** [comment]
duplicate of #74
