### ISSUE TITLE
SmartYouTubeTv can not forward and rewind on MiBox 3

### ISSUE THREAD

**Issue by blueyestar** [yuliskov/SmartYouTubeTV#139]
When playing a video, press forward or rewind button, nothing change.

**Comment by yuliskov** [comment]
> press forward or rewind button
Do you mean prev/next buttons under the video?

**Comment by blueyestar** [comment]
@yuliskov I am talking about the remote coontroller.

**Comment by yuliskov** [comment]
@blueyestar may I ask you the link to the your controller model?

**Comment by blueyestar** [comment]
@yuliskov It's the original controller for MiBox 3 MDZ-16-AA

**Comment by yuliskov** [comment]
@blueyestar hmm, as I know, original controller doesnt have special buttons like rewind

**Comment by blueyestar** [comment]
@yuliskov Sorry for the misleading description. I mean the circle button which acts like forward or rewind when you press left or right.

**Comment by yuliskov** [comment]
@blueyestar ok, I got it. Seems that it is an normal behavior. Circle button inside video shows player ui.
