### ISSUE TITLE
Not working well on MiBox Mini

### ISSUE THREAD

**Issue by Cappuccin0** [yuliskov/SmartYouTubeTV#14]
In recent builds, the resolution doesn't look correct on MiBox Mini, only part of screen is in visible area.
I have tried version 6.8.6 which works good, and builds after 6.8.14 seems having above issue.

**Comment by yuliskov** [comment]
OK. I'll check it.

**Comment by yuliskov** [comment]
https://github.com/yuliskov/SmartYouTubeTV/releases/tag/6.8.35

>

**Comment by Cappuccin0** [comment]
Tested on 6.8.35, works perfectly. Thanks!
