### ISSUE TITLE
Migrate to a supported webview

### ISSUE THREAD

**Issue by SatanicMechanic** [yuliskov/SmartYouTubeTV#141]
Crosswalk Project Is EOL, with the last version published in December 2016. While I'm not too concerned about the security vulnerabilities in a site specific app, there are other benefits to using current versions of blink and chromium.

**Comment by yuliskov** [comment]
As I know the first launcher should use Supported WebView

**Comment by yuliskov** [comment]
Seems that Supported WebView should work without any code change on the first launcher.
