### ISSUE TITLE
Virtual keyboard with external keyboard

### ISSUE THREAD

**Issue by hussainalhaddad** [yuliskov/SmartYouTubeTV#142]
Virtual keyboard opens up automatically in search, i can still type using my external keyboard but pressing enter, OK or even GO on the virtual keyboard doesn't seem to work, and pressing escape to hide the virtual keyboard takes me back to the left navigation bar.

Can you please add an option to disable the virtual keyboard completely?

Thanks

**Comment by yuliskov** [comment]
Hi. Please tell me, what type of keyboard do you have? It is bluetooth kbd?

**Comment by hussainalhaddad** [comment]
Yes, it's a combo bluetooth and touchpad.

[https://www.amazon.com/Rii-Bluetooth-Wireless-Touchpad-Rechargable/dp/B00JO80LVW](url)

**Comment by WolfganP** [comment]
@hussainalhaddad I installed `null keyboard` from play store and configured it as default in the box options. No more vkb onscreen! :-)

**Comment by yuliskov** [comment]
@hussainalhaddad thanks for the reply. Have you tested latest update for [LeanKeyKeyboard](https://github.com/yuliskov/LeanKeyKeyboard/releases)? Seems that latest update is what you seeking for. Link and changes below.

Changes:
- soft keyboard hides itself when user tries to type something on the physical keyboard

https://github.com/yuliskov/LeanKeyKeyboard/releases/download/4.3.21/LeanKeyKeyboardPro_v4.3.21_r.apk

**Comment by hussainalhaddad** [comment]
@yuliskov yeah tested it, but didn't work for me. The official YouTube app works fine without third party keyboard though.

@WolfganP Yeah, sometimes i use a remote, so i have to switch back to leanback keyboard.

**Comment by yuliskov** [comment]
@hussainalhaddad seems that you've tested old kbd release. I've patched kbd today to support physical kbd.

**Comment by WolfganP** [comment]
@yuliskov thanks! I'll try it as well. What's the intended behavior? Does the vkb hides when a phys key is touched, or does it not show at all (as with null keyboard)?

**Comment by hussainalhaddad** [comment]
@yuliskov no, just downloaded now as you mentioned it

**Comment by yuliskov** [comment]
@WolfganP kbd popups like usual. Nothing special there. It hides itself only if glyph key has been pressed on physical kbd.

@hussainalhaddad I'll search for the solution

**Comment by yuliskov** [comment]
@hussainalhaddad here's an updated kbd

how to test:
- select desired field (e.g. search), virtual kbd popups
- now start typing on your hard kbd
- soft kbd should disappear until you move to the next field

download:
https://github.com/yuliskov/LeanKeyKeyboard/releases/download/4.3.22/LeanKeyKeyboardPro_v4.3.22_r.apk

**Comment by hussainalhaddad** [comment]
thanks a lot @yuliskov it's working now.

**Comment by yuliskov** [comment]
@hussainalhaddad great to hear that kbd works as expected. In the next release I'll adjust GO button button to always hide kbd. Esc bug need more research but I think I could fix it too. Thanks for the feedback.

**Comment by yuliskov** [comment]
@hussainalhaddad update with possible fixes for ESC and Go keys

https://github.com/yuliskov/LeanKeyKeyboard/releases/download/4.3.23/LeanKeyKeyboardPro_v4.3.23_r.apk

**Comment by hussainalhaddad** [comment]
@yuliskov Still the same, unfortunately

**Comment by yuliskov** [comment]
@hussainalhaddad another try. Hope it working now.

https://github.com/yuliskov/LeanKeyKeyboard/releases/download/4.3.24/LeanKeyKeyboardPro_v4.3.24_r.apk

**Comment by hussainalhaddad** [comment]
@yuliskov same thing :(

**Comment by yuliskov** [comment]
Better place for the issue: https://github.com/yuliskov/LeanKeyKeyboard/issues
