### ISSUE TITLE
Error: Request was denied for security

### ISSUE THREAD

**Issue by randoloh820911** [yuliskov/SmartYouTubeTV#145]
Error: request was denied for security. Huawei TV box pro, worked for the first run after installation. then crosswalk was installed and smart YouTube TV is available. once the software was closed. the smart YouTube TV wont work anyone. thanks!

**Comment by yuliskov** [comment]
@randoloh820911 thanks for the your support. Could you attach an screenshot with error?

**Comment by nyakze** [comment]
Started getting this as well

**Comment by yuliskov** [comment]
Does the problem still there?

**Comment by nyakze** [comment]
It seem to have resolved itself, thanks!
