### ISSUE TITLE
"Loading..." message or black screen issues...

### ISSUE THREAD

**Issue by gilcio** [yuliskov/SmartYouTubeTV#146]
Hi there!
I've tried the last app version in my nVidia Shield TV (Oreo) but it keeps freezing:
- In a playlist, the second or third video doesn't start playing: "Loading..." message or black screen forever;
- I get a black screen sometimes even when playing one video only.

**Comment by mattiashking** [comment]
I have to correct my previous statement, automatic play is working OK. Between videos there is annoying PLAY logo only

**Comment by yuliskov** [comment]
@gilcio is the problem solved with the latest update?

**Comment by yuliskov** [comment]
I think the issue should be redirected here #83
