### ISSUE TITLE
bypass regional restrictions

### ISSUE THREAD

**Issue by dimzon** [yuliskov/SmartYouTubeTV#147]
Для обхода блокировок попробуйте случайные "буржуйские" IP подставить в заголовок https://en.wikipedia.org/wiki/X-Forwarded-For

**Comment by yuliskov** [comment]
@dimzon спасибо, вроде как перспективная вещь. Жаль что сервера ютуба на этот заголовок не реагируют.

**Comment by yuliskov** [comment]
duplicate of #42
