### ISSUE TITLE
Autoframe - Videos play a lot slower with setting turned on

### ISSUE THREAD

**Issue by mo123** [yuliskov/SmartYouTubeTV#148]
Hi

If I enable autoframe setting in Video Quality, then the screen blanks for a second, so it means autoframe switching is working, but videos then look like they play much slower 15-20fps or with skipped frames.
Turning autoframe setting off again, videos play much smoother again on a Rockchip RK3328 Nougat media player.

Can you also force to use VP9 instead of AVC1 if available when using autoframe as it seems to work a little better?

Is there a way to improve it or a log I can get to maybe show the problem?

Thanks

**Comment by yuliskov** [comment]
@mo123 hi there, codec can be restricted inside main boot screen

**Comment by yuliskov** [comment]
AFR is heavily dependent on hw. I can't do much there.
