### ISSUE TITLE
Please document the different  releases

### ISSUE THREAD

**Issue by WolfganP** [yuliskov/SmartYouTubeTV#15]
Hi, FOA, thanks a lot for this project, it gave more life to my generic Android 4.4 box improving the leanback experience.

Regarding the releases, could you please document what the diff version flavors (Original, Exoplayer, Xwalk) are intended for? And which one you recommend to start playing with? (ie this one is in active development, this one for fallback purposes if X doesn't work, etc)
Thanks again!

**Comment by yuliskov** [comment]
Hi. Yes its good idea. I'll add note about different versions. You may want
to start play with Original version. If you experience playback problems
then try XWalk one. Finally, Exoplayer version is intended for those whom
previous two versions didn't help. Other versions is for specific devices
only, but you can try them too.

**Comment by WolfganP** [comment]
Excellent, thanks!

**Comment by WolfganP** [comment]
@yuliskov Now that you implemented the unified launcher, is the selection of 720 / 1080 / 4K / 4K alt tied to any particular player as in the old flavors? (Original, Exoplayer, Xwalk)

**Comment by yuliskov** [comment]
@WolfganP yes, I've merged all flavors in to one.
720 - original
1080 - XWalk
4K - Exoplayer
4K Alt - Exoplayer with fixes

**Comment by WolfganP** [comment]
@yuliskov Thanks again for the explanation on the versions. The exoplayer version works beautifully in my FullHD box (better perceived picture quality than the original) but it seems to choose the 4K video resolutions if available (when my box is only 1080p capable) and the app crashes.

Is there any way to config the use the Exoplayer version but limit it to a certain max resolution? (ie 720p or 1080p)

**Comment by yuliskov** [comment]
@WolfganP have you tried to select resolution manually? Player should stay at that resolution as long as it could. Also you can find limit option on the main screen.

**Comment by WolfganP** [comment]
> have you tried to select resolution manually? Player should stay at that resolution as long as it could. Also you can find limit option on the main screen.

Thx @yuliskov . I tried manual resolution selection but I can't select it as the video starts to load and the app crashes before I can even go to the quality options popup, that's why I looking for any global setting somewhere (ie decoupling the player selection from the max/preferred resolution)

**Comment by yuliskov** [comment]
@WolfganP find option named 'Codec' on the main boot screen, then. I think that is what you want.

**Comment by Pentaphon** [comment]
@yuliskov 

The latest version (6.17.697) says the following:

**PRO Main - PRO Alt - LITE Main - LITE Alt**

Which doesn't match the current README. 

Does PRO = 4K? 1080 = LITE? Is it safe to say that PRO now means Exoplayer and LITE now means Original Youtube Player? And Alt means you need XWalk while Main means Webview which is already built-in?

Can we get more info in the app settings to make these facts more clear?
