### ISSUE TITLE
Enlarge the resolution after view 4k files

### ISSUE THREAD

**Issue by rickywwk** [yuliskov/SmartYouTubeTV#150]
After view 4K files and then return to youtube home screen, all things got enlarged. Please help.

**Comment by yuliskov** [comment]
Remove app and install again from scratch.

**Comment by rickywwk** [comment]
I'm new installed. Still need remove the app and install again ?

**Comment by yuliskov** [comment]
Yes. And post here screens your device info. Screenshot with a bug also welcomed. Thanks for your support.

**Comment by yuliskov** [comment]
Closed, untill issue will be updated
