### ISSUE TITLE
Auto update for SmartYoutubeTV?

### ISSUE THREAD

**Issue by mo123** [yuliskov/SmartYouTubeTV#154]
Possible to upload latest versions to APKPure app store or something they must do? Users can then use the latest version and APKPure app store will install updates when available.

Or some other way to auto update when a new version is released inside the app?
I read such a feature is already added but never got an update on an old version.
How can you check for an update, it happens automatically on start?

Thanks

**Comment by yuliskov** [comment]
> How can you check for an update, it happens automatically on start?

Yes, exactly! APKPure builds have autoupdate too.
