### ISSUE TITLE
Video stops over and over, 6.14.26

### ISSUE THREAD

**Issue by edgan** [yuliskov/SmartYouTubeTV#158]
I was trying to watch a video, and the video stops. I press A on my Nvidia Shield controller twice to get it to pkay again. Then some seconds later it stops again. I got through 10 minutes of a 12 minute video, and it had stopped at least ten times, and at sometimes seconds apart. I haven't had this issue before. I updated last night, but didn't see this issue last night. The regular app doesn't do this, and I didn't get ads either. Also tried force stopping the app to see if it would help, but still got stops on the same video.

**Comment by yuliskov** [comment]
@edgan does all four included launchers have the same issue?
