### ISSUE TITLE
B as back button on Nvidia shield

### ISSUE THREAD

**Issue by edgan** [yuliskov/SmartYouTubeTV#159]
It would be awesome to have the B button on my Nvidia Shield controller to act like the back button. Overall  if the controls acted like the official app that would be great.

To support this would it require key mapping? If you don't own one, would owning a Nvidia Shield help?

**Comment by yuliskov** [comment]
@edgan pls, bring me keycode of this button. In order to do this run app below and press desired key. App should show your keycode. Then make an screenshot and post it here.
App: https://drive.google.com/uc?id=0ByORA7yiJiQXdENBSENfczU4ZU0

**Comment by yuliskov** [comment]
I assume that all is working fine now.
