### ISSUE TITLE
Not playback with some videos on 6.14.43 version

### ISSUE THREAD

**Issue by RedTestament** [yuliskov/SmartYouTubeTV#162]
Yesterday I was using 6.14.35 version, but since the last update 6.14.43, many of the videos on the part of suggestions inside the videos, custom list, and later are not playing, and only loading screen appears, also in the subscription part many videos are not playing too, I reinstalled the apk with same result.

Using Android 6.0 on a TV box model T96pro

**Comment by yuliskov** [comment]
@RedTestament you need to help me. Pls, check the unstable releases archive. Try to find the latest one without such bug. Link below.
https://github.com/yuliskov/SmartYouTubeTV/releases

**Comment by yuliskov** [comment]
@RedTestament also, I'll appreciate if give me info about all four included launchers. Does this issue appear on all of them?

**Comment by yuliskov** [comment]
@RedTestament seems that I've found the problem. Please, post there screens from the CPU-Z > Device tab.

**Comment by RedTestament** [comment]
Thanks, the bug is solved in 6.14.45 version
