### ISSUE TITLE
Video paused continue watching prompt

### ISSUE THREAD

**Issue by co5mo** [yuliskov/SmartYouTubeTV#165]
youtube has added some binging protection... 
https://imgur.com/a/j7wrBBb
can we disable that?

**Comment by yuliskov** [comment]
@co5mo hi, I've not spotted changes you're talking about

**Comment by co5mo** [comment]
it is triggered after like an hour of not touching anything

**Comment by yuliskov** [comment]
@co5mo thanks, I'll check it

**Comment by yuliskov** [comment]
I'll deal with it later. Looks like it's not so serious issue.
