### ISSUE TITLE
I can't watch it when I use China tunnel VPN.

### ISSUE THREAD

**Issue by mmsean** [yuliskov/SmartYouTubeTV#166]
China tunnel VPN compatible issues, can you handle it?I only start China tunnel VPN and only the URL will appear. I can't enter the app. I don't know if I can solve it. Thank you.

**Comment by yuliskov** [comment]
@mmsean how it works compare to the original youtube app? Link below:
https://www.apkmirror.com/apk/google-inc/youtube-for-android-tv-android-tv/

**Comment by yuliskov** [comment]
Closed. I don't have enough resources to test this case.
