### ISSUE TITLE
Check for update button

### ISSUE THREAD

**Issue by nyakze** [yuliskov/SmartYouTubeTV#167]
Would be nice to be able to check for updates manually in the menu. I know it checks on startup but if you decline it, the dialog doesn't appear until the new update has come out and sometimes I need to open YouTube fast so I discard update dialog, but would like it to ask again or a way to check for updates manually.

**Comment by yuliskov** [comment]
@nyakze you're not quite right. Yes, update dialog shouldn't bother you some time after you press cancel. But this time limited by 6 hours. If you're still not see it, then it's because of high load on the update server. That is the case why I will not add manual update check.
