### ISSUE TITLE
[Fire TV] Random restart of the Cast from Phone playlist

### ISSUE THREAD

**Issue by doktormerlin** [yuliskov/SmartYouTubeTV#168]
After some time being in the app without clicking a button, the cast from phone playlist starts playing again sometimes (randomly). It usually starts with the first video in the playlist, sometimes it starts with a video from somewhere in the middle of the playlist.

Steps to reproduce:
Start a cast from phone
Play some videos and add some to the current playlist
Finish all the videos
Wait in the suggestions or subscription list
Playlist at some point starts playing again

Device: Fire TV Stick 2
Version: newest one, issue has been there for long

**Comment by yuliskov** [comment]
@doktormerlin many thanks. I'll check it.

**Comment by yuliskov** [comment]
should be fixed in the latest release

**Comment by doktormerlin** [comment]
It seems that the issue is not due to SmartYoutubeTV but to YouTube Vanced. Closed.
