### ISSUE TITLE
Unified version selected resolution doesn't stay

### ISSUE THREAD

**Issue by WolfganP** [yuliskov/SmartYouTubeTV#17]
Just a question regarding these latest unified versions: Should the selected resolution on first run stay as default for next runs or is it intended to select the resolution at start every time the app is invoked? 
(because I have to select the resolution every time, and I don't know if it's the intended behavior or a bug that I need to provide logs for)
Thanks!

**Comment by yuliskov** [comment]
Fixed in latest release.
