### ISSUE TITLE
Autoplay set to off but still playing next video or suggested video

### ISSUE THREAD

**Issue by dv8ed** [yuliskov/SmartYouTubeTV#171]
In settings I have Autoplay set to off but after video is done playing it plays another video. 

6.14.31 is last version I remember where autoplay off doesn't play another video. I'm using a Shield TV.

**Comment by yuliskov** [comment]
Thanks, bug is confirmed

**Comment by yuliskov** [comment]
fixed in the latest beta:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.14.74/SmartYouTubeTV_Orig_v6.14.74_r.apk

**Comment by yuliskov** [comment]
wait confirmation
