### ISSUE TITLE
Suggested video preview only working on 1080P launcher but not working on 4K launcher ?

### ISSUE THREAD

**Issue by ZhenyaKanaeva** [yuliskov/SmartYouTubeTV#174]
Dear sir, the suggested video preview work on 1080P launcher but no preview on 4K launcher ? Can you fix it or add this features in to 4K launcher ? TQ !

1st picture is the suggested video preview under 1080P launcher ; and the 2nd picture is 4K launcher without suggested video preview... TQ !

https://i.imgur.com/6AA7Qo8.jpg
https://i.imgur.com/07ebGe5.jpg

P/S : Version 6.14.55

![6aa7qo8 1](https://user-images.githubusercontent.com/5897464/47287402-ccd74380-d5fa-11e8-86c6-320a904d07fd.jpg)
![07ebge5 1](https://user-images.githubusercontent.com/5897464/47287426-d6f94200-d5fa-11e8-9814-37b74e04b4a2.jpg)

**Comment by yuliskov** [comment]
@ZhenyaKanaeva hi, I have no plans to change this behavior in the future. Main cause is the lack of the free time.

**Comment by yuliskov** [comment]
Closed for now since I've no plans on rework on this in meantime.
