### ISSUE TITLE
Video length is zero

### ISSUE THREAD

**Issue by BH1ENO** [yuliskov/SmartYouTubeTV#176]
We are behind firewall and have to use VPN to use Youtube. 
When open a video with Youtube, the video plays normally. Like below.
![image](https://user-images.githubusercontent.com/17289895/47471320-56298880-d83c-11e8-84ed-c019e7f73b48.png)

When open a video with SmartYouTubeTV, the length of the video is zero. Like belows.
![image](https://user-images.githubusercontent.com/17289895/47471382-90932580-d83c-11e8-856b-2657f509d314.png)

![image](https://user-images.githubusercontent.com/17289895/47471388-95f07000-d83c-11e8-9fd4-d2fc56471da9.png)

**Comment by yuliskov** [comment]
@BH1ENO have you tried all four included launchers? If no, then do it. Especially, I suggest you to try 4K launcher. Also, please give me the screenshot with debug info (button inside options) and CPU-Z screenshot with Device tab opened. Thanks.

**Comment by yuliskov** [comment]
@BH1ENO debug info could be found below the video, under options. It's usually rightmost button in the row. 
To obtain info from CPU-Z, you need to open CPU-Z, switch to the Device tab and take screenshot.

**Comment by BH1ENO** [comment]
I cannot find the options in my screen. Could you please give me a picture to show the position or point it out in my screen capture?

**Comment by yuliskov** [comment]
@BH1ENO forget about options, friend. It's not top priority now. Why couldn't you give me the output from CPU-Z?

**Comment by BH1ENO** [comment]
Well, please see the attachments.
![2018-10-26_202403](https://user-images.githubusercontent.com/17289895/47566293-ddbae880-d95d-11e8-9602-ed66d1fa9745.png)
![2018-10-26_202427](https://user-images.githubusercontent.com/17289895/47566298-e14e6f80-d95d-11e8-9819-06f6b30737ac.png)
![2018-10-26_202441](https://user-images.githubusercontent.com/17289895/47566299-e4496000-d95d-11e8-9eb1-3dd6a0943e74.png)

**Comment by yuliskov** [comment]
@BH1ENO many thanks! I'll publish test build within a couple of hours.

**Comment by yuliskov** [comment]
beta release: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.14.58/SmartYouTubeTV_Orig_v6.14.58_r.apk

**Comment by BH1ENO** [comment]
This is the message  from first run of the  new version.
![2018-10-27_143512](https://user-images.githubusercontent.com/17289895/47600568-b7488c00-d9f5-11e8-8720-e36b3b57d377.png)

I tried the first launcher. This time, The video length is correct. But there are two strange things. The fist one, there is only audio and the screen is black when play any video. The second one is the audio continues playing even after the video is paused.

**Comment by yuliskov** [comment]
@BH1ENO thanks for the feedback. It's definitely codec issue. Maybe with second 1080 launcher you get lucky. You definitely should try it.

**Comment by BH1ENO** [comment]
Yes, the second 1080p player works after installing the cross talk. And the first  1080p  player can play only audio.


Yuriy Lyskov <notifications@github.com<mailto:notifications@github.com>> 于 2018年10月27日周六 下午5:10写道：

@BH1ENO<https://github.com/BH1ENO> thanks for the feedback. It's definitely codec issue. Maybe with second 1080 launcher you get lucky. You definitely should try it.

**Comment by yuliskov** [comment]
Close, because the problem is solved (some kind of).
