### ISSUE TITLE
Ability to configure HTTP/SOCKS proxy in app

### ISSUE THREAD

**Issue by wangjia184** [yuliskov/SmartYouTubeTV#177]
It would be better to be able configure HTTP/SOCKS proxy in app.

We are from China and Youtube is inaccessible here. And device like MiBox does not allow configure global proxy

**Comment by yuliskov** [comment]
@wangjia184 hi, friend. The current project state is freezed. New features are not accepted. So I'm closing issue for now.

**Comment by whtsky** [comment]
Hi @yuliskov , looks like the project is not frozen now, can you reconsider this feature request? Thanks
