### ISSUE TITLE
Audio Distortion 1080 Alt

### ISSUE THREAD

**Issue by Timbo200** [yuliskov/SmartYouTubeTV#178]
An odd bug has cropped up in the last week.  Audio on certain videos breaks up, but not on others.  It only happens on 1080 Alt.  The others seem to work fine.

Sample video:
https://youtu.be/PBoaCHmvCZY

Thanks!

**Comment by yuliskov** [comment]
@Timbo200 it's definitely codec issue. Unfortunately, I don't have full control over codecs that are used in specific launcher.

**Comment by Timbo200** [comment]
Interesting.  Something must have switched on  Google's back end as it just started.  Sorry to read it's not something you can control.
