### ISSUE TITLE
After upgrading the new version, why does the remote control not respond?

### ISSUE THREAD

**Issue by hf97542** [yuliskov/SmartYouTubeTV#179]
After upgrading the new version, why does the remote control not respond?

**Comment by yuliskov** [comment]
Can't fix without additional info. Which version you're using now? From which version you did upgrade?

**Comment by yuliskov** [comment]
Hey, I give you archive of all releases. Try to find the latest one that will work on your device.
https://github.com/yuliskov/SmartYouTubeTV/releases

**Comment by yuliskov** [comment]
Closed since user didn't provide any additional infos
