### ISSUE TITLE
no video after logging into user

### ISSUE THREAD

**Issue by matanos5** [yuliskov/SmartYouTubeTV#181]
Using Mi Box 3 on Android 8.0.0, latest update.
Using build 6.14.55, although tried many builds.

Happens when using 4k main and alternative.
After installing APK (without logging into YouTube user), videos work properly.
Then, after logging in, videos have no sounds and there's a black screen.

Issue occurs after relaunching app.

If I'm using the 1080 launcher, everything works well - but video is up to 720p only.

Thank you for this great project.

**Comment by yuliskov** [comment]
@matanos5 hi, thanks for letting me know about this. Please, try the latest test release.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.14.73/SmartYouTubeTV_Orig_v6.14.73_r.apk

**Comment by matanos5** [comment]
@yuliskov Thank you so much for the fast reply and fix.
Can confirm - this fixed the issue.

Many thanks and lots of appreciation for this great app you're maintaining!
