### ISSUE TITLE
Dont know if bug or missing feature?, app will not open when other apps try's to use YOUTUBE

### ISSUE THREAD

**Issue by aranapatona** [yuliskov/SmartYouTubeTV#182]
Dont know if this bug or missing feature, app will not open when other apps try's to use YOUTUBE,
Specifically TEATV when trying to open a trailer, shows a message stating that it cannot find YOUTUBE (and of course, as it is not installed), is it possible to set itself to open any video sent to the original youtube app when called from other apps and not opened directly?

**Comment by yuliskov** [comment]
@aranapatona already did. I wonder, why it's not working in your case.
![screen](https://user-images.githubusercontent.com/5897464/48234868-129a5700-e3c4-11e8-8906-c2a594bed8fb.png)

**Comment by yuliskov** [comment]
should be fixed in the latest release:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.14.86/SmartYouTubeTV_Orig_v6.14.86_r.apk
