### ISSUE TITLE
5.1 audio support

### ISSUE THREAD

**Issue by amitprabhu** [yuliskov/SmartYouTubeTV#183]
There is no audio from the rear speakers with 5.1 audio setup.

**Comment by yuliskov** [comment]
Won't be fixed. YouTube supports stereo only.

**Comment by manuke42** [comment]
When I play this video on Chromecast, i get 5.1 audio support:
https://www.youtube.com/watch?v=_ttYSpt8oiw

Also the video codecs reveal there is an audio stream available on youtube in this video supporting 5.1:

140 = 128Kbps LC-AAC Stereo Audio @ 44.1 kHz
171 = 128Kbps Vorbis Stereo Audio @ 44.1 kHz
249 = ~50Kbps Opus Stereo Audio @ 48.0 kHz
250 = ~70Kbps Opus Stereo Audio @ 48.0 kHz
251 = 160Kbps Opus Stereo Audio @ 48.0 kHz
**256 = 192Kbps HE-AAC 5.1 @ 48.0 kHz
258 = 384Kbps LC-AAC 5.1 @ 48.0 kHz**

when i download the video with the code 258 i even get 5.1 on my PC.
wouldn't it be possible to support this audio like on chromecast somehow?

You may have to stream the audio file simultaneously. One can find all the links to the video and audio files available here:
https://www.h3xed.com/blogmedia/youtube-info.php

From my example video i can use the last 258 audio file to get 5.1 working. I think it would be possible, but not straightforward
