### ISSUE TITLE
Screen zoom out

### ISSUE THREAD

**Issue by fikobaf** [yuliskov/SmartYouTubeTV#184]
Is there a screen reduction setting for large screen television. I want to reduce the size of the video when my child watches. For example: like zoom out. or do not want to watch it in full screen.thanks...

**Comment by yuliskov** [comment]
@fikobaf hi, I need an example. Do you know any apps with wanted behavior?

**Comment by yuliskov** [comment]
@fikobaf oh, I understand. You want to browse YouTube while video is playing, right? For the such case a suggestions is designed.

**Comment by yuliskov** [comment]
OK. Closed. Since, I've no plans to rewrite existing logic.

**Comment by fikobaf** [comment]
In the Kodi application, you can zoom in and out with the settings / video settings / zoom amount on the video playback screen. Does the smart youtube app have this feature? does this feature have an insertion plan? thanks.

**Comment by fikobaf** [comment]
There is no problem in your application. I have my big screen TV. I don't want to watch some videos full screen. I want to watch non-hd videos by zooming out. I will be very happy if such an option is added to the general settings.Thanks...

**Comment by yuliskov** [comment]
OK. I think I need to create a poll or something like that. Where I could peek the most popular ideas and implement them.
