### ISSUE TITLE
Flashes white screen at Initial Launch

### ISSUE THREAD

**Issue by bum2kev** [yuliskov/SmartYouTubeTV#185]
When the application is first launched on the Nvidia shield a white screen flashes twice very quickly. See attached video http://www.mediafire.com/file/kage07u0hs2mkfv/20181116_111613_1.mp4/file .  (this was mentioned in the comments on the main page)

**Comment by yuliskov** [comment]
@bum2kev done:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.14.95/SmartYouTubeTV_Orig_v6.14.95_r.apk

P.S. you've mentioned resolution bug. If one still present on this build, please fill up the issue.
