### ISSUE TITLE
cross walk project service not found

### ISSUE THREAD

**Issue by chancemimi** [yuliskov/SmartYouTubeTV#187]
it says sth needed to be gotten.But when trying ,just failed.

**Comment by yuliskov** [comment]
@chancemimi do you mind to give me CPU-Z screens from your device? The error screen would also be good. About VPN I'm not sure. I've not tested deeply this particular situation.

**Comment by lzybilian** [comment]
Have you solved this problem, please?

**Comment by lzybilian** [comment]
I'm running into this problem right now.
