### ISSUE TITLE
youtube video lags then says loading

### ISSUE THREAD

**Issue by zakir1988** [yuliskov/SmartYouTubeTV#188]
Hi

When I watch a youtube video on Firestick not all the time sometimes I experience this the video lags then it stops playing and says loading  I can't exit out of the app or go to home screen I have to switch the firestick off to restart the device can you fix the problem please i am finding with every new update the app is getting faster and smoother to run.

**Comment by yuliskov** [comment]
@zakir1988 I need something to work with. How long you're using my app? What launcher you prefer to select and why? Attach here screens from the CPU-Z running on your device. If I have more ideas then I'll let you know.

**Comment by yuliskov** [comment]
Merge with #74
