### ISSUE TITLE
Can't properly exit app

### ISSUE THREAD

**Issue by ds22x** [yuliskov/SmartYouTubeTV#189]
After the latest update, I can't properly exit the app due to the new exit menu crashing after selecting the exit option (at least on my Fire tv stick, using the main 4K launcher).

**Comment by spec1re** [comment]
Same here, can't exit app. (Nvidia SHIELD TV 2017)

**Comment by VCESAITIS** [comment]
Same here, can't exit app. (Nvidia SHIELD TV 2017 Oreo 8.0)

**Comment by kriztology** [comment]
Same here. Fire TV Stick 4K and Fire TV Box gen1

**Comment by T-Town2468** [comment]
experiencing same issue on fireOS (gen 1 box, gen 2 stick)

**Comment by crcerror** [comment]
Same here. Fire TV Stick Gen 1.
It has nothing to do with current release. 
Amazon seems to change exit routine.
Exit switch does not respond

**Comment by yuliskov** [comment]
what about latest release:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/stable/smartyoutubetv_latest.apk

**Comment by kriztology** [comment]
@crcerror but nvidia shield has the same issue...

**Comment by haojiezhu** [comment]
@yuliskov - Link is down now. I downloaded 6.15.05 last night from this link and the problem with exit is fixed (Shield TV and Mi Box 3).

**Comment by ds22x** [comment]
@yuliskov Just updated and I can confirm it's fixed.

**Comment by Benman2785** [comment]
seems fixed in latest.apk
