### ISSUE TITLE
The upgrade problem

### ISSUE THREAD

**Issue by xiaoxihu2017** [yuliskov/SmartYouTubeTV#19]
1、The quality of the painting is selected for memory.
![mitvscreenshot_613_1509242595511-com firsthash sm](https://user-images.githubusercontent.com/31083939/32140156-393b8a42-bc91-11e7-951f-6e620f4d578e.jpg)

2、Online upgrade , upgrade failure.
![mitvscreenshot_613_1509242627277-com firsthash sm](https://user-images.githubusercontent.com/31083939/32140157-3db05f44-bc91-11e7-9b7c-f256bf8fd09e.jpg)

**Comment by yuliskov** [comment]
It is would be good to know an Android version.

**Comment by yuliskov** [comment]
For auto-update feature you need to have external storage attached to your tvbox. This may be an sdcard. Note, that most of devices already have built-in storage. But, I'm afraid that is not your case.

**Comment by yuliskov** [comment]
If you use vpn or something like this, then ensure that you've enabled access to Github.
