### ISSUE TITLE
[Nvidia Shield TV] Remote not working in "4K Alt" mode

### ISSUE THREAD

**Issue by haojiezhu** [yuliskov/SmartYouTubeTV#191]
Hi, this problem has really baffled me for a while. It only happens in "4K Alt" mode on my Shield TV, but not in the other 3 modes or on a Mi Box 3. Most of the time if I choose "4K Alt" mode, SmartYouTubeTV won't respond to my Shield remote at all. But it still accepts mouse/keyboard input. Only after I start playing a video with mouse-click, remote then starts to work. If I quit and restart SmartYouTubeTV, this problem comes back. Here is a short video I took to demonstrate the problem:

https://youtu.be/MlHv6zUIB70

The main reason I prefer using "4K Alt" over "4K Main" is that Autoplay function constantly stops working in "4K Main" but works really well in "4K Alt" mode.

**Comment by yuliskov** [comment]
@haojiezhu hi, thanks for letting me know about this bug. I'll try to fix it ASAP.

**Comment by haojiezhu** [comment]
@yuliskov Thanks a lot. I can confirm this problem is fixed now.
