### ISSUE TITLE
Select sounds and back button on the right buttom corner of the screen issues on Smart Youtube TV app

### ISSUE THREAD

**Issue by TheLegendaryKillerXD** [yuliskov/SmartYouTubeTV#193]
I'm having a lot of problems with them on Amazon Fire TV stick 2nd generation. It keeps on turning itself off and back on when it always does. And the select sound while scrolling that I didn't hear is that it didn't stay automatically on by itself. Can you please give it a try and have a good fix, so that they can be done in no time?

**Comment by TheLegendaryKillerXD** [comment]
![0_screenshot_2018-11-23-17-27-44](https://user-images.githubusercontent.com/45300240/48962443-abdd7780-ef45-11e8-9076-2b23d7d06aaf.png)

**Comment by yuliskov** [comment]
@TheLegendaryKillerXD could I ask you to record the video with the problem? The screenshot you've posted isn't quite enough.

**Comment by yuliskov** [comment]
Redirect #194
