### ISSUE TITLE
[Nvidia Shield] exit button not working

### ISSUE THREAD

**Issue by smarshnz** [yuliskov/SmartYouTubeTV#196]
When attempting to exit the app I can choose exit, however it does not actually exit the app.

**Comment by johny2000uwb** [comment]
FireTv 4k also.

**Comment by yuliskov** [comment]
Fixed in the latest release:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/stable/smartyoutubetv_latest.apk

**Comment by johny2000uwb** [comment]
FireTv 4k: Exit works after update

**Comment by chainone** [comment]
had the same issue, works after doing the update.
