### ISSUE TITLE
[FireTv 4k] Loading is very oft schown

### ISSUE THREAD

**Issue by johny2000uwb** [yuliskov/SmartYouTubeTV#197]
I have big problem with video lags. It is visible almost by every video. I used the 4k, because of the 60 fps in 1080. Connection lan adapter 100 mbits.

**Comment by johny2000uwb** [comment]
![img_20181124_225854081](https://user-images.githubusercontent.com/17253582/48973313-fb529f00-f03c-11e8-97fa-54073cd8ad75.jpg)

**Comment by johny2000uwb** [comment]
Connected via lan 100 mbits

**Comment by yuliskov** [comment]
@johny2000uwb does overall playback is paused while you see this message?

**Comment by johny2000uwb** [comment]
Yes. Oft stays in this state for longer time (minutes)

**Comment by johny2000uwb** [comment]
But some videos are without problems and some videos make this problem oft.

**Comment by yuliskov** [comment]
@johny2000uwb could you confirm or not that bug exists on 1080 launchers? Also, interesting to know, how many videos have this problem?

**Comment by johny2000uwb** [comment]
I have not seen this bug on 1080 launchers. Only on 4k Launcher. I do not have 4k TV, so I launch video in 1080. 
I can only estimate .. cca 60 procent of videos what I have seen.

**Comment by yuliskov** [comment]
@johny2000uwb thanks for the quick reply. It's seems like codec issue.

**Comment by yuliskov** [comment]
@johny2000uwb what do you say about this build?
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.36/SYTV_Orig_v6.15.36_r.apk

**Comment by johny2000uwb** [comment]
Seems to be fixed. I will test it on weekend more.

pá 7. 12. 2018 13:14 odesílatel Yuriy Lyskov <notifications@github.com>
napsal:

**Comment by johny2000uwb** [comment]
I have this loading not more.
