### ISSUE TITLE
some menu unreadable

### ISSUE THREAD

**Issue by gd82324976** [yuliskov/SmartYouTubeTV#198]
some menu unreadable, see picture below:
![20181125125714](https://user-images.githubusercontent.com/45324995/48975701-af8e0d00-f0b1-11e8-8b44-b1eacc2911e5.jpg)

**Comment by yuliskov** [comment]
@gd82324976 pls do the test:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.12/SmartYouTubeTV_Orig_v6.15.12_r.apk

**Comment by yuliskov** [comment]
should be fixed in the latest release
