### ISSUE TITLE
The Official 2017 User UI Interface App for Animations with Frame Rate is not on 60fps

### ISSUE THREAD

**Issue by TheLegendaryKillerXD** [yuliskov/SmartYouTubeTV#199]
I'm just thinking how it wasn't that smooth at all and for the moving image that has a perfect image picture quality on the TV screen and I was using the one with resolution of "1080p Main" and it has to be fixed on Amazon Fire TV Stick 2nd Generation as well.

**Comment by yuliskov** [comment]
@TheLegendaryKillerXD for smoother experience use 4K modes
