### ISSUE TITLE
4K support?

### ISSUE THREAD

**Issue by liliass** [yuliskov/SmartYouTubeTV#2]
Hi, May I know it is 4K video support on 4K TV ?

**Comment by yuliskov** [comment]
This feature can't be implemented at this moment. Sorry.

**Comment by yuliskov** [comment]
Hi. Prepared special version with 4k support. Check it out.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.32/SmartYouTubeTV_Exoplayer_v6.8.32_r.apk

**Comment by yuliskov** [comment]
4K support added in latest releases.
