### ISSUE TITLE
Video and Audio isn't consistent

### ISSUE THREAD

**Issue by jj0524** [yuliskov/SmartYouTubeTV#20]
Video and audio is not consistent for some videos. My TV box is Xiaomi mibox3 S905 Android 5.1.1.

**Comment by yuliskov** [comment]
Hello. Could you update app to last version? Last version contains four launchers: 720, 1080, 4K, 4K alt. They differ by performance on specific devices. Test them all, and then elaborate this question.

**Comment by jj0524** [comment]
I have tested the latest version 6.8.61 720p/1080p and the issue is still existed  especially in Live videos. The problem isn't found on official Youtube for android TV 2.01.04.  Is this CPU dependence? The issue also isn't found on Xiaomi TV box Mibox3 Pro MDZ-18-AA in the latest smartyoutubetv.

**Comment by yuliskov** [comment]
I don't believe that it's your hw specs. I would like to investigate problem in details. Could you install CPU-Z?  Post here screenshot of the second tab, named Device.

**Comment by jj0524** [comment]
Here you are. Thanks.
![mitvscreenshot_209_1509498029594-com cpuid cpu_z-com cpuid cpu_z mainactivity-7720b4e2570a9f5e7d5797d01bcaecbe](https://user-images.githubusercontent.com/32182562/32255528-9e6838b2-bee3-11e7-90dc-629b7720057c.jpg)

**Comment by yuliskov** [comment]
testing release:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.62/SmartYouTubeTV_Orig_v6.8.62_r.apk

**Comment by jj0524** [comment]
For 6.8.62 720p/1080p, it's black screen and no audio while playing any videos on Mibox3 MDZ-16-AA but MDZ-18-AA.

**Comment by yuliskov** [comment]
Try new releases. Especially 4K ones.
