### ISSUE TITLE
Fix "Next Video" 

### ISSUE THREAD

**Issue by Molkio** [yuliskov/SmartYouTubeTV#200]
It would be possible to delete that image when we use the "NEXT" function
A black screen would be better
That happens with the Xiaomi Mibox, with other devices like the Fire TV Stick does not happen

https://youtu.be/oK_6eMUgjQc
https://i.imgur.com/gDvC0FA

**Comment by Molkio** [comment]
Works! Thanks! 
:)


https://youtu.be/fFD4z0M1dho

**Comment by yuliskov** [comment]
@Molkio you're welcome!
