### ISSUE TITLE
Force update of the app directly from the menu ?

### ISSUE THREAD

**Issue by mattiashking** [yuliskov/SmartYouTubeTV#201]
Hi Yuriy, 

many thanks for all your effort with this app. 
Could you consider to add option just to manually force update of the existing apk ?
Many times I or someone from my family simply missclick the offered update and thus I am forced to install it via USB manually.

Just FYI: For the last tries of the existing automatic update it always ended with "analysis of the package failed" or something like that, and I was not able to update it then.

**Comment by yuliskov** [comment]
Update significantly improved in the newer releases.
Now update prompt should appears every time you boot into the app.
Further improvements aren't possible.
