### ISSUE TITLE
Autoupdate issues "There was a problem parsing the package"

### ISSUE THREAD

**Issue by WolfganP** [yuliskov/SmartYouTubeTV#202]
Just wanted to avoid mixing issues, so I started a new one for easier tracking and feedback if needed.

From https://github.com/yuliskov/SmartYouTubeTV/issues/74#issuecomment-441341555

> @greenman86 autoupdate will be fixed soon. If you don't want to wait, here the direct link: https://github.com/yuliskov/SmartYouTubeTV/releases/download/stable/smartyoutubetv_latest.apk

As @greenman86 said, I'm also suffering from "Unable to parse this package" anytime i try to install the latest version (my box is a generic android 4.4 kitkat one)

@yuliskov if there are any logs you need from me to help troubleshooting, just ask. Thx!

**Comment by greenman86** [comment]
Yeh im able to auto update again. but there is a video lag for the first 10
seconds of any  video being watched

**Comment by yuliskov** [comment]
@WolfganP do you have this bug on the latest releases?

**Comment by yuliskov** [comment]
Everyone, who experienced this issue, please update app manually.
