### ISSUE TITLE
Bad image on PHILIPS 55PUS7303

### ISSUE THREAD

**Issue by AleksandrDneprCity** [yuliskov/SmartYouTubeTV#203]
Hello!
I install this application on TV PHILIPS 55 PUS 7303 (Android 7. 0) and have problem with image on video - very small contrast and on the image are bright colored torches.

The camera of the smartphone cannot convey a poor contrast, because automatic adjustments are functioning, but color torches are visible.

![20181203_004020](https://user-images.githubusercontent.com/45544502/49346007-f0c78380-f694-11e8-943f-2d21172a19ea.jpg)
![20181203_004022](https://user-images.githubusercontent.com/45544502/49346008-f0c78380-f694-11e8-8318-443c7ad425f6.jpg)
![20181203_004126](https://user-images.githubusercontent.com/45544502/49346009-f0c78380-f694-11e8-966c-9ea16e1df310.jpg)
![20181203_004206](https://user-images.githubusercontent.com/45544502/49346010-f0c78380-f694-11e8-946f-75a96cdf2228.jpg)
![20181203_004232](https://user-images.githubusercontent.com/45544502/49346011-f0c78380-f694-11e8-9611-910f73f3e06d.jpg)

**Comment by yuliskov** [comment]
@AleksandrDneprCity hi. I believe that problem with codecs on your device. Please, test provided sample on the external player with hw decoding enabled.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.26/test.mp4

**Comment by AleksandrDneprCity** [comment]
Tested on two players: On the built-in and on the VLC, nowhere did I find the options to turn on and off the hardware decoding. On both players, this video plays perfectly.
If you need to test on some other player, tell me which one, I will install and test.

Протестировал на двух плеерах: На встроенном и на VLC, нигде опций для включения и отключения аппаратного декодирования я не нашёл. На обоих плеерах видео идёт отлично.
Если нужно протестировать на каком-то другом плеере, скажите на каком, я установлю и протестирую.
![20181203_111912](https://user-images.githubusercontent.com/45544502/49366521-2b133e00-f6f2-11e8-9f4a-99f3cf73b6e2.jpg)
![20181203_114251](https://user-images.githubusercontent.com/45544502/49366522-2babd480-f6f2-11e8-960f-0e5634d9d24a.jpg)

**Comment by AleksandrDneprCity** [comment]
I have news on this issue:
1) No matter what quality of video was chosen from the very beginning, we immediately have a distorted image. But if you select any other quality in the Quality / Video menu, the image immediately becomes excellent. If you go back to the previous video quality, the picture stay excellent.
2) If after these manipulations restart the Smart YouTube TV application, the picture is immediately excellent.
3) If the TV is switch to the HDMI input, and then restart Smart YouTube TV, the problem repeats, we again have bad image.

As i understand it, the whole problem is in the initialization of codecs.

But found the second problem. After restarting the application, even if the picture remains without distortion, its quality is lower than selected in the menu "Quality / Video". All the same, you need to manually switch the quality there / back so that it becomes correspond to the selected one.

У меня новости по этой проблеме:
1) Не зависимо от того, какое качество видео было выбрано с самого начала, сразу имеем искажённое изображение. Но если в меню "Качество / Видео" выбрать любое другое качество, то изображение сразу становится отличным. Если вернуться назад на прежнее качество видео, картинка остаётся без искажений.
2) Если после этих манипуляций перезапустить приложение Smart YouTube TV, то картинка сразу отличная.
3) Если ТВ переключить на HDMI вход, а потом снова запустить Smart YouTube TV, то проблема повторяется, снова имеем искажения изображения.

Как я понял, вся проблема в начальной инициализации, возможно кодеков.

Но есть и вторая проблема. После перезапуска приложения, даже если картинка осталась без искажений, её качество ниже чем выбрано в меню "Качтество / Видео". Всё-равно нужно вручную переключать качество туда/обратно, чтобы оно стало соответствовать выбранному.

**Comment by yuliskov** [comment]
@AleksandrDneprCity воу, спасибо. Полезная инфа. Возможно, совместными усилиями получится что-то сделать. Какая у вас версия приложения? Проблема с запоминанием качества была пофикшена пару версий назад (неужели не до конца!?). И да, дублировать на англ не обязательно.

**Comment by yuliskov** [comment]
@AleksandrDneprCity по второй проблеме, где выбранное качество не сохраняется. Помогите плз проблему повторить. Это происходит на всех роликах или каких-то определенных?

**Comment by AleksandrDneprCity** [comment]
Только что проверил около 10 роликов, большинство были в качестве 1920х1080 50 fps, 1920х1080 60 fps, 1920x1080 30 fps, и один 1280х720 25fps. Это происходит на всех проверенных роликах. Т.к. это видно и на 720p, то могу сделать вывод, что все ролики стартуют в разрешении ориентировочно 360p или 480p. И причём, даже если не перезапускать приложение, а только сам ролик.
1) Запустил ролик, идёт в невысоком разрешении. Проверяю в меню Качество/Видео, стоит максимальное качество, например 1920x1080 50 fps vp9. Переключаю на соседнее качество, картинка сразу намного чётче, возвращаю прежнее качество, картинка теперь чётка.
2) Выхожу из этого видео и тут же снова запускаю, видео снова идёт в невысоком разрешении, полностью повторяя пункт 1.

**Comment by yuliskov** [comment]
@AleksandrDneprCity симптом выше не похож на сбой в логике работы программы. Иначе баг проявлялся не только на качестве картинки, а его было бы видно в статистике и настройках, скажем. По всему получается, что вторая проблема тоже связана с кодеками. И воспроизвести баг на своих девайсах я наверно не смогу. Ну что же. Придется действовать наугад. Скину сюда ссылку, когда будет что показать. Спасибо за помощь.

**Comment by AleksandrDneprCity** [comment]
А не проще будет сделать так, чтобы при открытии видео, перед его стартом дополнительно производились действия выбора качества видео, как будто это пользователь решил поменять качество ? Ведь при запуске имеется корректная информация, какое качество должно быть выбрано, (это видно в меню Качество / Видео), остаётся только вызвать функцию, которая исполняет выбор качества и после этого стартовать видео.
Это решит сразу обе проблемы и избавит Вас от зависимости от модели ТВ.

**Comment by yuliskov** [comment]
@AleksandrDneprCity сделал, пробуйте
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.27/SmartYouTubeTV_Orig_v6.15.27_r.apk

**Comment by AleksandrDneprCity** [comment]
К сожалению, не помогло. Всё без изменений.

**Comment by yuliskov** [comment]
еще версия на проверку
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.28/SmartYouTubeTV_Orig_v6.15.28_r.apk

**Comment by AleksandrDneprCity** [comment]
Пока что не помогло.

**Comment by yuliskov** [comment]
ок. вот еще
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.29/SmartYouTubeTV_Orig_v6.15.29_r.apk

**Comment by AleksandrDneprCity** [comment]
Пока что без изменений по 1-й и 2-й проблеме.

**Comment by AleksandrDneprCity** [comment]
Пока что без изменений по 1-й и 2-й проблеме.

**Comment by yuliskov** [comment]
@AleksandrDneprCity версия на проверку
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.35/SYTV_Orig_v6.15.35_r.apk

**Comment by AleksandrDneprCity** [comment]
Спасибо! В этот раз запускается сразу в отличном качестве без каких либо дефектов на изображении.

Причём, если запускать сразу после HDMI входа:
Видео с МС на вулкане в Исландии, сначала появляется надпись "Загрузка" на сером экране, затем "Загрузка" появляется второй раз на тёмном экране, кратковременно проскакивает искажённое изображение, тут же появляется "Загрузка" третий раз, после которой видео снова начинает идти уже  в отличном и в максимальном качестве.

Если выйти из видео и запустить снова это же или другое видео:
На любом видео сначала появляется надпись "Загрузка" на сером экране, затем появляется второй раз "Загрузка" на тёмном экране  и начинает идти видео без искажений, но в низком разрешении, идёт где-то 2 секунды, затем третий раз появляется "Загрузка" и после этого видео идёт уже в максимальном разрешении.

**Comment by yuliskov** [comment]
@AleksandrDneprCity сейчас, по-идее, видео должно запускать без видимых признаков перезапуска, но с задержкой. Проверьте. Интересно, проблема вернется или нет.   
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.36/SYTV_Orig_v6.15.36_r.apk

**Comment by AleksandrDneprCity** [comment]
Проблемы больше нет и в 36-й версии. Запуск стал красивее - хотя надпись "Загрузка" появляется трижды, но картинка с искажениями или с низким разрешением больше не проскакивает при запуске.
Бывает, только звук проскакивает на доли секунды, где-то во время первой надписи "Загрузка" или после неё, но на тёмном экране, потом после третьей надписи "Загрузка" появляется старт видео с отличным изображением.

**Comment by AleksandrDneprCity** [comment]
Проблем с видео нет никаких. По времени старта, трудно сказать, стало бы быстрее запускаться, но вроде как быстрее. Надпись "Загрузка" всё так же 3 раза появляется, но это мелочи. Главное, что любое видео запускается сразу в максимальном качестве.
Огромное спасибо за проделанный труд.

**Comment by yuliskov** [comment]
@AleksandrDneprCity вам спасибо. Оставлю пока так. Если будут какие-то изменения - дам вам знать.    Боюсь, чтобы изменения не сказались отрицательно на остальных пользователях.

**Comment by yuliskov** [comment]
@AleksandrDneprCity Привет. Нужна ваша помощь. Хотелось бы узнать не вернулась ли проблема на этой сборке.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.17/SYTV_Orig_v6.16.17_r.apk

**Comment by AleksandrDneprCity** [comment]
Добрый день.
Проверил, всё отлично, никаких проблем не обнаружил.

**Comment by yuliskov** [comment]
Огромное спасибо!
