### ISSUE TITLE
No sound 

### ISSUE THREAD

**Issue by jj0524** [yuliskov/SmartYouTubeTV#21]
No sound effect while enable sound from setting.

**Comment by yuliskov** [comment]
Need more info

**Comment by jj0524** [comment]
Please see the following picture.
![mitvscreenshot_210_1509493226058-com firsthash smartyoutubetv2-com liskovsoft smartyoutubetv flavors xwalk smartyoutubetvactivity-3a6b49e6ec2a2d8c04562ba9f07aaa91](https://user-images.githubusercontent.com/32182562/32254390-69909ca4-bedb-11e7-9777-2263efe52354.jpg)

**Comment by yuliskov** [comment]
ok. got it.

**Comment by yuliskov** [comment]
Fixes in latest versions.
