### ISSUE TITLE
Voice search

### ISSUE THREAD

**Issue by khanhtungmtp** [yuliskov/SmartYouTubeTV#214]
I think when the voice search finishes, focus on the video and not the keyboard

**Comment by yuliskov** [comment]
thanks for the mention that

**Comment by khanhtungmtp** [comment]
Hope you will fix it in the upcoming update, hihi

**Comment by yuliskov** [comment]
pls test:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.71/SYTV_Orig_v6.15.71_r.apk

**Comment by khanhtungmtp** [comment]
Video test https://drive.google.com/file/d/1jnuywZgxli39goIhURSj9elIwhZlY_Zl/view?usp=drivesdk

**Comment by yuliskov** [comment]
bugfix update:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.75/SYTV_Orig_v6.15.75_r.apk

**Comment by khanhtungmtp** [comment]
I booted it up, it was not so fast, but the mouse outside I didn't use it
so I didn't test it, I just said voice hihi

Vào 9:21 Th 4, 09 thg 1, 2019 Yuriy Lyskov <notifications@github.com đã
viết:
