### ISSUE TITLE
Autoplay not working 

### ISSUE THREAD

**Issue by zakir1988** [yuliskov/SmartYouTubeTV#215]
On Amazon Firestick 2nd generation don't know if People are having the same problems on other Devices as me.

What I'm facing is when the video is finished played  it should automatically play related videos but it does not play related videos it what it does is when The video is finished The screen goes blank then after few seconds it repeats The same video we played after The second time or so of watching The same video The autoplay feature works.

Needs a fix. its good that by having a firestick I can tell you the Problem us Firestick users are having the problems im facing should be the same for the 3rd and 4th generation Firestick users.

**Comment by stevensmedia** [comment]
I have the opposite problem. I have autoplay turned OFF but it autoplays anyway.

**Comment by yuliskov** [comment]
@stevensmedia @zakir1988 hi, I need to know the app version and the launcher's name that you're using

**Comment by zakir1988** [comment]
I was using 4K alt Launcher with default settings one problem I found is that after an update the app with may have a glicth for example autoplay was not working for me I have resolved the issue by chaning the launcher and going to back to 4K alt what I found is that when it autoplay screen goes blank then loads the next recommend video straight away without the the video title preview what video it will play next does not work on 4K alt will try on 4K main see if the problem is the same

**Comment by zakir1988** [comment]
Same problem im facing on 4k main

**Comment by stevensmedia** [comment]
All of the last few versions, 4k.

**Comment by yuliskov** [comment]
should be fixed here
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.17/SYTV_Orig_v6.16.17_r.apk
