### ISSUE TITLE
Taking too long to start?

### ISSUE THREAD

**Issue by trmdi** [yuliskov/SmartYouTubeTV#217]
I don't know why every time I open it, it takes too long, about ~1min, before it could show the main screen.

**Comment by yuliskov** [comment]
@trmdi how long are you using this app? I'm eager to know was there an regression or not.

**Comment by yuliskov** [comment]
In case you want to compare, prev releases:
https://github.com/yuliskov/SmartYouTubeTV/releases

**Comment by trmdi** [comment]
I've been using this app for a long time, but that was a version with the blue icon. Yesterday I tried updating it to the latest stable/beta version and notice this.
On the old version (which has a blue icon) it shows the main screen very quickly.

**Comment by WolfganP** [comment]
I noticed the same on very long program start (in previous releases it was a gray screen with a spinner, now it shows the YT logo with an spinner).
It seems as if the program tries to get something and timeouts after a long time. If there's any log needed, just let me know.

**Comment by yuliskov** [comment]
Start-up time has been improved.
Now caching is done on first launch only.
All succeeding launches should go much faster.

https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.73/SYTV_Orig_v6.15.73_r.apk

**Comment by trmdi** [comment]
~15s now, much faster.

Just curious, what does it do on startup in those 15s? Can it be improved a bit more? The Official Youtube app loads instantly.

**Comment by yuliskov** [comment]
@trmdi it did multiple web queries at boot. It's a main cause of the problem. Official YouTube also does such things but while app in the background. If I'd apply this approach my app will consume some amount RAM and CPU even when you're not using it. As a result this would cause more sluggish overall performance of your tv box.

**Comment by trmdi** [comment]
Excuse me, does SmartYoutubeTv automatically update? Or I have to update it manually.
I see it display "Check for update" on starting it, what does that update?

**Comment by yuliskov** [comment]
@trmdi it does what it says: checks for updates and if there is one you'll see the update dialog.

**Comment by onolox** [comment]
> 
> 
> @trmdi it did multiple web queries at boot. It's a main cause of the problem. Official YouTube also does such things but while app in the background. If I'd apply this approach my app will consume some amount RAM and CPU even when you're not using it. As a result this would cause more sluggish overall performance of your tv box.

I see no problem in this regard, I prefer a "preloading" than wait looking to an empty TV :-)
In more modern TV boxes this will not be a problem.
