### ISSUE TITLE
4K can't work on sony KD-49X8300c

### ISSUE THREAD

**Issue by vanyanyan** [yuliskov/SmartYouTubeTV#219]
Pls help below
Smart youtubetv still can't run 4k on my sony 8300 4k tv, version no 6.15.64 
![_20190110213138](https://user-images.githubusercontent.com/31093488/50971540-36426080-151f-11e9-945f-6a7e1d88bc0a.jpg)
![_20190110213154](https://user-images.githubusercontent.com/31093488/50971545-38a4ba80-151f-11e9-99ed-8c3a3bbe28b5.jpg)

**Comment by yuliskov** [comment]
Display resolution doesn't matter. It's internal measurements of my app. I've deleted display related info as it cause such misunderstanding.

**Comment by vanyanyan** [comment]
ok,thanks for your reply
