### ISSUE TITLE
black screen loading after shield update to 7.2.2

### ISSUE THREAD

**Issue by SatWiz** [yuliskov/SmartYouTubeTV#220]
4K content doesn't play anymore after shield update to 7.2.2. Screen stays black displys loading only without any process.
Startup in 1080 mode everything plays no problem.

**Comment by ryadre** [comment]
Mine won't even load after the update. Just sits on the YouTube screen with the spinning wheel

**Comment by yuliskov** [comment]
Is something changed after last update?

**Comment by SatWiz** [comment]
Really weird, tried everything. Clear data/cache, reinstalled don't get it working anymore for 4K launchers. Sometime it has sound for 1 sec and than continue flashing loading. One time I get display invalid video format when do next and back again. But most time only loading flashing on black screen.

**Comment by yuliskov** [comment]
Hi, guys. What about the latest release?
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.114/SYTV_Orig_v6.15.114_r.apk

**Comment by yuliskov** [comment]
@SatWiz in the latest release I've added logging capability. You could find one in the main Launcher, right inside Tweaks menu.

**Comment by SatWiz** [comment]
@yuliskov,  Thanks for your support. Unfortunately the update did not change anything. Either on my SHIELD or SONY 4K Android TV. Black screen only. I have collect the logs for you on my SHIELD with the 2 different 4K starters. Hope you can fix it. Thanks. 
[logs.zip](https://github.com/yuliskov/SmartYouTubeTV/files/2798860/logs.zip)

**Comment by yuliskov** [comment]
@SatWiz seems nothing helpful. I'll prepare new release with extended logging.

**Comment by yuliskov** [comment]
Hello. Special build for the latest android versions. Pls, do the test.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.13/SYTV_Orig_v6.16.13_r.apk

**Comment by yuliskov** [comment]
@SatWiz 
Hello. Special build for the latest android versions. Pls, do the test.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.13/SYTV_Orig_v6.16.13_r.apk

**Comment by SatWiz** [comment]
@yuliskov , here are the logs again. lite-main is working, the other 4K launchers still black loading screen. Btw sign-in page is hanging in all launchers. Need to force stop app to enter again.
[logs.zip](https://github.com/yuliskov/SmartYouTubeTV/files/2813040/logs.zip)

**Comment by yuliskov** [comment]
@SatWiz thx for the help. Check this fix.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.18/SYTV_Orig_v6.16.18_r.apk

**Comment by SatWiz** [comment]
[logs.zip](https://github.com/yuliskov/SmartYouTubeTV/files/2821593/logs.zip)
@yuliskov , here are the logs. We keep on going ;).

**Comment by yuliskov** [comment]
@SatWiz did you spotted any changes on the latest build?

**Comment by SatWiz** [comment]
@yuliskov nothing has changed for the SHIELD, I will try later on my TV and let you know.

**Comment by yuliskov** [comment]
@SatWiz ok, maybe logs from this release could help 
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.26/SYTV_Orig_v6.16.26_r.apk

**Comment by SatWiz** [comment]
@yuliskov , I am really sorry to bother you all the time. I found it when I dig in the logs and try to open the https://r?---sn-* googlevideo.com urls. It appears some were blocked in my pi-hole config. After removing them all 4K videos are accessible again.

**Comment by yuliskov** [comment]
@SatWiz so problem was on your side? It's great news.

**Comment by SatWiz** [comment]
Yes, it was really weird both TV and SHIELD were not working. But thanks your log function it could helped me further to find out. Really appreciate your help!!
