### ISSUE TITLE
Small UI Bug with "Quality -> Preset" in 4K Modes

### ISSUE THREAD

**Issue by haojiezhu** [yuliskov/SmartYouTubeTV#223]
This is just a very small UI bug. In either 4K mode, "Quality -> Preset" used to show the codec and resolution mode selected previously. In the latest release and test version, all modes show up as unselected in "Quality -> Preset". If I select one mode, close the selection dialog, go back to "Quality -> Preset" again, all modes go back to unselected again.

**Comment by yuliskov** [comment]
Fixed in the latest relase
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.15.114/SYTV_Orig_v6.15.114_r.apk
