### ISSUE TITLE
Binary release builds all point to the same commit

### ISSUE THREAD

**Issue by hackel** [yuliskov/SmartYouTubeTV#224]
It seems that every release since 16.15.57 is pointing to a02dd0d.  What is going on?  Each version has its own tag that points to that same commit from 23 days ago.  Have the last 47 releases been identical?  This is really dodgy and it makes me wonder what you are putting into your binary releases that is not actually in the repo.  Clarification requested.

**Comment by yuliskov** [comment]
All changes are coming from another branch named 'use-fragments'
