### ISSUE TITLE
[Fire TV 4K Stick] Dropped frames with avc when autoframerate is enabled

### ISSUE THREAD

**Issue by fehmi1907** [yuliskov/SmartYouTubeTV#231]
For avc videos other than 30 fps (i.e. 24 or 25), playback is very jerky with autoframerate enabled. Stats screen also shows a ton of dropped frames. Lowering the resolution of the video does not help - even the lowest resolution stutters. 

However, if I choose vp9 instead of avc, playback is smooth with autoframerate. I have tried both the pro main and also pro alt builds but the result is the same.

**Comment by yuliskov** [comment]
I think this issue unfixable. I've done some research and come to conclusion that I've no control over rendering pipeline.
