### ISSUE TITLE
Update not downloading 

### ISSUE THREAD

**Issue by zakir1988** [yuliskov/SmartYouTubeTV#232]
The recent update on my Firestick is not downloading when I press upgrade usually I wait a few seconds to a minute for the update to download then Im prompted on the install screen to install the update. 

Then what I did  I downloaded  the update using downloader broswer  by going to the smartyoutubetv githib page.

Dont know if its effecting only firestick users.

When i downloaded the update it was slow in downloading the update apk file maybe that's normal as its maybe using free hosting servers for us to download the update file.

**Comment by yuliskov** [comment]
@zakir1988 all updates are coming from the github. I don't know what could cause slowdowns.
