### ISSUE TITLE
[Xiaomi box 3 pro android 5.1] play 2k and 4k video very not fluent

### ISSUE THREAD

**Issue by Laeoo** [yuliskov/SmartYouTubeTV#234]
processor:MT8693 2 core Cortex-A72+4 core Cortex-A53 64bit 2.0GH，zPower VR GX6250
 
play 2k or 4k video's status：
video resolution : 3840*2160@30
video/audio codecs x-vnd.on2.vp9(313)/vorbis(171)
video/audio bitrate 17.57Mbit/0.12Mbit
aspect ratio: none
hardware accelerated: false
dropped/rendered frames: 268/55
player paused: false
playback state: ready
display mode id: none

**Comment by yuliskov** [comment]
@Laeoo what do you expect? Your cpu too weak for the 4K software decoding. I don't think that any of the devices on the market capable of doing this. In case you've interested why this device isn't support vp9 hardware decoder. Answer is simple. This device is intended for Chinese region where vp9 codec isn't widely supported.

**Comment by Laeoo** [comment]
> @Laeoo what do you expect? Your cpu too weak for the 4K software decoding. I don't think that any of the devices on the market capable of doing this. If case you interested why this device isn't support vp9 hardware decoder. Answer is simple. This device is intended for Chinese region where vp9 codec isn't widely supported.

I don't know anything about that,thank for you answer XD
