### ISSUE TITLE
Sign-in gives an invalid code

### ISSUE THREAD

**Issue by WolfganP** [yuliskov/SmartYouTubeTV#236]
I tried to sign in into the program, and a popup showed a code (in the form ABC DEF GHI) and pointed me to go to a computer or phone where I'm logged in, and enter the code at youtube.com/activate.
Problem is that page seems to accept codes in the form ABCD-FGHI, as if the app and site aren't using the same sign-in functions or API versions.

**Comment by yuliskov** [comment]
It's a glitch on google site.
Please be patient, do refresh page/restart app two or more times.

**Comment by WolfganP** [comment]
Thx @yuliskov , you meant refresh on the computer or the app side? Which of the two is the valid code format?

**Comment by yuliskov** [comment]
I mean both. The app should be restarted first to get the correct code. Browser on pc should be refreshed after that too.

**Comment by WolfganP** [comment]
Looking at the documentation and samples, youtube.com/activate expects an 8 letters code (2 pairs of 4, see https://appuals.com/activate-youtube-using-youtube-comactivate/ as https://support.google.com/youtube/answer/3015415?hl=en doesn't mention the code format/lenght).

SYTTV gives a 9 letters code (3 sets of 3) that isn't accepted in YT /activate screen.

I deleted all SYTTV app data and reset device, started from scratch but to no avail (it always offer a 9 digits when trying to sign in when the desktop side expects a 8 letters one). Maybe there's a newer API to use SYTTV side?

PS: looking at the Youtube API documentation, it confirms the code should by in form of ABCD-EFGH form, as per the sample response in https://developers.google.com/youtube/v3/guides/auth/devices#step-2-handle-the-authorization-server-response

```
{
  "device_code" : "4/4-GMMhmHCXhWEzkobqIHGG_EnNYYsAkukHspeYUk9E8",
  "user_code" : "GQVQ-JKEC",
  "verification_url" : "https://www.google.com/device",
  "expires_in" : 1800,
  "interval" : 5
}
```

**Comment by WolfganP** [comment]
I re-tried full app delete-reinstall device side and cookies cleaning on desktop side yesterday, but to no avail. App still delivering the wrong code format (3x3) instead of the (4x2) expected and confirmed by the documentation I linked above.
Are there any logs I may provide to help troubleshoot? Thx!
