### ISSUE TITLE
App keeps disappearing after install

### ISSUE THREAD

**Issue by saalmaan** [yuliskov/SmartYouTubeTV#238]
Hello, 

I have tried to intall latest version of smart youtube and kids youtube both of which disapear after installation. 

any suggestions?

**Comment by yuliskov** [comment]
Hmm. The latest? Which one?

**Comment by saalmaan** [comment]
I tried the latest latest version from github

**Comment by yuliskov** [comment]
This version should be ok
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.44/SYTV_Orig_v6.16.44_r.apk

**Comment by saalmaan** [comment]
Thanks I will try this and let you know

**Comment by busyleung** [comment]
Are you using Xiaomi TV or other brand smart TV made in China? App keeps disappearing after install these days on my Xiaomi TV 3S.

**Comment by saalmaan** [comment]
Yes I am using Xiaomi TV 3

**Comment by busyleung** [comment]
Xiaomi blocks the smart yourube tv app. So I signed the apk by myself, then Xiaomi will treat it as another app, it won't disappear again and again.
Please check my blog and download: https://busyleung.com/xiaomi-delete-smart-youtube-tv-app.html

**Comment by saalmaan** [comment]
@yuliskov 6.16.44 is not disappearing but playback is really stuttering.
tried different settings but nothing working.

**Comment by yuliskov** [comment]
> playback is really stuttering

Still the same?
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.48/SYTV_Orig_v6.16.48_r.apk

**Comment by yuliskov** [comment]
Bug is fixed
