### ISSUE TITLE
Can’t run on the TV without sdcard

### ISSUE THREAD

**Issue by seatrix** [yuliskov/SmartYouTubeTV#239]
this app can’t run on the TV without sdcard,and display "Please, make sure that SDCard is mounted".
My tv don't have sdcard,but have usbdisk,the path is "/mnt/usbdisk".
can use the usbdisk  or internal cache as  cache ,or delay the detection of sdcard

**Comment by yuliskov** [comment]
Hi. Pls, post the log file: Main Screen > Tweaks > Save log to file

**Comment by seatrix** [comment]
The app can't save log to file because there's no sdcard, the log file should be saved in /mnt/sdcard/log.
You can test it when the sdcard is unmounted

**Comment by yuliskov** [comment]
Update regarding your problem
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.49/SYTV_Orig_v6.16.49_r.apk

**Comment by seatrix** [comment]
I try this version,but it seems that the app doesn't work.
It still display "Please, make sure that SDCard is mounted" about 10 times,then stucked,I tried many times,if I insert a sdcard ,it works fine.

I review the code,you changed  FileHelpers.java.
in this function" public static File getCacheDir(Context context) "
you just get the dir ,but don't check if you can write the dir,maybe  Environment.getExternalStorageDirectory() get a dir so cacheDir  isn't null,but the app don't have permisson to write.
I think it's better to check the dir permisson in "getCacheDir",and a writable dir will be returned.

**Comment by seatrix** [comment]
I tried to set log file, and display logfile is “/mnt/sdcard/log.txt”
I think Environment.getExternalStorageDirectory() will return “/mnt/sdcard" even if no sdcard is inserted.
If a sdcard is inserted ,the log file will be  “/mnt/sdcard/Android/data/live*****/log.txt”.

**Comment by yuliskov** [comment]
Thanks for the help. I don't think it's a case. All storage under /mnt/sdcard should be writable. You can test it yourself. But maybe I could be wrong. Anyway, let's try more simple solution first. Using an data storage of app itself. I don't remember why I didn't try it before.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.52/SYTV_Orig_v6.16.52_r.apk

**Comment by seatrix** [comment]
Great！It works！Thanks！
