### ISSUE TITLE
Xiaomi Mi TV 3 60" (4K mode)

### ISSUE THREAD

**Issue by Menogus** [yuliskov/SmartYouTubeTV#24]
version 6.8.61 - when use both 4K mode - video is very slow(lagged)
on 1080 - all ok...

Xiaomi BAR MDZ-18-DA Specifications: 
CPU - Mstar 6A928,Quad-core 1.4GHz Cortex-A17
GPU - Mali-760 MP4, 4 + 4-core
RAM - 2GB,Three-channel DDR3
Flash - 8GB,eMMC 5.0

**Comment by luckydevil13** [comment]
use youtube leanback from open gapps stock tv, (google play servces, market not need),
need root

**Comment by yuliskov** [comment]
It fully depends on your hw caps. More video formats will coming soon.
