### ISSUE TITLE
Don't remember audio coder on each video

### ISSUE THREAD

**Issue by nghiadhd** [yuliskov/SmartYouTubeTV#241]
My TV is MiTV 3. It doesn't support vorbit audio codec. The video is lag so much it I select vorbit codec. But when I change audio codec from vorbit to mp4a. But it reset to vorbit (default) on next video. I run on the latest smart youtube TV 6.16.49.
Expected: audio codec should be remember after selection.

**Comment by yuliskov** [comment]
done, thx that you've mention that

https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.51/SYTV_Orig_v6.16.51_r.apk

**Comment by yuliskov** [comment]
upd:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.53/SYTV_Orig_v6.16.53_r.apk

**Comment by nghiadhd** [comment]
Thanks @yuliskov 
I tested on 6.16.53
It works like charm
