### ISSUE TITLE
Pause button broken - Nvidia ShieldTV

### ISSUE THREAD

**Issue by rodalpho** [yuliskov/SmartYouTubeTV#246]
As of recent builds, the pause button on my remote no longer immediately pauses video playback. It first pops up the on-screen display, and then the second press will pause video. But then pressing it again does not _un_-pause. I tried disabling the enter/select button pausing from the options, but that didn't change this behavior. Can this be fixed? It's killing my muscle memory!

**Comment by yuliskov** [comment]
Sure, I'll fix this asap. Which version you're using?

**Comment by rodalpho** [comment]
Cool! I'm running 6.16.54.

**Comment by yuliskov** [comment]
thx

**Comment by yuliskov** [comment]
Seems, I need your help. I need to know a keycode which produces when you click on play button. This app  can help to obtain such info.
https://drive.google.com/uc?id=1LVqx4MjO_-NOgEPK7E9pf9Et27TpOOZh

**Comment by rodalpho** [comment]
I don't feel comfortable installing an APK from some random google drive, is it on the play store?

**Comment by yuliskov** [comment]
No. OK. Give me at least screen of your remote controller. I've found on inet next picture. Is it yours?
![http___i imgur com_6onsbzl 1](https://user-images.githubusercontent.com/5897464/52894751-1bb37500-31b8-11e9-897b-1c1b93c0f82e.jpg)

**Comment by rodalpho** [comment]
I'm using a Harmony Hub via Bluetooth. Using the button mapper app

https://play.google.com/store/apps/details?id=flar2.homebutton&rdid=flar2.homebutton

The play and pause buttons both show up as ID 85, "MEDIA_PLAY_PAUSE". I believe this is probably the same button as you'd find on a bluetooth keyboard for play/pause. Seems likely it's  keyevent KEYCODE_MEDIA_PLAY_PAUSE.

https://developer.android.com/reference/android/view/KeyEvent

**Comment by yuliskov** [comment]
This info is very helpful. I've prepared an update.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.63/SYTV_Orig_v6.16.63_r.apk

**Comment by rodalpho** [comment]
In 6.16.63, the play and pause buttons do not immediately pause the video, nor do they pop up the onscreen display. Instead the video just hiccups/stutters for a fraction of a second then continues.

**Comment by yuliskov** [comment]
Update:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.64/SYTV_Orig_v6.16.64_r.apk

**Comment by rodalpho** [comment]
Problem solved! Thanks!
