### ISSUE TITLE
4k VP9 no video

### ISSUE THREAD

**Issue by claudiorenato182** [yuliskov/SmartYouTubeTV#25]
First, congratulations for de app. Very good.

In my generic android 4.4.2 box with 4k "suport", i can't play the videos in 4k or 1080 using de VP9 codec, but with AVC codec plays very well in 1080 and "2k" (there's no option for 4k in AVC in the list).

In theory, android 4.4.2 has suport for vp9
https://developer.android.com/guide/topics/media/media-formats.html

Thanks.

**Comment by yuliskov** [comment]
Hi. Won't be fixed. I'm pretty sure that your box isn't capable to hw decode such videos.

**Comment by ProofWoW** [comment]
Will not be AVC 4K support?
I have MiTV3S, but VP9 not play fine

**Comment by yuliskov** [comment]
4k@avc should be soon. I've found the solution.

**Comment by liliass** [comment]
Hi Yuliskov, 

Is 4K@AVC available yet ? I have Mi4 4K@VP (v6.16.42)but heavy dropped frames.

**Comment by yuliskov** [comment]
@liliass google tries to get rid of avc formats. So, I think avc will disappear even on full hd videos.
