### ISSUE TITLE
Disable Upgrade Screen!?

### ISSUE THREAD

**Issue by spencerthayer** [yuliskov/SmartYouTubeTV#257]
> Version: 6.16.54 (PRO Main)
> Device: AFTMM (mantis)
> Language: en_US

6.16.54 is consistently getting an error with the `There is a new version (6.16.77) of Smart YouTube TV available!` prompt. After "upgrading" and "installing" 6.16.77 the app is opened and it remains 6.16.54. Once again the upgrade prompt appears again. This loops will continue indefinitely.

This error happens on my Firestick 4K and several other Firesticks which I have installed Smart YouTube TV on.

**Opinion:**
_At this point, I am tired of constantly being asked to upgrade the application. I simply do not want to upgrade this app every damned day. And my less technical friends who use this app have simply stopped bothering to use Smart YouTube TV on their Firesticks because of the annoying ugrade prompt. You need to fix this. Here is my suggestion..._

### In settings make a section for checking for the latest version and offering the option to upgrade. Also in this section provide the option to prompt the user with new upgrades - but keep this option disabled by default.

**Bingo! Problem solved.**

But until this is implemented how does a user disable the _annoying_ upgrade prompt?

**Comment by spencerthayer** [comment]
For the time being, I have uninstalled Smart YouTube TV. (No sense in using a broken app.) If this issue is addressed and fixed I will install it again and of course I'll do any troubleshooting any assignee to this ticket might have me do.

**Comment by spencerthayer** [comment]
So then @yuliskov this isn't likely going to be fixed?

**Comment by yuliskov** [comment]
Try to install app from scratch. The issue should gone.

**Comment by spencerthayer** [comment]
I do understand that is an option @yuliskov. But that isn't really a solution. No one is willing to uninstall and reinstall this app to make some basic changes. All of those things should exist in the menu structure.

**Comment by yuliskov** [comment]
I've changed package name some time ago.
I think that could cause an issue you talking about.
