### ISSUE TITLE
你好，创维55V8E电视安装后，只有声音，没有画面

### ISSUE THREAD

**Issue by hf97542** [yuliskov/SmartYouTubeTV#26]
你好，创维55V8E电视安装后，只有声音，没有画面，在灯光变暗后，仔细看还是有画面的，只不过这个画面很淡很淡，几乎看不见。

**Comment by hf97542** [comment]
![qq 20171127115407](https://user-images.githubusercontent.com/19843316/33250253-7ed6090c-d36a-11e7-9b99-177ec7d9482c.jpg)
![qq 20171127115447](https://user-images.githubusercontent.com/19843316/33250255-7f0a1cba-d36a-11e7-849a-43cc10fb041a.jpg)

**Comment by hf97542** [comment]
左上角有一条白线在闪动

**Comment by yuliskov** [comment]
Hi. What about 4K version? One intended specially for such cases. 
Oh... and try to write in English, please.

**Comment by hf97542** [comment]
It's all right to use the latest APP, thank you.

**Comment by hf97542** [comment]
Compared to the previous one, press the downward key of the remote control, and there is no video.

**Comment by yuliskov** [comment]
Need more details.
