### ISSUE TITLE
UI Display is Oversized - Resolved

### ISSUE THREAD

**Issue by stodd3** [yuliskov/SmartYouTubeTV#260]
**Edit**: Update to version 6.16.89 resolved the issue. 

Thanks for a great app and all the hard work!

~~**Version**: 6.16.79~~
**Device**: Amazon Fire TV Stick 4k

- Display was normal this morning/earlier today.

Troubleshooting Steps Taken:

- Restarted device.
- Unplugged the device completely and tried the app again.
- Uninstalled and reinstalled latest version of the app, issue persists.
- Checked device zoom/display settings, all OK.
- All other apps display correctly.

- Including images below (sorry for the quality):

![IMG_0904](https://user-images.githubusercontent.com/7934735/54965845-4e335900-4f40-11e9-83b6-3deee9c55654.JPG)
![IMG_0905](https://user-images.githubusercontent.com/7934735/54965846-4e335900-4f40-11e9-87f9-ec53e2ad0da5.JPG)

Is there anything else I can try that resolve the issue?

Thanks

**Comment by griefage** [comment]
Same exact issue with same device.

**Comment by FrostenFail** [comment]
The same problem on the TV Kivi 32FK32G

**Comment by Wolf68k** [comment]
Same issue but with a 1st gen Fire TV (not stick) but it only happens when I use the Lite Main. The Pro Main is ok, even though I don't have a 4k TV.

//edit
There was an update that fixed it for me.

**Comment by griefage** [comment]
update fixed the ui scale for me

**Comment by niuso** [comment]
An update always fixes this problem.
I have had this problem 2 times with 2 different versions. It is always removed by installing a new version, which you have never installed.

Now I want to keep an older version. With the old processor does not work so much, with the new 6.16.89 processor heats up more and my heating alarm appears on the screen.

When the problem appears in the configuration and type of device, it does not recognize mine and it appears as if it were a 42 "LG television.This is the error but give it up, delete data and reinstall it.The problem does not disappear.It only disappears with the new one version (no matter what it is) seems like a way to force yourself to update.

Now installed 6.16.89, the last and this error will appear in a future and force me to update again.

I have tvbox with s905D 2gb, mali 450, android 7

**Comment by saheb70** [comment]
same issue happening with mine Mi tv 4a 43 inches, **issue resolved**
i tried everything update and all.

ended up with downloading stable version from official site and installing it on tv manually. it worked for me.

link for stable version : https://github.com/yuliskov/SmartYouTubeTV/releases/download/stable/smartyoutubetv_latest.apk
  
Cheers,
