### ISSUE TITLE
IU display Oversize ver.2 

### ISSUE THREAD

**Issue by niuso** [yuliskov/SmartYouTubeTV#264]
Check https://github.com/yuliskov/SmartYouTubeTV/issues/260
I add the subject again because the previous one is solved and it is not.

An update always fixes this problem.
I have had this problem 2 times with 2 different versions. It is always removed by installing a new version, which you have never installed.

Now I want to keep an older version. With the old version  the processor does not work so much, with the new 6.16.89 processor heats up more and my heating alarm appears on the screen.

When the problem appears, in the configuration and type of device, it does not recognize my device and it appears as if it were a TV Lg 42". My screen 32" and tv box. .This is the error but give it up, delete data and reinstall it. The problem does not disappear. It only disappears with the new one version (no matter what it is) Seems like a way to force yourself to update.

Now installed 6.16.89, the last and this error will appear in a future and force me to update again.

How can I change the device in configuration? Maybe solve the error.

I have tvbox s905D 2gb, mali 450, android 7, tv 32"

**Comment by yuliskov** [comment]
already fixed
