### ISSUE TITLE
Translation french of SmartYouTubeTV

### ISSUE THREAD

**Issue by bubuleur** [yuliskov/SmartYouTubeTV#265]
Hello,
I come to you to make my contribution if it is possible
I translated several strings files. xml and I would like to send them to you
How can I do ?
Thanking you

**Comment by bubuleur** [comment]
Up please

**Comment by yuliskov** [comment]
hi. you can't attach files here directly
But you can post links for that files

**Comment by bubuleur** [comment]
Thank you for your reply
I translate the strings.xml , I saw that it should translate another? 
the translation will be in your next update?
[French translation.zip](https://github.com/yuliskov/SmartYouTubeTV/files/3042770/French.translation.zip)

**Comment by yuliskov** [comment]
ok, I'll check it

**Comment by bubuleur** [comment]
Thanks

**Comment by bubuleur** [comment]
Hello,
thank you for putting my translation in your new update and thank you also for not having blocked the subject
I looked I need to change some words that are wrong I will send you the translation
have a good day

**Comment by bubuleur** [comment]
Hello,
Enclosed French language updated
[French Update 1.00.zip](https://github.com/yuliskov/SmartYouTubeTV/files/3062322/French.Update.1.00.zip)
It is possible to release an update to see if all is well
Thanking you

**Comment by XcellMiguel** [comment]
Hi, I've got an update today, I noticed it's now in French, but there's some UTF8 conversion problems with accents when playing a video, for example the "Quality" text instead of "Qualité" is shown as "QualitÃ©".

**Comment by bubuleur** [comment]
Hello,
thank you for updating
I come back to you I have a problem with the letter é in french on the xml file that mark Ã©
and on the app there are words with Ã© 
it's normal ?
attached file where there are Ã©
[strings.zip](https://github.com/yuliskov/SmartYouTubeTV/files/3070314/strings.zip)
Thank you

**Comment by bubuleur** [comment]
Hello I can convert the file to UTF-8? will not it be a problem?

**Comment by bubuleur** [comment]
Up please

**Comment by yuliskov** [comment]
@bubuleur UTF-8 is a preferred encoding for app resources. So, yes, you can use it.

**Comment by bubuleur** [comment]
Hello,
ok perfect thanks for your answer I saved in UTF-8 format I hope it's good
attached files rectified
[French Update 1.10.zip](https://github.com/yuliskov/SmartYouTubeTV/files/3085617/French.Update.1.10.zip)
It is possible to publish an update to see if everything is good
Thanking you

**Comment by yuliskov** [comment]
upd:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.16.97/SYTV_Orig_v6.16.97_r.apk

**Comment by bubuleur** [comment]
Thank you very much yuliskov it is perfect there is more worry with Ã©
attached update I have rectified words that are cut by the application
[French Update 1.20.zip](https://github.com/yuliskov/SmartYouTubeTV/files/3089315/French.Update.1.20.zip)
It is possible to publish an update to see if everything is good
Thanking you

**Comment by bubuleur** [comment]
Up please
Thanks a lot

**Comment by bubuleur** [comment]
Hello,
I just saw that you have released a new update but I do not see if you have integrated my update for the French language
Thank you
Have a good day

**Comment by bubuleur** [comment]
I can not get your new update there is no link
Thanking you

**Comment by bubuleur** [comment]
Up please
I would like to test your new application
Thanks

**Comment by bubuleur** [comment]
Hello,
Excuse me for bothering you again but is it possible to have a link for the new update?
thank you for all

**Comment by yuliskov** [comment]
done
