### ISSUE TITLE
The key of the 4K mode remote controller is pressed and there is no related picture.

### ISSUE THREAD

**Issue by hf97542** [yuliskov/SmartYouTubeTV#28]
The key of the 4K mode remote controller is pressed and there is no related picture.

**Comment by hf97542** [comment]
![dffdsf](https://user-images.githubusercontent.com/19843316/33464703-a7d15a3e-d67e-11e7-9600-07f5f2cb4e2b.jpg)

**Comment by hf97542** [comment]
![qq 20171201093153](https://user-images.githubusercontent.com/19843316/33464720-c00152d0-d67e-11e7-9650-4ea89579e1e8.jpg)

**Comment by yuliskov** [comment]
Need more info. I don't understand where is a problem.
