### ISSUE TITLE
It does not work at all

### ISSUE THREAD

**Issue by LanStateMap** [yuliskov/SmartYouTubeTV#280]
It does not work on Ugoos AM3 (Android 7.1, Amlogic S912, Mali-T820MP3)
[log.txt](https://github.com/yuliskov/SmartYouTubeTV/files/3120145/log.txt)

**Comment by yuliskov** [comment]
Hi. Seems that required apk is 32-bit instead of 64. Try to install from this link.
https://www.apkmirror.com/apk/google-inc/android-system-webview/android-system-webview-74-0-3729-112-release/android-system-webview-74-0-3729-112-android-apk-download/

**Comment by LanStateMap** [comment]
I fixed the problem. I installed chrome and SmartYouTubeTV works fine now.

**Comment by LanStateMap** [comment]
Thanks for quick response =)
Do you think that it's possible to use webview instead of chrome?

**Comment by yuliskov** [comment]
I'm sure it should work.

**Comment by LanStateMap** [comment]
Thanks
