### ISSUE TITLE
Issue with music videos

### ISSUE THREAD

**Issue by saraah99** [yuliskov/SmartYouTubeTV#282]
Hi everyone, is there currently an issue with playing vevo videos? I noticed it last night on fire tv: it looks as if the video starts playing and a frame does appear on screen for like a split second, but then the screen goes black and all I see is "loading...". I updated to the latest stable release and even tried a different launcher, but no dice. Thanks in advance.

**Comment by ArmaWizard** [comment]
https://github.com/yuliskov/SmartYouTubeTV/issues/274

Same issue for me, above link is related.

**Comment by attila-fazekas** [comment]
Same issue here: after updating to 6.16.98 most of the videos are stuck in "Loading..." state with black screen. 

I have Sony KDL-55W809C but for some reason under App version it says: _Device BRAVIA 2015 (SVPDTV15_EU)_, don't know if it was like this all the time tho

**Comment by yuliskov** [comment]
@atisss33 hi, could you post there some logs? In order to do this logging should be enabled inside app's settings: app's boot screen (where you've choose desired launcher) > Tweaks > Save log to file

**Comment by attila-fazekas** [comment]
@yuliskov Here you are: [log.txt](https://github.com/yuliskov/SmartYouTubeTV/files/3168992/log.txt)

First time it did open Steve Bug & Mr. V: The Long Run (Steve Bug's Vocal Mix) video after some glitch, then 2nd and 3rd attempts failed

**Comment by yuliskov** [comment]
@atisss33 thx, friend. I'll check it.

**Comment by saraah99** [comment]
Music videos are back up and running after updating to the latest stable release. Thanks yuliskov!

**Comment by saraah99** [comment]
Seems like this issue is back on. 

I guess this link is related...
#294

**Comment by yuliskov** [comment]
Hi, guys. Could anyone post here the log from this release?
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.02/SYTV_Orig_v6.17.02_r.apk

**Comment by yuliskov** [comment]
Up. Guys, please post here the log from this release.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.02/SYTV_Orig_v6.17.02_r.apk

**Comment by saraah99** [comment]
Here you go [log.txt](https://github.com/yuliskov/SmartYouTubeTV/files/3249422/log.txt)

**Comment by yuliskov** [comment]
@saraah99 thx, try this update
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.03/SYTV_Orig_v6.17.03_r.apk

**Comment by saraah99** [comment]
Just tried 6.17.03 as well, which you uploaded in the other post, but no dice.

**Comment by yuliskov** [comment]
@saraah99 ok, I'll continue to search for the solution. Thanks again for the help.

**Comment by saraah99** [comment]
Yeah, this one exactly, but the issue is still there.

**Comment by saraah99** [comment]
No problem, thank you!

**Comment by saraah99** [comment]
Latest update fixed it. Thanks @yuliskov. I'm closing this issue again.

**Comment by zyxmon** [comment]
I have the same problem on different tv boxes. The last test version 6.17.10 solved the issue on 2 of 3 boxes. The problem is present on mi box 3 (MDZ-16-AB) and was solved on mi box S (MDZ-22-AB) and a realtek based box.
There was no problem a month ago.
The problem happened (probably a coincidence) after I've changed google account password.

**Comment by zyxmon** [comment]
I have cleaned the data, reauthorized Smart Youtube and the problem is gone on me box 3.
Thank for the great program.
