### ISSUE TITLE
Digital Trends video doesn't start

### ISSUE THREAD

**Issue by yoasif** [yuliskov/SmartYouTubeTV#289]
Trying to play this video: https://www.youtube.com/watch?v=bi2YQKWL3PQ and it never starts, no matter what quality setting I use. 

The screen shows "Loading" and it never loads. 

I have seen this with various videos, but never remember which videos they were. This one got me so frustrated that I opened up a browser to play the video, which worked without any issue. 

Using the default 4k mode (even wiped data to test) on a Nvidia shield.

**Comment by f-o** [comment]
Getting the "Loading..." error a lot recently as well.
Sony android tv, both on 4K and 4K alt

**Comment by f-o** [comment]
Update:
When clicking on videos, the playback opens, and the text "LOADING..." shows on a black background.
After 20-30 seconds, the video starts to play.
Playback continues for anything between 5 seconds to 2 minutes, and then shows black screen with "LOADING..." again.
This continues all throughout the video. 

Worth to notice is that this doesn't happen with all videos. 
Sometimes jmyou can watch 10 different videos in a row, with no issues, and then suddenly the next video will have this problem. 
The affected video will continue to have this issue, and even if you press "Back", and try to open the video again, it will continue with the "LOADING..." error.

Version: 6.16.98 (PRO Main)
Device: BRAVIA 4K 2015 (SVP4KDTV15_EU)
Language: en_GB
Region: GB

Connection: Wired Ethernet
Speed: 38.66 / 8.65 Mbps

**Comment by yuliskov** [comment]
The update:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.10/SYTV_Orig_v6.17.10_r.apk

**Comment by yoasif** [comment]
This works now, thanks!
