### ISSUE TITLE
Missing feature: Adjust cast volume

### ISSUE THREAD

**Issue by lokErik** [yuliskov/SmartYouTubeTV#29]
Missing feature, can't adjust volume when I cast to Smart YouTube app, guess it is permission issue that prohibit the system sound to change. Love the app otherwise, am using the latest version and app sound is working now too. Sometimes after a long time idle the app won't start playback just stays at "loading", changeing to another clip and same situation. A restart solves it!

**Comment by yuliskov** [comment]
Hi. Thanks for your time. Could you post here your device name? Also, interested to know whether your device has Gapps installed or not. I need to investigate the problem more deeply.

**Comment by lokErik** [comment]
I am using a rooted MXIII-G2 with Android 6.0.1
It came with the usual gapps installed. Ota updated once.

Casting to chrome browser on the box I am able to adjust volume and chrome got permission for system sound. But chrome ui is not remote friendly and pull more resources.

**Comment by yuliskov** [comment]
Thanks for the info, friend.

**Comment by lokErik** [comment]
Hi, saw that they released a new version of YouTube for Android Tv. V.2.02.08 had to try it for sake of trying. Law and behold the cast volume is now adjustable from phone to tv. Tried the last version 2.02.04 were it wasn't possible. So latest version got fix for it. Thought it might be of help to  localize the bug.

**Comment by yuliskov** [comment]
@lokErik I doubt that something can be done with this

**Comment by yuliskov** [comment]
redirected to #38
