### ISSUE TITLE
Video language subtitles are always the automatically generated ones

### ISSUE THREAD

**Issue by bennyhillthebest** [yuliskov/SmartYouTubeTV#292]
That means that on english videos where english human generated subtitles are available the app defaults to the english automatically generated ones and the english human generated ones cannot be selected in the subtitles menu.

[One example.](https://youtu.be/kjyeCdd-dl8)

**Comment by yuliskov** [comment]
Just tested the sample. Subs're working flawlessly. I don't know what you're talking about.

**Comment by bennyhillthebest** [comment]
On the video i linked, with the pro main launcher, there should be two type of subtitles for the english language, automatically generated ones and the human generated ones. There is only one option "en wvtt" which are the automatically generated ones. Hopefully this explains it better.

(On the Lite Main launcher there are the two possibilities btw, but no playback speed control which i really like).

**Comment by bennyhillthebest** [comment]
These are the subtitles screeshots: https://imgur.com/a/WViceYk 1st screeshot is the Lite Main Launcher which is ok, 2nd screenshot is the Pro Main Launcher which is wrong!
