### ISSUE TITLE
SmartYouTube TV Live

### ISSUE THREAD

**Issue by vsachd** [yuliskov/SmartYouTubeTV#293]
I downloaded the SmartYouTube TV Live app for Firestick, and it works great.  Thank You!

I thought of installing it on my Amlogic T95Z plus Android 7.1.2 Media Box, and it downloaded and opened up great. I can see the guide. However, when I try to watch a live show, it goes into "Loading..." mode and never starts the show. What could I do differently?  By the way, SmartYourTube from you works fine on this media set-top box.

Additionally, I could download the YourTube App directly from the Google Play Store, but it downloaded the Android phone version, which is hard to navigate without a touchscreen TV and a full keyboard and mouse. I have a Smart Media TV Box mouse. Also, it tries to look for location even with Wifi Location google services on it does not find the location, and complains GPS is not working. Anyways, that's not your app and not your problem. It is just trying to see if your LiveTube can open up the stream.

Thanks

**Comment by yuliskov** [comment]
Live app is dependent on DRM services that aren't available on non-branded boxes. Don't know how to bypass this restriction.
