### ISSUE TITLE
Missing some files in git repositoty

### ISSUE THREAD

**Issue by dagerler001** [yuliskov/SmartYouTubeTV#295]
After pulled project from GitHub , i tried build it, but encountered with problem:

`Could not read script 'C:\Users\Maxwell\Downloads\SmartYouTubeTV-6.17.02\SharedUtils\core_settings.gradle' as it does not exist.`

Seems like not all file what necessary for success build added to git candidate.

**Comment by yuliskov** [comment]
fixed
