### ISSUE TITLE
Chrome browser not installed error

### ISSUE THREAD

**Issue by mo123** [yuliskov/SmartYouTubeTV#296]
I get a Chrome browser not installed error when SYTV starts up.
But AndroidTV devices have no Chrome app to install from the ATV Store.

**Comment by haojiezhu** [comment]
SmartYouTubeTV uses WebView. On Android TV, "Android System WebView" (which is powered by Chrome) allows apps to display web content. Try to uninstall WebView updates under "System -> Apps" and then reinstall the latest WebView update in Play Store. A new version based on Chrome version 75 just came out today.

**Comment by yuliskov** [comment]
@mo123 try to install chrome manually from here:
https://www.apkmirror.com/apk/google-inc/chrome/
