### ISSUE TITLE
Can not play video

### ISSUE THREAD

**Issue by Liohao1995** [yuliskov/SmartYouTubeTV#299]
I installed 6.17.10 version, but i can not play video, is it work with android 4.4 ?, i check details information, the network activity is 0 kb while the connection speed is about 6000 Kbps, i want to reselect the mode( lite/pro) how i can do? Sorry for my english, please

**Comment by yuliskov** [comment]
Exit from the app (press BACK multiple times). Start the app, while you see loading circle press BACK.
