### ISSUE TITLE
Large RAM consumption

### ISSUE THREAD

**Issue by devslava** [yuliskov/SmartYouTubeTV#3]
Hi
We have some issues with the app. 
We have Android Rockchip set-top box with 512 mb RAM.
When playing long videos, after ~15-30 minutes video starts to freeze, app consumes 60-65% of RAM and begins to displace other Aandroid processes.
Turning on webm or switching to WebView doesn't solve the problem.

Clearing webview cache every two minutes programmatically doesn't solve the problem. 
It behaves better, but app freezes at the end anyway.
Is there any way to let this app consume less RAM?
Maybe, there is some memory leak?

1 gb RAM box works well, but we need to run this app on 512 mb box.

**Comment by yuliskov** [comment]
Yup. I know. Seems that this behavior depends on running hardware. As temporal workaround I'll add cache clearing capability.

**Comment by yuliskov** [comment]
Another solution might be setting lower resolution on such devices.

**Comment by devslava** [comment]
Thank you. I hope we will find some soluton.
But, as I said, I was trying to call WebView.clearCache(true) or mXWalkView.clearCache(true) every to minutes with no success :(

Do you mean lower video resolution? How can I do this?

**Comment by devslava** [comment]
I've found  WebView.setInitialScale(). Testing this way now.

**Comment by yuliskov** [comment]
Resolution change still hard to implement. I doubt that this can be done by manipulation with WebView.
Currently I'm working on intercepting http requests. Hope that it will be implemented soon.

**Comment by devslava** [comment]
WebView.setInitialScale() actually changes video resolution.
When I set w.setInitialScale(160) in BrowserWebViewFactory, resolution changes from 1280x720 to 640x360 and works much longer until freezing - about 50-60 minutes. But it freezes completely at the end anyway.

**Comment by yuliskov** [comment]
@devslava When I experimented with setInitialScale there was problem with interface cropping. So I decided to drop this idea.

**Comment by devslava** [comment]
Wow, seems I've defeated large memory consumption.
I have disabled mp4 (disableCodec('mp4')) and now it plays withost DASH. Maybe, DASH implementation is no very well on my device or Android version(4.4.2). Memory allocation has significantly changed better way and now Mediaserver is utilized much more. 
This works perfectly with WebView. Video plays smoothly for hours. But when I set engine type XWalk I have this line in the stack trace very often and video stops sometimes:
`E/chromium: [ERROR:webmediaplayer_android.cc(790)] Not implemented reached in virtual unsigned int content::WebMediaPlayerAndroid::decodedFrameCount() const`
Yes, there is no Buffer health and network activity monitor now but who knows, maybe it was the reason.
Just check out screenshots.
So you can try to make some experiments this way :)

![image](https://cloud.githubusercontent.com/assets/8116529/22783411/5582861e-eed4-11e6-96a9-df9d783f9922.png)

![image](https://cloud.githubusercontent.com/assets/8116529/22783756/dc8412e4-eed5-11e6-9e0d-0ca25f10c739.png)

![image](https://cloud.githubusercontent.com/assets/8116529/22783987/d12ce5fa-eed6-11e6-8764-b8e054f64849.png)

**Comment by devslava** [comment]
Moreover, I've turned on debug info in default Android youtube client and it shows the same codecs info. Seems it plays without DASH too.
![image](https://cloud.githubusercontent.com/assets/8116529/22787261/5dd4ac74-eee4-11e6-9354-d51770a9e50c.png)

**Comment by yuliskov** [comment]
@devslava I can add this fix specially for your device. All I need is device name: Android Settings > About box > Model number?

**Comment by yuliskov** [comment]
@devslava very cool pie chart.  In which app you created it?

**Comment by devslava** [comment]
@yuliskov Can you please add NG3128HD to the applyCodecFixes in your Smart YouTube TV in Google Play too? (Not Beta version) Please disable webm and mp4 codecs.
Something like 
`applyCodecFixes({'X92': 'webm', 'MiTV': 'webm', 'NG3128HD': 'webm', 'NG3128HD': 'mp4' });`
Thanks.
I advice you to test this solution for other devices too. I am sure that DASH is working not well with a lot of other devices too. DASH is cool technology, but It seems that good media player like ExoPlayer is needed to handle it well. 

There are pie charts from Android Device Monitor that comes with Android SDK Tools.  You can start it from android Studio - Tools > Android > Android Device Monitor.

**Comment by yuliskov** [comment]
@devslava thank you for the contribution to this project. Just published fixed version to Google Play. Check it out when you have a time.

**Comment by devslava** [comment]
@yuliskov Thank you!
I will check it.

**Comment by yuliskov** [comment]
Last version has 4K launcher. It consumes much less ram. Please, test it.
