### ISSUE TITLE
Online upgrade, parse error occurred

### ISSUE THREAD

**Issue by hf97542** [yuliskov/SmartYouTubeTV#30]
Online upgrade, parse error occurred
The TV box is Android 4.2.2

**Comment by hf97542** [comment]
![qq 20171205192005](https://user-images.githubusercontent.com/19843316/33604593-8455f8aa-d9f1-11e7-8f41-8b9e11dda8f6.jpg)
![qq 20171205192010](https://user-images.githubusercontent.com/19843316/33604594-848c1ef8-d9f1-11e7-90e9-51b5d253de56.jpg)
![qq 20171205192014](https://user-images.githubusercontent.com/19843316/33604595-851b8142-d9f1-11e7-8e57-0541d9ad10c7.jpg)
![qq 20171205192021](https://user-images.githubusercontent.com/19843316/33604596-854b6b0a-d9f1-11e7-84cc-55ebdcff185f.jpg)

**Comment by hf97542** [comment]
![qq 20171205192005](https://user-images.githubusercontent.com/19843316/33604625-9cc70834-d9f1-11e7-9699-adb80565307f.jpg)

**Comment by yuliskov** [comment]
Hi. Please, test this apk.
https://drive.google.com/uc?id=1PNL6uaRdKZS56f0fqtd9QZUU5WE-75ob

**Comment by hf97542** [comment]
All right, thank you.
