### ISSUE TITLE
Various issues with latest releases

### ISSUE THREAD

**Issue by ZandigSlaytanic** [yuliskov/SmartYouTubeTV#306]
Currently using: 6.17.27
System: Nvidia Shield TV

1) Using PRO Main or PRO Alt - the Suggested Videos do not load/show on the screen when playing a video - just shows blanks boxes.

2) Using LITE Main or LITE Alt - playing a video results in a white screen with audio playing.

**Comment by yuliskov** [comment]
pls try this update: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.28/SYTV_Orig_v6.17.28_r.apk

**Comment by ZandigSlaytanic** [comment]
Thank you - but still the same issues.
Here is the log: 
[log.txt](https://github.com/yuliskov/SmartYouTubeTV/files/3360795/log.txt)

**Comment by yuliskov** [comment]
upd
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.30/SYTV_Orig_v6.17.30_r.apk
