### ISSUE TITLE
[FR] Sponsor Block

### ISSUE THREAD

**Issue by seniorm0ment** [yuliskov/SmartYouTubeTV#339]
Been using this extension that is basically crowdsourced information per video that skips over sponsors in the video. I would absolutely love to see this implemented into SmartYoutubeTV if it would be possible to do. So far it has worked very well for me, It of course doesn't block sponsors in every single video seeing a user has to submit the times to block. But it has worked very well for me and blocks in most popular videos at the least.

https://github.com/ajayyy/SponsorBlock

**Comment by fgl27** [comment]
not news
https://github.com/yuliskov/SmartYouTubeTV/issues/314

comment there, close this :+1:

**Comment by seniorm0ment** [comment]
my b
