### ISSUE TITLE
latest release has ruined 4k playback on MiTV 3 60"

### ISSUE THREAD

**Issue by saalmaan** [yuliskov/SmartYouTubeTV#34]
Hi,

I have been using this app for some time but most recent version has forced me to install older version to get a smooth 4k playback. 4K playback was smooth until 6.12.05 but upon installing 6.12.09 started seeing 4k issues. 

Here are details of my Hardware.

MITV 3 firmware version: 1.3.33
Online video version: 2.5.1(159b)
screen software version: 00.01.5A
Android version: 5.1.1
Kernal version: 3.10.23
Build number: 7.6.9.1426

You have developed a great app so, keep it up. I have posted this app in many Xiaomi forums as recommend app for MiTVs. 👍

Many thanks
![img_5957](https://user-images.githubusercontent.com/4620730/34063960-85739c52-e1ed-11e7-8e86-0d746ad09470.JPG)
![img_5958](https://user-images.githubusercontent.com/4620730/34063961-858f1914-e1ed-11e7-9aa1-2055f4eeaf93.JPG)

**Comment by yuliskov** [comment]
Hello. Thanks for the your time.
Hope to fix this issue with next update.

**Comment by yuliskov** [comment]
Please, check the latest release.

**Comment by TheMiguelBi** [comment]
I saw that the application has updated to version 6.12.11. 
Is there any link to get the APK file to the latest version?
Thanks for this great App!
Miguel

**Comment by yuliskov** [comment]
@TheMiguelBi maybe later

**Comment by WolfganP** [comment]
@TheMiguelBi try https://github.com/yuliskov/SmartYouTubeTV/releases/latest , it's an standard github's feature

**Comment by saalmaan** [comment]
I have tested latest v6.12.11 and can report that 4k video playback is back to smooth. reported issues seem to be fixed. thanks
