### ISSUE TITLE
Navigation broken in 6.17.118

### ISSUE THREAD

**Issue by anubis-genix** [yuliskov/SmartYouTubeTV#341]
The update broke the navigation in PRO Alt. Switching over to PRO Main for now.

**Comment by yuliskov** [comment]
Hi. Pls, explain little bit more, what is a problem.

**Comment by anubis-genix** [comment]
Sorry, forgot to mention I'm running it on FireTV 4K of it helps. 
Once Pro Alt is loaded I'm not able to move through the app itself. Up, down, left, right and select don't work at all. All I can do is to long press back to close the app.

**Comment by anubis-genix** [comment]
Cleared cache and data without restoring the backed up settings, otherwise the navigation would get struck again.

**Comment by yuliskov** [comment]
@anubis-genix would you be so kind to post me by email copy of backup that have caused this bug? Backup is stored here: /<device_internal_memory>/data/com.liskovsoft.videomanager
My email: yu.liskov@gmail.com

**Comment by anubis-genix** [comment]
I just sent you the email with the Backup folder attached.

**Comment by yuliskov** [comment]
@anubis-genix my inbox is empty. Pls resend.
alt email: firsthash@gmail.com

**Comment by yuliskov** [comment]
Done. Email received. Thanks, again.

**Comment by anubis-genix** [comment]
You're welcome. I also sent it to your second adress. Thanks for looking into this issue!

**Comment by yuliskov** [comment]
Excellent news.
Backup successfully restored and bug reproduced.
I'm starting to search the solution.
