### ISSUE TITLE
Remote Control Rewind and FFD Buttons broken in 6.17.118-119

### ISSUE THREAD

**Issue by thenextmans** [yuliskov/SmartYouTubeTV#342]
The rewind button now mistakenly acts as if the back button was pressed on a FireTV remote control using Nvidia Shield on the Pro Main profile. The Fast foward button now skips right to the end of the video rather than seeking forward.

**Comment by yuliskov** [comment]
Hi. I've changed mapping little bit since 'Fast forward' and 'Fast backward' already mapped to the navigation buttons. Do you think that's not convenient?

**Comment by thenextmans** [comment]
Which version started with the new mapping? The FireTV remote's rewind and fast-foward button has always worked perfectly with your app until recently. Now they are now not functioning properly or as expected, which creates a frustrating user experience. 

Thanks for all your work on this wonderful app!

**Comment by yuliskov** [comment]
Mapping changed starting from *.118

**Comment by anubis-genix** [comment]
The new mapping is confusing to be honest. I don't see the reason for changing the reverse and forward functionality.

**Comment by thenextmans** [comment]
yes i would have to agree with "anubis-genix" as far as the new mapping.  What is the purpose of the new mapping configuration?  The rewind and fast-forward buttons used to serve discrete seeking functions separate from the directional navigation buttons. I would use them every time i use SmartYoutubeTV, which is daily.  Now, those buttons are functionally broken, with the rewind button seeming to go back and the fast-forward button skipping right to the end of the video.  Please consider re-instating the original mapping which had always worked very well until the change. 
Thank you!

**Comment by yuliskov** [comment]
reverted in latest stable: https://github.com/yuliskov/SmartYouTubeTV/releases/download/stable/smartyoutubetv_latest.apk

**Comment by anubis-genix** [comment]
thanks a lot @yuliskov !

**Comment by thenextmans** [comment]
thanks so much @yuliskov ! The functionality is back to it's normal, intuitive baseline! I appreciate your work on this excellent app and your responsiveness to your users.
