### ISSUE TITLE
Recommended videos not selectedable

### ISSUE THREAD

**Issue by saalmaan** [yuliskov/SmartYouTubeTV#35]
Hi, 

Youtube video recommendations that show during or after video are not selectable anymore. Pressing up/down on remote recommendation don't open and pressing quickly at the end of the video does show recommendation but not enough time to select the videos as next video starts playing automatically.

I hope this can be fixed because this is an important feature for content discovery.

Many thanks

**Comment by yuliskov** [comment]
Hello. I'm not sure that I understood your correctly. Could you give some screenshots? Which version did you use?

**Comment by saalmaan** [comment]
I am using version 6.12.05.

**Problem:**
1) First screenshot you can see that I am trying to see video youtube recommendation (as shown in 2nd screenshot) by clicking up/down on the remote control but nothing showup. In Youtube's web tv mode you can actually see recommendation when pressing down arrow key on remote control.

2) In the Second screenshot, you can see that I have managed to see video recommendation. I manage to do this by waiting for video to finish and then very quickly press down arrow key on the remote control and select a video. If I am marginally slower then next video starts playing and these recommendations disappear.

**Solution:**
It will be great to implement video recommendation interface similar to https://www.youtube.com/tv as shown in third screenshot

I hope this clarifies the issue. Happy to give more information and context.

Thanks

_First screenshot taken from smart youtube app_
![screen shot 2017-12-16 at 02 39 02](https://user-images.githubusercontent.com/4620730/34066670-5dcb5cae-e20a-11e7-8cb9-527f09b144bc.png)

_Second screenshot taken from smart youtube app_
<img width="1074" alt="screen shot 2017-12-16 at 02 39 22" src="https://user-images.githubusercontent.com/4620730/34066696-ac9de810-e20a-11e7-8870-548dfe331080.png">

_Third screenshot taken from http://youtube.com/tv_
<img width="1826" alt="screen shot 2017-12-16 at 02 50 22" src="https://user-images.githubusercontent.com/4620730/34066754-0493298a-e20c-11e7-8d3f-679e660da913.png">

**Comment by yuliskov** [comment]
Confirmed. Thanks for the detailed info.

**Comment by saalmaan** [comment]
I can confirm the youtube suggestions during and after video has finished are working. Thank you for fixing this.
