### ISSUE TITLE
https://www.youtube.com/tv closed!

### ISSUE THREAD

**Issue by Codeinfirst** [yuliskov/SmartYouTubeTV#350]
How can we open through the website? opened with smart tv application. I changed user agent but it didn't work

**Comment by yuliskov** [comment]
Try to use UAs from this file:
https://github.com/yuliskov/SmartYouTubeTV/blob/f8d5c99409614d1ae79185894ffbe53f0264bf4e/common/src/main/java/com/liskovsoft/smartyoutubetv/misc/UserAgentManager.java
