### ISSUE TITLE
Question: Global voice search

### ISSUE THREAD

**Issue by TomberWolf** [yuliskov/SmartYouTubeTV#357]
How does global voice search work on a Fire TV Stick?
I don't know how to use it.

**Comment by yuliskov** [comment]
Press and hold voice button (works in any place).
And try to say: "YouTube Linkin Park"
P.S. Bridge app should be installed.

2019-10-14 23:54 GMT+03:00, Tom <notifications@github.com>:

**Comment by TomberWolf** [comment]
Just that simple... thank you so much.
