### ISSUE TITLE
Stats for nerds missing dropped frames information

### ISSUE THREAD

**Issue by saalmaan** [yuliskov/SmartYouTubeTV#36]
Hi, 

**Problem:**
In the version, 6.12.05 stats for nerds is missing dropped frames information. Can this be brought back as this is valuable information for debugging various other things.

**Solution:**
Introduce youtube.com/tv style stats for nerds

Many thanks 

_Screenshot taken from smart youtube 6.12.05_
![img_6008](https://user-images.githubusercontent.com/4620730/34066854-4f1ed8da-e20e-11e7-97e2-33b9f1b708a9.JPG)

_Screenshot taken from youtube.com/tv_
<img width="1878" alt="screen shot 2017-12-16 at 03 08 40" src="https://user-images.githubusercontent.com/4620730/34066868-9beec6ca-e20e-11e7-99e1-1faa01826d0d.png">

**Comment by yuliskov** [comment]
It's reasonable proposition. Stats're really need to be upgraded. Thanks.

**Comment by yuliskov** [comment]
Fixed in the newed versions.
