### ISSUE TITLE
First video not loading on 6.17.183 Pro Alt

### ISSUE THREAD

**Issue by anubis-genix** [yuliskov/SmartYouTubeTV#363]
Everytime I launch the application, the first video I select is not playing. All I can see is the black background where the video is supposed to be and the recommendation bar at the bottom. Once I cancel the playback and reselect the video again the video starts to play. I'm running it on a Fire TV 4K Stick. Had the same problem in the past 3 releases too.

**Comment by anubis-genix** [comment]
Fixed with .187

**Comment by yuliskov** [comment]
thx

2019-10-20 16:36 GMT+03:00, anubis-genix <notifications@github.com>:
