### ISSUE TITLE
Adding videos to watch later list

### ISSUE THREAD

**Issue by aleks-zverev** [yuliskov/SmartYouTubeTV#388]
Trying to add or delete videos to watch later list, when in Pro main version, results in pulling up suggestions or nothing instead of watch later feature pop up.
Sometimes it works correctly, not sure why.
Tried several releases - not working now.
Km8 pro 
Android tv 7.1.2 rom

**Comment by yuliskov** [comment]
test build: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.240/SYTV_Orig_v6.17.240_r.apk

**Comment by aleks-zverev** [comment]
Yes, it works! Thanks.

**Comment by zxhwkk** [comment]
My APP version is   web_20201111_00_RC01
 Deice  TV,Samsung/SmartTV,SamsungBrowser (1.1),Tizen (2.4.0) 
 Lang  en
 Geo  us,HongKong
 Client  TVHTML5,7,20201111.00.01

Even though the App says My device is TV or Samsung its ACTUALLY a  NVIDIA SHIELD Pro 2017  Android Pie 9

The App work great only problem I have found I can NOT DELETE or add anything to watch later      any suggestions I can try please advise.
