### ISSUE TITLE
 I can not interrupt video when sending it from the cell phone

### ISSUE THREAD

**Issue by jackiehhop** [yuliskov/SmartYouTubeTV#39]
Hello
Friend is staying great your work

I have a small problem previously with version 6.8.38 I could send different videos and interuptube them when I sent it now with the new version I can not send videos until the video that I sent first is finished

 I RECORD A VIDEOS FOR YOU TO SEE BETTER THE FAILURE
BEFORE OK -------- AFTER BAD

https://drive.google.com/open?id=18aPe6ISVQEynhmojBM6jihViGH3hNApO

**Comment by yuliskov** [comment]
@jackiehhop many thanks. Check the latest version. https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.25/SmartYouTubeTV_Orig_v6.12.25_r.apk

**Comment by jackiehhop** [comment]
it's still the same the app does not interrupt the video

**Comment by yuliskov** [comment]
@jackiehhop thanks for the reply. Let me to clarify something. Regression occurs somewhere between 6.8.38 and 6.8.41. Am I right?

**Comment by jackiehhop** [comment]
the application has stopped when it starts (4k MITV and others) version 6.8.38
the application has stopped when it starts (4k MITV and others) version 6.8.41
the application has stopped when it starts (4k MITV and others) version 6.8.43

the version 6.8.49 app let start and also interrupts the video 

record another video with the presented situations

videos (stopped) and other (the version 6.8.49)
here link 
https://drive.google.com/open?id=18aPe6ISVQEynhmojBM6jihViGH3hNApO

**Comment by yuliskov** [comment]
@jackiehhop if it possible, I need to know the latest version when all working fine. Did the 6.8.49 version is the last version without such problems?

**Comment by jackiehhop** [comment]
if I use the version 6.8.49 and this works well

**Comment by yuliskov** [comment]
@jackiehhop try 6.12.03 version, please.
 https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.03/SmartYouTubeTV_Orig_v6.12.03_r.apk

**Comment by jackiehhop** [comment]
the version 6.12.03 not is work this function

**Comment by yuliskov** [comment]
@jackiehhop hi, friend. Does the last version change something for you?

**Comment by jackiehhop** [comment]
hello my friend 

it's still the same, the application does not let you send the video
thanks for your help

**Comment by jackiehhop** [comment]
BUT THE ALTERNATIVE 4K VERSION IF IT IS DOING THE FUNCTION BUT CONSUMES A LOT OF MEMORY OF THE TELEVISION IN CHANGE THE VERSION 4K WORKS STABLE BUT DOES NOT MAKE THE CHANGE OF THE VIDEO FROM THE PHONE

**Comment by yuliskov** [comment]
Hi, friend. I don't have a clue what is going on. If only you could find between which versions regression appeared.

**Comment by jackiehhop** [comment]
hello mi friend


the regression happens after version 6.8.64, when I go to version 6.12.03 it does not do this function anymore

**Comment by yuliskov** [comment]
@jackiehhop thanks

**Comment by yuliskov** [comment]
@jackiehhop seems fixed. Thanks for the your support, friend.

**Comment by jackiehhop** [comment]
thank you very much my friend is working well :) 

I can send videos from the phone

**Comment by yuliskov** [comment]
@jackiehhop thanks to you. There is no need for the video, as long as there are no issues.

**Comment by yuliskov** [comment]
@jackiehhop hi. Cant test 4K for tehnical reasons. Is this happens only in 4k mode?

**Comment by jackiehhop** [comment]
YES, IF FRIEND HAPPENS IN THE 4K MODE

**Comment by yuliskov** [comment]
@jackiehhop hmm. Maybe video with the bug could help.

**Comment by jackiehhop** [comment]
hello mi friend 

here this the video
https://drive.google.com/open?id=1OP-XnrAfMH7jaGI79iGe0XZiQTNh7D7D

**Comment by yuliskov** [comment]
@jackiehhop thanks for the video. I think that problem in vp9 codec. Its poorly supported by most of the devices. Unfortunately, AVC 4k codec, google have deleted couple weeks ago. So, you have no choise. Pleaee, correct me, if I'm not right and previous builds of my app performs well.

**Comment by jackiehhop** [comment]
HELLO MY FRIEND

A BENA FOR MA TO SOLVE IT WOULD BE TO ADD TO THE BEGINNING OF THE CONFIGURATION THE RESOLUTION OF THE SCREEN BEFORE LAUNCHING THE APPLICATION AND TO AVOID THIS ERROR FROM A LOT BEFORE

**Comment by yuliskov** [comment]
Preferred codec can be selected from main launcher.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.59/SmartYouTubeTV_Orig_v6.12.59_r.apk
![screen](https://user-images.githubusercontent.com/5897464/35694019-a7d53a10-0788-11e8-88c0-a41f07122fe0.png)

**Comment by yuliskov** [comment]
Update: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.60/SmartYouTubeTV_Orig_v6.12.60_r.apk

**Comment by jackiehhop** [comment]
Working excellent

**Comment by jackiehhop** [comment]
hi friend configuration icons it would be nice to leave them in one only as settings, Icon menu

**Comment by yuliskov** [comment]
> the configuration icons would be nice to leave them in one only as configurations, Icon menu

Hi, you mean to move this setting to another place? I don't get it.

**Comment by jackiehhop** [comment]
if you place the settings maybe in a spinner within the same initial menu
example
https://stackoverflow.com/questions/26755878/how-can-i-fix-the-spinner-style-for-android-4-x-placed-on-top-of-the-toolbar

it's an idea, thanks, friend
