### ISSUE TITLE
Change the package name

### ISSUE THREAD

**Issue by jemerocay** [yuliskov/SmartYouTubeTV#393]
I have a launcher app that launches com.google.android.youtube.tv.

This app doesn't work anymore on my custom launch app. I want to change the smartyoutubetv package name to com.google.android.youtube.tv to launch smartyoutubetv instead of the old youtube app.

any advise?

**Comment by yuliskov** [comment]
Install regular Smart YouTube TV apk.
Plus install bridge apk: https://github.com/yuliskov/SmartYouTubeTV/releases/download/stable/ATV_SYTV_Bridge.apk

**Comment by jemerocay** [comment]
Thanks a lot Yuliskov. This  solution worked for me.
