### ISSUE TITLE
Bad performance compared to official app

### ISSUE THREAD

**Issue by larvata** [yuliskov/SmartYouTubeTV#4]
Hi, I'm running the app on my minix NEO U1.
An HD video won't be played smooth on my device, and sometimes audio goes out of sync. 

I have noticed the CPU usage is higher than the official one.

Smart YouTube TV 6.5.1
![image](https://cloud.githubusercontent.com/assets/1443833/22860696/c423954a-f140-11e6-8edb-65aad696982c.png)

com.google.android.youtube.tv 1.3.11
![image](https://cloud.githubusercontent.com/assets/1443833/22860717/486a7c42-f141-11e6-9055-8748c726835b.png)

**Comment by yuliskov** [comment]
What app do you use to measure CPU performance? Does beta version have the same performance issue? Link below. Also if you don't mind, post "Stats for nerds" from both versions.
https://play.google.com/store/apps/details?id=com.firsthash.smartyoutubetv2.beta

**Comment by larvata** [comment]
It is the "Show CPU usage" option in the Developer options.

Most of the videos can not be played in the beta version.
Some stuck on a black screen with the "Loading..." text; some stuck on the first frame of the video.

Here is a log and a screenshot of the video stuck on the black screen:
![image](https://cloud.githubusercontent.com/assets/1443833/22862685/6f4e3d4e-f16e-11e6-90ec-f729e444d299.png)
<details>
<summary>
log of beta version (click to expand)
</summary>
<p>
02-12 21:56:23.762: D/PushDaemon(4963): get master[com.ktcp.video:push] now!! pid:4920
02-12 21:56:23.762: D/PushDaemon(4963): master [com.ktcp.video:push] [4920] is running, skip startService
02-12 21:56:25.488: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:25.549: W/cr_BindingManager(5817): Cannot call determinedVisibility() - never saw a connection for the pid: 5817
02-12 21:56:25.552: I/com.liskovsoft.browser.Tab(5817): 2017-02-12 21:56:25.551 org.slf4j.impl.AndroidLoggerAdapter#log:63
02-12 21:56:25.552: I/com.liskovsoft.browser.Tab(5817):  logPageFinishedLoading: 
02-12 21:56:25.593: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:25.617: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:25.667: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:25.677: I/chromium(5817): [INFO:CONSOLE(143)] "fixOverlappedTextInRussian", source:  (143)
02-12 21:56:25.710: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:26.064: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:26.070: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:26.077: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:26.169: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:26.292: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:26.300: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:27.021: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:27.392: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:27.395: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:27.405: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:27.410: I/MediaFocusControl(3184):  AudioFocus  requestAudioFocus() from android.media.AudioManager@2e7e82b2org.chromium.content.browser.MediaSessionDelegate@67b4d46 req=1flags=0x0
02-12 21:56:27.436: I/OMXClient(5817): Using client-side OMX mux.
02-12 21:56:27.439: E/ACodec(5817): Unable to instantiate a decoder for type 'audio/opus'.
02-12 21:56:27.439: E/ACodec(5817): signalError(omxError 0x80001003, internalError -2147483648)
02-12 21:56:27.440: E/MediaCodec(5817): Codec reported err 0xfffffffe, actionCode 0, while in state 1
02-12 21:56:27.440: W/MediaCodec-JNI(5817): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
02-12 21:56:27.440: W/MediaCodec-JNI(5817): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): Failed to create MediaCodec: audio/opus, isSecure: false, requireSoftwareCodec: no
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at android.media.MediaCodec.native_setup(Native Method)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at android.media.MediaCodec.<init>(MediaCodec.java:486)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at android.media.MediaCodec.createDecoderByType(MediaCodec.java:444)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at org.chromium.media.MediaCodecUtil.createDecoder(MediaCodecUtil.java:217)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at org.chromium.media.MediaCodecBridge.create(MediaCodecBridge.java:214)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at android.os.Looper.loop(Looper.java:135)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at android.app.ActivityThread.main(ActivityThread.java:5257)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at java.lang.reflect.Method.invoke(Native Method)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at java.lang.reflect.Method.invoke(Method.java:372)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
02-12 21:56:27.441: E/cr_MediaCodecUtil(5817): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
02-12 21:56:27.444: I/OMXClient(5817): Using client-side OMX mux.
02-12 21:56:27.466: I/CodecLooper(7162): type=1400 audit(0.0:17): avc: denied { read write } for name="amvenc_avc" dev="tmpfs" ino=9946 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:video_device:s0 tclass=chr_file permissive=1
02-12 21:56:27.466: I/CodecLooper(7162): type=1400 audit(0.0:18): avc: denied { open } for path="/dev/amvenc_avc" dev="tmpfs" ino=9946 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:video_device:s0 tclass=chr_file permissive=1
02-12 21:56:27.474: I/omx_core(5817): OMX_Init 66 gInitCount=1
02-12 21:56:27.474: V/AML_all_components(5817): --------------------------------
02-12 21:56:27.474: V/AML_all_components(5817): ARCH = arm
02-12 21:56:27.474: V/AML_all_components(5817): author:aml.sh multi-media team
02-12 21:56:27.474: V/AML_all_components(5817): branch name:   * jb-mr1-amlogic
02-12 21:56:27.474: V/AML_all_components(5817): git version:   011dae5a4bcb3e3676f392664ac0bf74db6cca1b 
02-12 21:56:27.474: V/AML_all_components(5817): last changed:  Date: Sun Dec 27 20:57:19 2015 +0800
02-12 21:56:27.474: V/AML_all_components(5817): build-time:     Thu Jan 7 14:47:14 CST 2016
02-12 21:56:27.474: V/AML_all_components(5817): build-name:     jintao.xu
02-12 21:56:27.474: V/AML_all_components(5817): uncommitted-file-num:0
02-12 21:56:27.474: V/AML_all_components(5817): cd /mnt/fileroot/jintao.xu/5.1.p201
02-12 21:56:27.474: V/AML_all_components(5817): hostname droid07
02-12 21:56:27.474: V/AML_all_components(5817): --------------------------------
02-12 21:56:27.474: V/OmxComponentManagerImpl(5817): loadLibrary:228 Loading OMX library libOmxVideo.so.
02-12 21:56:27.526: I/CodecLooper(7162): type=1400 audit(0.0:19): avc: denied { ioctl } for path="/dev/amvenc_avc" dev="tmpfs" ino=9946 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:video_device:s0 tclass=chr_file permissive=1
02-12 21:56:27.539: D/omx_video(5817): get avc encode max instance number: 1
02-12 21:56:27.581: I/omx_core(5817): Core library has 11 components
02-12 21:56:27.581: E/OMXMaster(5817): A component of name 'OMX.google.h264.decoder' already exists, ignoring this one.
02-12 21:56:27.581: E/OMXMaster(5817): A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
02-12 21:56:27.591: E/OMXNodeInstance(5817): setParameter(1:google.vp9.decoder, ??(0x6f60000b)) ERROR: UnsupportedIndex(0x8000101a)
02-12 21:56:27.591: W/OMXNodeInstance(5817): [1:google.vp9.decoder] component does not support metadata mode; using fallback
02-12 21:56:27.591: E/ACodec(5817): [OMX.google.vp9.decoder] storeMetaDataInBuffers failed w/ err -1010
02-12 21:56:27.591: E/OMXNodeInstance(5817): getParameter(1:google.vp9.decoder, ParamVideoAndroidVp8Encoder(0x6f600007)) ERROR: UnsupportedIndex(0x8000101a)
02-12 21:56:27.608: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:27.651: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:27.744: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:27.922: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:28.076: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:28.281: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:28.500: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:28.759: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:28.912: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:29.102: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:29.318: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
02-12 21:56:29.505: E/ActivityThread(5817): Failed to find provider info for com.liskovsoft.browser
</p>
</details>

----

Smart YouTube TV 6.5.1, stats for nerds
![image](https://cloud.githubusercontent.com/assets/1443833/22862691/9d3ec9bc-f16e-11e6-8360-0ace9e918a14.png)

----

Android version of my device: 5.1.1

**Comment by yuliskov** [comment]
I guess that I found why. Your device suddenly switched to vp9 codec.  By default must be avc.
Here. Try this versions with forced (I hope) avc codec. Apks signed with debug signature so you have to remove previous versions before install. After that post "Stats for nerds".
Original: https://drive.google.com/uc?id=0ByORA7yiJiQXcEN1UGxpS1VUR0E
Beta: https://drive.google.com/uc?id=0ByORA7yiJiQXRXNfak1fM0g3QXc

**Comment by larvata** [comment]
Original:
![image](https://cloud.githubusercontent.com/assets/1443833/22863077/087b4ac4-f175-11e6-8c3b-9fcf70786086.png)

Beta:
![image](https://cloud.githubusercontent.com/assets/1443833/22863078/1205ad14-f175-11e6-9105-ef3218468589.png)

Both versions are works well, thank you!

**Comment by yuliskov** [comment]
Can you give me your device model as seen in Android Settings > About box > Model number? I consider to add it to codec fix list.

**Comment by larvata** [comment]
@yuliskov It's "NEO-U1"

**Comment by yuliskov** [comment]
Thanks. In a couple of hours both apps will be updated on Google Play.

**Comment by devslava** [comment]
@yuliskov You should consider disabling VP9 for all devices. Most devices support VP9 only as software decoding. It is a result of high CPU usage and video glitches.
By the way, NEO U1 is one of the high-end TV boxes, so if it can't handle it well...

**Comment by francescosoft** [comment]
Hello. I have the same on K1 plus. Very high CPU usage and glitches in playback. For 3 Weeks it was ok. Can you put an option for disableing VP9 so i can test if thats the Problem ?

**Comment by yuliskov** [comment]
@francescosoft I already did it. Both versions now have VP9 disabled by default. Could you check last version please?

**Comment by francescosoft** [comment]
@yuliskov thanks. I checked but it didn't get better. As far as i remember 6.4.5 was ok for me, but i'm not sure. The version from 3-4 weeks ago was for sure ok. How can i find the Problem ?

**Comment by yuliskov** [comment]
@francescosoft please post video info ("Stats for nerds") for both version. 
Also exact name of your device would be great: Android Settings > About box > Model number 
Thanks.

**Comment by devslava** [comment]
Hi.
I have KI plus box too. 
Video smoothness is really not so perfect as in official client, but not so bad in my opinion.
Maybe, it is because of higher resolution.
Model Number is "KI PLUS".
Stats:
![image](https://cloud.githubusercontent.com/assets/8116529/22893279/eb60b362-f21d-11e6-9d84-2aac204910ed.png)

**Comment by francescosoft** [comment]
Hello @yuliskov. Sorry for my late reply. My box is "K! PLUS". Attached you can find the stats for nerds.
![20170214_093242](https://cloud.githubusercontent.com/assets/5352425/23013059/c6bb62c6-f431-11e6-884d-8ee7a7e0d340.jpg)
![20170214_093250](https://cloud.githubusercontent.com/assets/5352425/23013058/c6b9774a-f431-11e6-885f-f60c4a44bbdf.jpg)
![20170214_093257](https://cloud.githubusercontent.com/assets/5352425/23013057/c6b90760-f431-11e6-985a-5b1817e26f46.jpg)
I hope we can find the problem, because your app is very nice :)

**Comment by devslava** [comment]
Seems that official app just follows dimentions( video size is 1280x720 )

**Comment by francescosoft** [comment]
What can i do to have a smooth playback ?

**Comment by timmyvo** [comment]
This app getting lag when playing. The audio goes faster than the video, it does not match each other. I use this app on xiaomi mibox Gen 3c. I hope that you will fix this soon. My device run Android 5.0.

**Comment by yuliskov** [comment]
Try lower resolution.

**Comment by timmyvo** [comment]
The quality of the video is the best part for enjoy, Can you fix this issue instead of ask for lower resolution. I do not set for the 1080p resolution, I set it by default but also getting lag. I really like your app because it can support to sign in without google play services and it can help a lot users can enjoy youtube. So please support for this issue.

**Comment by yuliskov** [comment]
I attempted to fix performance issues in Beta version. Have you tried it?
https://play.google.com/store/apps/details?id=com.firsthash.smartyoutubetv2.beta

**Comment by greystashh** [comment]
Is it possible to enable 50/60 fps playback?

**Comment by yuliskov** [comment]
60 fps playback enabled in last version.
