### ISSUE TITLE
Apkmirror

### ISSUE THREAD

**Issue by darren3** [yuliskov/SmartYouTubeTV#40]
Is there any chance you could upload updates to Apkmirror? Then I can use APKupdater to keep up to date.

**Comment by yuliskov** [comment]
@darren3 filled out a form on its site. We'll see.

**Comment by darren3** [comment]
Great, fingers crossed. Thanks.

**Comment by yuliskov** [comment]
No news. Still no response.

**Comment by yuliskov** [comment]
Closed since no feedback from the Apkmirror's site
