### ISSUE TITLE
Video don´t play in lastest Stable Build

### ISSUE THREAD

**Issue by RedTestament** [yuliskov/SmartYouTubeTV#400]
Videos dont play and only Loading screen on Stable build 6.17.274 PRO Main, PRO Main ALT, Lite and Lite Alt. Using an Android Tvbox T96pro

[log.txt](https://github.com/yuliskov/SmartYouTubeTV/files/3992145/log.txt)

**Comment by yuliskov** [comment]
This is the previous stable version. Check that there everything is ok. https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.245/SYTV_Orig_v6.17.245_r.apk

**Comment by yuliskov** [comment]
Pls test this update: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.275/SYTV_Orig_v6.17.275_r.apk

**Comment by scouse1742** [comment]
that last version doesn't work here either i'm using a minix x8-h on probox 2 firmware

**Comment by RedTestament** [comment]
The same problem, here is the new log
[log.txt](https://github.com/yuliskov/SmartYouTubeTV/files/3993242/log.txt)

**Comment by yuliskov** [comment]
Guys, could you confirm that previous stable doesn't work too?

**Comment by xRayDev** [comment]
On two last stable releases black screen and don't play video.
**6.17.245** - last work stable version work on my Xiaomi Mi Box 3 [MIBOX3 (Once)] with profile Lite Main

**Comment by yuliskov** [comment]
OK. I reverted some changes. Video should work right now.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.279/SYTV_Orig_v6.17.279_r.apk

**Comment by scouse1742** [comment]
I can confirm that this last update posted is working on minix x8-h with probox 2 firmware . big thanks to yuliskov and all involved in this brilliant app

**Comment by RedTestament** [comment]
I confirm that now works, only avc codec, on all the launchers, big thanks to Yuliskov for solve this issue.
