### ISSUE TITLE
No ATV Smart YouTube TV Bridge on Mi Box S

### ISSUE THREAD

**Issue by Bonk-Choy** [yuliskov/SmartYouTubeTV#404]
On Mi Box S, the Smart YouTube App doesn't prompt me to install ATV Smart YouTube TV Bridge. Any ideas?

**Comment by yuliskov** [comment]
Supported on devices where origin youtube installed as non-system app.

**Comment by Bonk-Choy** [comment]
Thanks

**Comment by ataroshe** [comment]
Hi, @yuliskov thanks for the above clarification. Just to check - are there any instructions on how to use (install) Bridge correctly?
And if I move the origin YouTube app outside from the system apps with the help of X-Plore?

Best,
Eugene
