### ISSUE TITLE
SYTV 2.17.295 does not open nor play videos and crashes

### ISSUE THREAD

**Issue by foreveryoungforty** [yuliskov/SmartYouTubeTV#409]
Hello, 291 works perfectly, 295 installs , settings work, but when you try to open a video, the usuals load-circle appears and than the app crashes after a few seconds. Until now I always used Pro Main with all earlier versions, and that worked. But not with 295r any more.
Thanks for looking into this bug. Best, Rik

**Comment by yuliskov** [comment]
Hi. Here is the instructions.

How to enable logs.
Start the app. When you'll see spinning circle press BACK key.
You're on launcher select screen. Find there Tweaks button. Press on it.
Dialog popups. Find check box named 'Save log to file' and check it. Path
to logs will be shown after you click on checkbox. Now run app as usual
unitill ads popups agan. When this happens go to path where log stored and
post log file to this chat.

**Comment by foreveryoungforty** [comment]
Hello here's the logfile... hope it unveals the issue. Thank you.
[log.txt](https://github.com/yuliskov/SmartYouTubeTV/files/4007983/log.txt)

Ps. I uninstalled 291 and did a fresh install of 295.

**Comment by yuliskov** [comment]
Oh. I see. Try to uninstall the app and install again.

**Comment by foreveryoungforty** [comment]
295 still gives same problems and does not give upgrade to (beta)299 version.
Can you post the APK from 299 please ? Thanks

**Comment by yuliskov** [comment]
OK.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.299/SYTV_Orig_v6.17.299_r.apk

вс, 29 дек. 2019 г. в 19:00, foreveryoungforty <notifications@github.com>:

**Comment by foreveryoungforty** [comment]
Great... 299 works fine - thank you very much.

**Comment by foreveryoungforty** [comment]
Closed issue
