### ISSUE TITLE
Dutch translation for settings of app

### ISSUE THREAD

**Issue by foreveryoungforty** [yuliskov/SmartYouTubeTV#410]
Hello Yuriy,
If you are interested, I can provide you with the translations in Dutch for the settings of SYTV. Please let me know where I can do so. I searched your app on the Crowdin platform, but did not find it there.  Best, Rik (Belgium)

**Comment by yuliskov** [comment]
Thanks, Rick. I appreciate your willing to help.

**Comment by foreveryoungforty** [comment]
Glad to do so, is there a tool where I can find the English strings, and register the Dutch ones ?

**Comment by yuliskov** [comment]
Check this one. I didn't tested it though.
https://forum.xda-developers.com/showthread.php?t=1666630

**Comment by foreveryoungforty** [comment]
Hello Yuriy, to me in that link , it is totally not clear what/how a translator should do & work to get things done. I do a lot of translations on the Crowdin-platform (and before also in OneSky) and there it is very easy to work and interact regarding translations.
I see in your app that the settings screen is translated in French. Living in Belgium , I also know that language, maybe you can bring me into contact with the french translator how he fixed this, so i can do so in dutch. Hope that can help.

**Comment by yuliskov** [comment]
@foreveryoungforty yup, here is the guy that did a lot of french translation.
https://github.com/yuliskov/SmartYouTubeTV/pull/406

**Comment by foreveryoungforty** [comment]
Hi Yuriy, maybe I found the solution myself. I unzipped the zip-source code of your app, and found a french strings.xml file after some searching. I will translate that file and send that translated xml to you. I think from your side you will have to do some programming in order to make that language to appear in the available choices. Is that ok for you ?

**Comment by yuliskov** [comment]
Sorry, pal. French isn't allowed. I already have the contributor for this language.

**Comment by foreveryoungforty** [comment]
I know, i wont do anything nor change that file, but i will use that file as a basis to make a dutch version of that. Maybe i did not make myself clear.

**Comment by yuliskov** [comment]
Yes, I didn't get you right. OK, then.

**Comment by foreveryoungforty** [comment]
Hello Yuriy,
it took me four hours to check all your folders in your app that contain files that need to be adapted and translated for an implementation of Dutch translation.
Note that I don't use the term Dutch (this is the english term), but "nederlands" or the abbreviation "nl" : this raises/augments the use/recognition for your dutch users, speaking that language.
To be sure of correct translations, I took the original (english) strings as a reference, not the french ones.
I used the the 316-release.

**Comment by foreveryoungforty** [comment]
I see it is not possible to post xml files here - I will send them to you by mail.

I used my Gmail-account to send you the 5 files with dutch strings. I don't know if extra programming is needed from your side or if you only have to add the new folders and respective files under them.
If it is more useful to you, you may always post/send me an apk-file with the new dutch files integrated, so I can test them all the way before general release. See what is best for you.

Best regards , Rik

**Comment by foreveryoungforty** [comment]
Hello Yuriy,
Downloaded 323-version - your implementation of my Dutch translations look great - I tested them for all the direct visible and main functions of your app. 99% correct.
I sent you a mail via Gmail with some small tweaks in my translations to make it 100%. Thanks.
