### ISSUE TITLE
4K on FireTV not working

### ISSUE THREAD

**Issue by Xerxes13** [yuliskov/SmartYouTubeTV#413]
When I try to switch to 3840x2160 vp9 quality I get the error android.media.MediaCodec.error_1100
Tried it with both PRO Launcher, the LITE Launcher crashes after start (both)

Version 6.17.334 with FireTV 4K

**Comment by yuliskov** [comment]
I've tested on Fire Stick. It works flawlessly.

**Comment by Xerxes13** [comment]
I don't have a FireTV Stick (which looks like a big USB Stick), I have a FireTV 4K (which looks like a flat square, see [here](https://www.amazon.de/Fire-Tv-Mit-4K-Ultra-HD-Und-Alexa-Sprachfernbedienung-/dp/B06XTVS1D4)

**Comment by Xerxes13** [comment]
Had a 4K vid today at 24fps (vp9) that worked, but with stutter and a lot of dropped frames.

**Comment by Xerxes13** [comment]
Upgraded to a FireTV Stick 4K, works flawlessly now
