### ISSUE TITLE
No audio for the first ~3 seconds of any video

### ISSUE THREAD

**Issue by icrustandi** [yuliskov/SmartYouTubeTV#427]
On Nvidia Shield - it makes no difference whether I'm playing straight to TV speakers or my soundbar. This problem shows up on both Pro main and Pro alt, but no issues with audio on Lite.

On any video, when it first initially starts, there is not audio for about 3 seconds. After that, everything else works as it should. If I rewind all the way back to the beginning, the audio plays just fine through the end of the video.

**Comment by yuliskov** [comment]
Just disable auto frame rate switching or enable delay.

**Comment by icrustandi** [comment]
Yup - disabling AFR worked. Delay also worked, but prefer to not add a delay. Thanks
