### ISSUE TITLE
What is the package name of the app?

### ISSUE THREAD

**Issue by SocietasEvanescentes** [yuliskov/SmartYouTubeTV#428]
I can't remember if I'm on stable or beta, but I just expanded my FireTV Storage and I'm trying to move all third party apps that aren't amazon to my USB via rm move-package. That being said, I can't seem to find this app when using list packages. 

Thank you 🙂

**Comment by yuliskov** [comment]
com.liskovsoft.videomanager

2020-01-31 2:52 GMT+02:00, Travis M <notifications@github.com>:

**Comment by SocietasEvanescentes** [comment]
Thank you so much for the speed!
