### ISSUE TITLE
Screen issue

### ISSUE THREAD

**Issue by ja-som** [yuliskov/SmartYouTubeTV#437]
Hello,
since yesterday I have this issue:
![Screenshot_20200216-000124](https://user-images.githubusercontent.com/5942380/74596553-2285f980-5051-11ea-8d27-01c6e3c08690.png)

When I start video it is OK, it's like this only in "menu".
I don't think I changed anything yesterday or day before. I also tried to delete data for app.
App version: 6.17.371 Pro main
Device info: Nvidia Shield TV (2019), Android 9, Shield TV 8.1.0 (32.7.301.32)

**Comment by fgl27** [comment]
Don't use webview beta.

**Comment by ja-som** [comment]
Thank you @fgl27 it fixed it.

**Comment by SpeedForceGN** [comment]
I am having the same issue and mine is set for 1080 Main
![20200217_045852](https://user-images.githubusercontent.com/61169069/74693260-02714a00-51b9-11ea-92ae-
![20200217_045908](https://user-images.githubusercontent.com/61169069/74693266-0a30ee80-51b9-11ea-9fcf-cd4030426a82.jpg)
1b64e09d60be.jpg)

**Comment by fgl27** [comment]
don't you see the solution? @SpeedForceGN

**Comment by SpeedForceGN** [comment]
> Hello,
> since yesterday I have this issue:
> ![Screenshot_20200216-000124](https://user-images.githubusercontent.com/5942380/74596553-2285f980-5051-11ea-8d27-01c6e3c08690.png)
> 
> When I start video it is OK, it's like this only in "menu".
> I don't think I changed anything yesterday or day before. I also tried to delete data for app.
> App version: 6.17.371 Pro main
> Device info: Nvidia Shield TV (2019), Android 9, Shield TV 8.1.0 (32.7.301.32)

How do you know if you are using webview beta or not?

> don't you see the solution? @SpeedForceGN

No, any suggestions?

**Comment by fgl27** [comment]
Google it

**Comment by SpeedForceGN** [comment]
> Google it

What? Webview beta...  what is the purpose of asking questions here in this forum.

**Comment by ja-som** [comment]
@SpeedForceGN  go here
https://play.google.com/apps/testing/com.google.android.webview
If you have option to leave the beta, then do it.
Then open the Play Store app on your TV, find Android Webview and uninstall, (it will revert it to your stock version)

**Comment by yuliskov** [comment]
Guys, simply switch to the Pro Alt.
It should do the trick.

Regards, Yuriy

**Comment by fgl27** [comment]
> > Google it
> 
> What? Webview beta... what is the purpose of asking questions here in this forum.

this is not a forum little buddy, sorry if I mistreated you, but have you even tried? really you didn't even try to find the answer for yourself, why would I do it for you then?

You aren't in the right place if you can't even help yourself with a simple search (on my point of view) after all something like that doesn't get enable by it self you must accept the beta, somehow you did, if you did you must be able to undo...
