### ISSUE TITLE
Stop Auto-Updater?

### ISSUE THREAD

**Issue by rainman74** [yuliskov/SmartYouTubeTV#45]
Hi, is it possible to stop auto-updater with an option/setting?

You make an update almost every 5 hours and you have to select the dialog at every restart. ;-)

**Comment by yuliskov** [comment]
@rainman74 don't promise to fully disable updates (its by design). But there may be some changes in the update behavior. E.g. when you press cancel, update is postproned for a week or so.

**Comment by yuliskov** [comment]
OK. I've changed my mind. Update Check checkbox has been added.

**Comment by rainman74** [comment]
Thank you 👍
