### ISSUE TITLE
Unusually large text size on 6.17.404

### ISSUE THREAD

**Issue by aecarvalho** [yuliskov/SmartYouTubeTV#454]
Everything else works fine besides the text size of the title, play, pause, options button texts, etc. which are unusually large and overlapping at times, even the padding is a bit extra, hope it's fixed in the next update
![IMG_20200309_140934](https://user-images.githubusercontent.com/60945000/76196105-a629a500-620f-11ea-903c-9c24ba153d51.jpg)

**Comment by yuliskov** [comment]
I need your device dpi. Install aida.

Regards, Yuriy

**Comment by aecarvalho** [comment]
xdpi/ydpi = 36/37 DPI
It's an MI TV 4A (40) using 1280×720

**Comment by yuliskov** [comment]
Hi. Thanks for the info.
Please install new version (link below). I've improved debug info in a bit. Then go to the app version page and get the screen from there (example below).
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.405/SYTV_Orig_v6.17.405_r.apk
![screen](https://user-images.githubusercontent.com/5897464/76239407-2e24a480-623a-11ea-81e1-cd8aae47007e.png)

**Comment by aecarvalho** [comment]
For me this build also has the same enlarged icons and texts like I sent earlier, but anyway here's what you asked for
![Screenshot_20200310-002453](https://user-images.githubusercontent.com/60945000/76247729-077c6300-6266-11ea-87e4-89ed7988d704.png)

Also a big thanks for being so quick to help

**Comment by yuliskov** [comment]
May I ask you for the log from the last build? It could be enabled via the
settings dialog on the sytv boot screen. Such setting item is called "Save
log to file".

Regards, Yuriy

**Comment by aecarvalho** [comment]
Yes of course, attached the log as well as the screenshots of the earlier requested picture as well as a better look at the issue, the app version information got updated after I restarted the app
![Screenshot_20200310-013013](https://user-images.githubusercontent.com/60945000/76252966-c2f5c500-626f-11ea-9ff1-5c75bc3dde11.png)
![Screenshot_20200310-013511](https://user-images.githubusercontent.com/60945000/76252973-c7ba7900-626f-11ea-9b59-f1e4edb794f2.png)
[log.txt](https://github.com/yuliskov/SmartYouTubeTV/files/4308714/log.txt)

**Comment by yuliskov** [comment]
OK. I tried to fix the issue in this build.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.406/SYTV_Orig_v6.17.406_r.apk

**Comment by aecarvalho** [comment]
It has been fixed! Thank you so much for your promptness and continued support :)

**Comment by yuliskov** [comment]
You're welcome!
What about playback?
Is it working again?
Regards, Yuriy

**Comment by aecarvalho** [comment]
Yes playback is working smoothly, sorry for reverting late

**Comment by yuliskov** [comment]
Thanks, friend!

Regards, Yuriy
