### ISSUE TITLE
[Fire TV 4K] Adverts

### ISSUE THREAD

**Issue by stezo2k** [yuliskov/SmartYouTubeTV#464]
Seem to be getting more and more adverts lately. Is this normal or do I have to downgrade?

**Comment by yuliskov** [comment]
The same as always, my friend. But to you need to confirm your intention on
first app boot.

ср, 18 мар. 2020 г. в 13:04, stezo2k <notifications@github.com>:

**Comment by stezo2k** [comment]
Thank you so much. I had no idea it had changed

**Comment by aecarvalho** [comment]
Even I got an advertisement today, thought I might inform you, it's an android TV though, MI 4A (40), running on 4.17.425, ad block is enabled in the settings on start up
I've attached the screenshot herewith
![Screenshot_20200319-154202](https://user-images.githubusercontent.com/60945000/77085226-0c8ba000-6a26-11ea-92e4-e3c67ded3156.png)

**Comment by stezo2k** [comment]
I don't mind the odd page ad. It's the video ones which are annoying. I'm just glad I can turn them off now :) thank you for a great app. I use it all the time
