### ISSUE TITLE
[AFR FireTV stick 4k] Display mode switching is messed up resulting in choppy video playback

### ISSUE THREAD

**Issue by anshul1886** [yuliskov/SmartYouTubeTV#468]
this issue started around a week back. Some 30/25 fps videos are switching to 60/50 display mode which is good. But some 24 fps videos are stuck at 24 and not switching  to 48. Also some 25/30 fps videos whose resolution is greater than 1980 they are also stuck at 25/30 and not switching display to 50/60. This is resulting in very choppy video playback. If I am switching off AFR then also videos seems choppy.

AFR should be enabled first.

Example videos where choppy playback:
https://www.youtube.com/watch?v=ZKbydYg8R-E
https://www.youtube.com/watch?v=h1KUA4GSilU

**Comment by yuliskov** [comment]
I'll check. Thx

Regards, Yuriy

**Comment by yuliskov** [comment]
Pls test: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.433/SYTV_Orig_v6.17.433_r.apk

**Comment by anshul1886** [comment]
Its working now for 25 and 30 fps videos but not for 24 fps videos. 24 fps video is  still switching display to 24. thanks

**Comment by anshul1886** [comment]
Here issue seems to be different than display mode switching. Amazon prime video's  24 fps looks smooth but youtube's 24 fps looks choppy. It seems display mode is switching properly. In case of YouTube it looks like frames are dropped. It looks like 24 fps is converted to 60 fps video and from that only 24 frames are shown and rest are dropped.

**Comment by yuliskov** [comment]
How to test? Give me the name of the video.

Regards, Yuriy

**Comment by anshul1886** [comment]
We can test on any 24 fps video. one such video https://www.youtube.com/watch?v=ZKbydYg8R-E

**Comment by anshul1886** [comment]
Also there is one more observation that tv signal is not switching to HDR for HDR video. Previously it was working fine. But I haven't played any HDR video recently so not sure since when this started happening.

**Comment by anshul1886** [comment]
this seems working fine now. Looks like it was due to amazon exoplayer version.
