### ISSUE TITLE
changing resolution error

### ISSUE THREAD

**Issue by yfive5** [yuliskov/SmartYouTubeTV#47]
Error ID: 63-s-aeV_yTvNLQS after changing resolution from 1080 to 720 on Amazon FireTV Stick because of lacks while connected to Resurrection Remix Nougat Android-7.1.2_r36 - NJH47F

**Comment by yuliskov** [comment]
@yfive5 thx, but info you just proveded isn't helpful for me. I need more. Maybe video or something.

**Comment by yuliskov** [comment]
not enough info
