### ISSUE TITLE
New open-function/screen in 463/464

### ISSUE THREAD

**Issue by foreveryoungforty** [yuliskov/SmartYouTubeTV#478]
Hello Yuriy,
Again a great new feature "open" to go to another player, although I am perfectly satisfied with the high quality SYTV renders...., but it has some UI-issue with the screen that pops up after you push "open".

A large part of the pop-up screen is below the bottom of the TV-screen, so you only see the latest-used player on top, and the first other choice. The 2nd is already half-hidden , and with me there is also VLC Player and the standard Video-Movies app built-in from Sony below. The pop-up does not move together with scolling down, so you have to "guess" what is there and what you will choose....
see screen-shot.   Thanks a lot for looking into this. Best, Rik
![20200330_174505](https://user-images.githubusercontent.com/59088697/77934456-6571f880-72b0-11ea-8609-8ba5958406a0.jpg)

**Comment by yuliskov** [comment]
This is a system popup. I can't control it.

Regards, Yuriy

**Comment by foreveryoungforty** [comment]
Ah ok, thanks for your reply.
