### ISSUE TITLE
Cannot load TV adapted interface

### ISSUE THREAD

**Issue by TheUserDead** [yuliskov/SmartYouTubeTV#48]
Hello, thanks for great work.
I have problem from **.27 > **.30 versions.
I have alternative launcher on my mxq s905 (pro 4k) tv box
When i call your app directly from launcher, i have no errors, but if i use my own launcher first time tvbox ask me for youtube default app (SmartYouTubeTV or Browser)
I choose your app and click (always), after that i see menu about youtube version and when i choose any of that i see loading circle and error (baloon message) 
"URL not supported https://www.youtube.com/?glRU&hl-ru"
before **.27 version, i have no errors.
When i see that message, i see web based standard youtube interface and can't quit from app (quit dialog no provided) only home button helps.
If i use other launcher, all works good.
You can say (use your standart launcher) but i need call your app from another launcher (just another app) can you help me?

**Comment by yuliskov** [comment]
@TheUserDead thanks for the bugreport. It would be good to try that launcher by myself. Is it working on other devices?

**Comment by TheUserDead** [comment]
No and i know why...
The problem is somewhere between applications. Rather, the methods of calling the application. Recall, I initially choose smartyoutubetv as the default youtube application. 
I understood! Their application is more likely to pass this link (https://www.youtube.com?bal bla bla) 
 to your application, and yours just writes "url is not supported" and opens a page instead of a special version of youtube for tvbox
I'm sorry to trouble you.
The situation is that the player that I use is being sold by the Internet provider to which I am connected. They have their own launcher, and they will not provide it separately. I wrote to them about the problem, but it seems to me they did not understand me.
There are two options. Or your application will ignore the passed parameters and open as needed or ask them to do it that is more logical.

**Comment by yuliskov** [comment]
@TheUserDead thanks. I think, you've provided enough info to fix this issue. I'll try to deal with it.

**Comment by yuliskov** [comment]
@TheUserDead possible fix here: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.35/SmartYouTubeTV_Orig_v6.12.35_r.apk

**Comment by TheUserDead** [comment]
Thanks, i i'll try install fixed version, but see error message again and just white screen.

**Comment by TheUserDead** [comment]
I sent more info to launcher developer (what i understand, about sended params)
I think, you no need to worry.
Thanks for your work!

**Comment by TheUserDead** [comment]
So many thanks for you. I don't know you made something or no, but your app opens correctly.
Have a nice coding!
