### ISSUE TITLE
Any chance or possibility of integrating SponsorBlock into the app?

### ISSUE THREAD

**Issue by SocietasEvanescentes** [yuliskov/SmartYouTubeTV#483]
This was last mention here: https://github.com/yuliskov/SmartYouTubeTV/issues/314 but has never had a response from the dev. I imagine they're busy, but I would love to see this added to the app as I find Kodi clunky

**Comment by yuliskov** [comment]
I've no plans for this. Sorry, pal.

Regards, Yuriy
