### ISSUE TITLE
Preview/Thumbnails in videos

### ISSUE THREAD

**Issue by Xerxes13** [yuliskov/SmartYouTubeTV#485]
Since the last 2 (maybe 3?) updates I didn't have any preview tiles when forwarding through a video (to go to a given timestamp)

Using the latest stable version: 6.17.475
Device: FireTV Stick 4K

Thanks for the awesome work.

**Comment by yuliskov** [comment]
On my stick everything is fine. I'm using Pro launcher.

Regards, Yuriy

**Comment by Xerxes13** [comment]
Okay, I did some testing. It definitely has something to do with the sign in.

Using the app as guest (no signin): thumbnails work
Using the app signed in with Google Account: thumbnails don't work
Using the app as guest while signed in with Google Account: thumbnails don't work

How is this possible?
Edit: all tests with same settings, Pro Main

**Comment by yuliskov** [comment]
I've no clue.

Regards, Yuriy

**Comment by thugdang** [comment]
preview thumbnail doesn't work for me at all

**Comment by Xerxes13** [comment]
I tried with an 2nd Google Account and with the official YT App on my SmartTV, the thumbnails works, so it must have something to do with my own Google Account.
I contacted the YouTube support, its not a problem of the app. Sorry for that.
