### ISSUE TITLE
Program upgrade exit 

### ISSUE THREAD

**Issue by xiaoxihu2017** [yuliskov/SmartYouTubeTV#49]
Please watch the video
https://youtu.be/nkVauSORaTE

**Comment by yuliskov** [comment]
@xiaoxihu2017 could you confirm that bug still exists on the build provided below?
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.33/SmartYouTubeTV_Orig_v6.12.33_r.apk

**Comment by xiaoxihu2017** [comment]
6.12.35 ，6.12.36upgrade6/12/37 exit

**Comment by yuliskov** [comment]
@xiaoxihu2017 Hi. I've changed update mechanism. Could you check provided app? It should ask you for update right after run of any version.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.35/SmartYouTubeTV_Orig_v6.12.35_r.apk

**Comment by xiaoxihu2017** [comment]
Install 6.12.15 exit,
See video https://www.youtube.com/watch?v=zJRXBPFbRkk

**Comment by yuliskov** [comment]
@xiaoxihu2017 thanks for the video. I've added crash logging. Please, install this apk and record video again.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.35/SmartYouTubeTV_Orig_v6.12.35_r.apk

**Comment by xiaoxihu2017** [comment]
See video https://www.youtube.com/watch?v=1Vl_cvAKz4M

**Comment by yuliskov** [comment]
@xiaoxihu2017 first, let me thank you for the feedback. It's very helpful. I prepared next update based on the info from the video.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.35/SmartYouTubeTV_Orig_v6.12.35_r.apk

**Comment by WolfganP** [comment]
I'm also having issues with auto upgrading. My installation got stuck in v6.12.37 (that currently is not listed in https://github.com/yuliskov/SmartYouTubeTV/releases), when the latest version as of today is 6.12.40
Going to the initial screen with ESC, I confirmed Auto Update is ticked but no new version is auto detected at program start. Is it possible to add a Force Update button to avoid having to sideload if no new version is detected in the upcoming days?
Thanks!

**Comment by yuliskov** [comment]
@WolfganP technically, 37 build is the latest one for auto-update. I've not added new builds becase I need to get some feedback first. There is possibilty that new builds come with some regression.

**Comment by yuliskov** [comment]
Seems fixed
