### ISSUE TITLE
6.17.504 causes playback glitch

### ISSUE THREAD

**Issue by aecarvalho** [yuliskov/SmartYouTubeTV#498]
There was no problem yesterday but today as soon as I tried to play a video, the audio plays but with the video stuck on the first frame, it could be corrected by exiting the video twice to get back to the playlist then reopening the video, after which it plays well. Sorry I forgot the log because I then uninstalled it and reinstalled 6.17.482 which works well.

**Comment by yuliskov** [comment]
Hi. Is it happen on Lite or Pro version?

Regards, Yuriy

**Comment by aecarvalho** [comment]
Pro version, ad block and minimum buffer was enabled
