### ISSUE TITLE
60 fps playback

### ISSUE THREAD

**Issue by greystashh** [yuliskov/SmartYouTubeTV#5]
Hi,

I'm very pleased to have found this app as alternative for YouTube TV APP. It's much more consumer friendly by enabling to resume videos and disable auto playback. Thats nice. One thing I wonder whether it is possible to play videos in 60 fps? Well, on my device (Wetek Play 2 / Android 5.1) the YouTube TV app doesnt support that but the normal YouTube app can play 1080p60.

Therefore I am asking myself whether this is possible to integrate in your app?

**Comment by yuliskov** [comment]
@greystashh thanks, I'll try to find a solution

**Comment by greystashh** [comment]
Is it possible to integrate?

**Comment by greystashh** [comment]
Like I have seen that you added 60fps. Unfortunately I cannot select it in the APP. Can you help me?

**Comment by yuliskov** [comment]
Currently isn't working. I'm trying to fix this.

**Comment by yuliskov** [comment]
Hi. This version capable to play 60fps video. Please test.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.32/SmartYouTubeTV_Exoplayer_v6.8.32_r.apk

**Comment by yuliskov** [comment]
Fixed in latest release.
