### ISSUE TITLE
Video closes abruptly on 6.17.535

### ISSUE THREAD

**Issue by aecarvalho** [yuliskov/SmartYouTubeTV#505]
On MI TV 4A (40'), the playing video abruptly closes saying the "video link is broken" if I'm on slow data or if the data suddenly stops. The broadband here isn't very fast and at times if I'm downloading something on my phone then the data speed on the TV decreases a lot, earlier the video used to show buffer symbol but with 6.17.535 the video buffers for a very short while then immediately stops and returns to the video list if net speed is slow. I've attached the log herewith. 

Thank you so much for this app and for resolving all my earlier issues.
https://github.com/aecarvalho/sample/blob/master/log.txt
Sorry I couldn't directly upload text file here hence I uploaded it into my account repository.

**Comment by aecarvalho** [comment]
Regards

**Comment by thanxx** [comment]
+1 Can confirm the same
