### ISSUE TITLE
Image Cut off on Nvidia ShieldTV

### ISSUE THREAD

**Issue by rodalpho** [yuliskov/SmartYouTubeTV#52]
I'm running the app on a Nvidia ShieldTV. I tried all 4 versions; 720p and the first 4k works, 1080p and the second 4k do not work. 

With the 720p version, the image is cut off around the edges. When I go to stats for nerds, it has a weird "viewport" line saying it's running at 1024x576 or 960x540x2, but clearly I'm seeing more of the image than that as only maybe 10-15% is cut off. Is this a bug, or should I be using a different version on the ShieldTV?

The first 4k version seems to work, but switches resolutions and is missing a bunch of features like recommended videos.

**Comment by yuliskov** [comment]
@rodalpho interface was changed many times. There is possibility that you're using old build or something like this. Post a screenshots and then I can talk more specifically.

**Comment by rodalpho** [comment]
The app autoupdates and autoupdated when I installed it, so it should be the newest version. I just tried and was unable to recreate the cut-off sides-- if it happens again I'll take a screenshot.

Which version _should_ I be using on a ShieldTV?

**Comment by yuliskov** [comment]
> Does the "960x540*2 viewport" thing mean I'm watching downscaled video, or am I seeing the full 1080p resolution
It's ok, no downscale. Despite of this, I decided to change this behavior. Below you can find the test-build. https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.45_2/SmartYouTubeTV_Orig_v6.12.45_r.apk

**Comment by rodalpho** [comment]
Thanks, seems to work fine. I'm using the 720p "version" and it says viewport is 1920x1080*2 now.
