### ISSUE TITLE
Unable to instantiate decoder OMX.amlogic.avc.decoder.awesome

### ISSUE THREAD

**Issue by SECURIOlab** [yuliskov/SmartYouTubeTV#53]
Many videos are starts with shis error on buble. After more restarts same video it works so why not works immediatelly  for first time ?
I tryes it on many Amlogic devices S905X and S912 Android 6.0.1, 7.1.1, 7.1.2 all have same issue in about half of videos. I have also boxes patched as MIBOX to watch 4K videos, but the issue with error in bubble  is same.
Please provide solution how to fix it. Thank you.
![smart youtube not awesome](https://user-images.githubusercontent.com/15924305/34902832-93cdf6e6-f81b-11e7-8ff4-0af95659d109.jpg)

**Comment by SECURIOlab** [comment]
same bubble on this version from previous issue post: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.41/SmartYouTubeTV_Orig_v6.12.41_r.apk
But now the video starts correct, before in ver. 6.12.40 it was just black screen.
Can you fix the buuble ?

**Comment by yuliskov** [comment]
@SECURIOlab please tell me, is this problem exists on the next build
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.36/SmartYouTubeTV_Orig_v6.12.36_r.apk

**Comment by SECURIOlab** [comment]
still same bubble but now every video starts well, so thank you
After detele all app data I use 4K: MiTV and legacy as before and still same bubble, but every video starts well. My Android version is 7.1.1 NMF26Q kernel 3.14.29 for Amlogic S912, S905X same

**Comment by yuliskov** [comment]
@SECURIOlab please, try that old builds. This could help to identify a problem witn false warnings.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.36/SmartYouTubeTV_Orig_v6.12.36_r.apk
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.35/SmartYouTubeTV_Orig_v6.12.35_r.apk
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.33/SmartYouTubeTV_Orig_v6.12.33_r.apk

**Comment by SECURIOlab** [comment]
tried all three versions from your links and everyone has the exactly same bubble as you see on picture.

Every version has also another issue: if press back button during playing some video, there is long time black screen with white mouse cursor until it shows home list with videos. Sometimes I need to push back button twice to come back to list of videos. Your newest ver 6.12.42_r is better in this but original YouTube app 2.02.08 has not so long processing.

**Comment by yuliskov** [comment]
@SECURIOlab hi. I need to know, is there any regression on the latest version compared to the previous one (6.12.42)?
https://github.com/yuliskov/SmartYouTubeTV/releases/tag/6.12.43

**Comment by SECURIOlab** [comment]
no it isn't. as I described, it's exactly same bubble in same situations, but previous versions 33,34,35 doesn't start video, just black screen. Versions 42 and 43 starts videos good even the bubble. I suspect if the bubble isn't some system popup, not your application.

**Comment by SECURIOlab** [comment]
I'm get it back: 43 version can't start some videos with OMX... bubble. Just black screen and sometimes app crash.

**Comment by yuliskov** [comment]
> I suspect if the bubble isn't some system popup, not your application.
Its my popup. I could remove it but it would complicate bugfixing. I think that best is add the checkbox to hide playback errors.

**Comment by yuliskov** [comment]
@SECURIOlab OK. I've reverted player to the 6.12.42 state and added the checkbox to hide errors (in quality menu). Check it out.
https://github.com/yuliskov/SmartYouTubeTV/releases/tag/6.12.44

**Comment by SECURIOlab** [comment]
omx.amlogic.avc... buble is gone in new versions but there is another starting video problem in tested 6.12.79 and few previous same. Many videos start with no sound and blank screen. It happens always when Video quality autochoose video/vp9 . When ai manually switch to video/avc1 it shows and plays good, then I can switch it back to vp9 and everything works fine. But first start is always blank. Now all videos but 80% all videos start with vp9 and they are blank+no sound. Just manually switch to another codec and back starts is correctly. Please solve this issue and reply to me to test it. My device is amlogic S912 with newest Android 7.1.2

**Comment by tschuehly** [comment]
I have the same problem. If I select VP9 it does not play. The Playback State is stuck on Idle. I'm on the newest Fire TV 4K

**Comment by yuliskov** [comment]
Hi all. I've update error behavior. Now app tries to restart such videos. This could help in situation where playback is happened despite of errors.
