### ISSUE TITLE
App (6.17.579) crashes while selecting any video in Pro Main

### ISSUE THREAD

**Issue by stauffenberg2020** [yuliskov/SmartYouTubeTV#537]
Hi, I recently updated the app to 6.17.579. The app crashes whenever I select any video in the Pro Main launcher.

I also tried using an old version of the apk which worked in the past, But this also crashes in the Pro Main mode whenever I click any video

(But it works in the LITE Main though !)

**Comment by stauffenberg2020** [comment]
Hi, I again did a lot of testing. It looks like most of the "Tamil" language videos are not playing (including live streams) in the Pro Main mode. Not sure why. Would be great if this is resolved

**Comment by stauffenberg2020** [comment]
Hi, I did some additional testing. It looks like the videos that I often play are crashing the app in the Pro Main mode. Is there a cap (or has it been introduced lately) of how many times a video can be played in the Pro Main mode?

**Comment by stauffenberg2020** [comment]
Please fined the logfile from my Android. Looks like its missing something in the Pro Main mode. I am not able to understand the log fully, But I am sure the developers can get some info out of it.

05-19 19:40:18.509 28994 29060 D RequestInterceptorProcessor: Intercepting url: https://r1---sn-nuv45-55gl.googlevideo.com/videoplayback?expire=1589931621&ei=BRrEXquLJcSb8gPS1r7oBg&ip=62.107.7.2&id=o-AFiEPAfEy8pRtTtZy_KQSt4ImJ12kat90YbuLJ_uugZa&itag=140&source=youtube&requiressl=yes&mh=6H&mm=31%2C29&mn=sn-nuv45-55gl%2Csn-4g5edns7&ms=au%2Crdu&mv=m&mvi=0&pl=23&initcwndbps=1608750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=3728032&dur=234.684&lmt=1535945257802418&mt=1589909909&fvip=1&keepalive=yes&c=TVHTML5&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgK0emMl7xAq9z1HJFV2P5pR8u3tin5zpyBfWCegwSVLYCIQDupa_LEdrdX6Uqdw7j0zMGFh2M-xn4xkBvcNsKpCp3ow%3D%3D&alr=yes&sig=AOq0QJ8wRQIhAO88K_BMsG-7P9qN__gEhW2cuMPx2JLEc90u3WnpbTchAiA6FRBRKlVsyKlHYHXghcFkVofy8n9zTqF_XWTkcF-BQg%3D%3D&cpn=CJasUAqZQPKyVI6e&cver=6.20180913&range=0-80870&rn=2&rbuf=0
05-19 19:40:18.509 28994 29060 D SmartPreferences: Is app just installed: false
05-19 19:40:18.537 28994 29003 W System  : A resource failed to call end. 
05-19 19:40:18.554 28994 28994 I Tab     : Console: ElementWrapper: IFRAME https://www.youtube.com/s/_/kabuki_legacy/_/js/k=kabuki_legacy.base_zds.en_US.O16BTGA_gU4.O/rt=j/d=1/dg=0/ct=zgms/rs=ANjRhVmr-qgsVn8FthBZFPdAseU5Wd9KpQ/m=base:203
05-19 19:40:18.559 28994 29113 I Tab.WebViewClient: should intercept2? p6@9063909
05-19 19:40:18.559 28994 29113 D RequestInterceptorProcessor: Intercepting url: https://www.youtube.com/get_midroll_info?ei=BRrEXquLJcSb8gPS1r7oBg&m_pos=0&token=ALWClJJtAs-rq4hYPqXhLC0M8npwsQxmBzd8Wmvj7hK1p_0o7tqsB9Wbe70iDm7ezMor4q8UHUHOjJkEuFJsAx3DRSD8pv0vo-9pJrvV84NKLN_Ad_V84vyd9mjsbrUqRU-OwgD_5CrZGwhh-1BI_jBZywh5yDTEyjmlDLxPbkmQlKGoj_RjX5lhjjYdGkQCHTBGI4YaYjXDwucrgnVkg5XP50FH9no6yQHaDoK9Zutka9_yRnfXQ8po8Bs_X9W9dfMNhos9bloAbNyV_gXNzPtIhIYH1wN29IaEoZJBVA00UQ9c9ptBaf8l0NaK_Ery47I5vu8Htgosdtag2h6FrVMh4rifm4Xxzy_YRpn4WOrBgalMsAYOjeHuFqm-kzcPkw2EgUH0H7pT_wnZBVPeoGI048jF2Vjbps8qT5yDDptD7xyjUp3pTX8H6I7vWCeDqXySGw7Qt7QKUo83LVYNfW7tGMC24b3QmHtPmQC-rScK5qhagyAP4AbUMz70RD1S-M3zmygMUzegkpVLDPndjyi1nHuwlSoA4F40wiyVLLpI7behnAoSaWkIp27_1w_PgMd9zGFx10PPGvTmRfTHPtdho4EgdjKnhgeyrW5M2CWOkIYMAAJ1uFoQ7KbNCujyhLrOjOKvF82oAyjKtUVgQ9r008aFW8S10KMIGax_Ktn5kEmHQyNt50EmGeAdxd_WnbyRlZIznEne2JiqD5Pxlto4vpMpvhJvAlQ-DUq50dwHf5QFWtmFHsJ5nHmR-yVx9fLzV-9uMZxNC46RZUoDsRHqBsfs9e61jRa1umLy1OvSMSZyXI759E8tDF9paFuKBy-RwdSNf5avAlVBfXknoB3ch6j5qVxuFdI_MLBLHHGo7EWZ62ck_9C-C7IUlnF_s4SXKY5cwwzZ1lboIo3Cyf0iayfrcgzv1UW9JIu130Sv8DRqtT27uaX9Z5b2troMOrOxtse8uNgSZW2i_i4XewYDq4ZWJOASkyly4fwTn6w9g80cPjDB56HsA9OZNPHTGCAh04wmTj-xEDx6VI0uNNors5-jVJSyxoY8fZ1v2PDn0DTmwV0_hMCaqrhPPoeBRGHUU_N2Eh28&index=0&cpn=CJasUAqZQPKyVI6e&lact=375&ytr&vis=0&ad_block=1&tsla=0&bid=ERR_BID&dt=1589910012836&flash=0&frm=0&ca_type=image&u_tz=120&u_his=5&u_java=false&u_h=540&u_w=960&u_ah=540&u_aw=960&u_cd=24&u_nplug=0&u_nmime=0&p_w=960&p_h=540&c=TVHTML5&cver=6.20180913&m_pos_ms=0
05-19 19:40:18.559 28994 29113 D AdAwayClient: Ads blocked: https://www.youtube.com/get_midroll_info?ei=BRrEXquLJcSb8gPS1r7oBg&m_pos=0&token=ALWClJJtAs-rq4hYPqXhLC0M8npwsQxmBzd8Wmvj7hK1p_0o7tqsB9Wbe70iDm7ezMor4q8UHUHOjJkEuFJsAx3DRSD8pv0vo-9pJrvV84NKLN_Ad_V84vyd9mjsbrUqRU-OwgD_5CrZGwhh-1BI_jBZywh5yDTEyjmlDLxPbkmQlKGoj_RjX5lhjjYdGkQCHTBGI4YaYjXDwucrgnVkg5XP50FH9no6yQHaDoK9Zutka9_yRnfXQ8po8Bs_X9W9dfMNhos9bloAbNyV_gXNzPtIhIYH1wN29IaEoZJBVA00UQ9c9ptBaf8l0NaK_Ery47I5vu8Htgosdtag2h6FrVMh4rifm4Xxzy_YRpn4WOrBgalMsAYOjeHuFqm-kzcPkw2EgUH0H7pT_wnZBVPeoGI048jF2Vjbps8qT5yDDptD7xyjUp3pTX8H6I7vWCeDqXySGw7Qt7QKUo83LVYNfW7tGMC24b3QmHtPmQC-rScK5qhagyAP4AbUMz70RD1S-M3zmygMUzegkpVLDPndjyi1nHuwlSoA4F40wiyVLLpI7behnAoSaWkIp27_1w_PgMd9zGFx10PPGvTmRfTHPtdho4EgdjKnhgeyrW5M2CWOkIYMAAJ1uFoQ7KbNCujyhLrOjOKvF82oAyjKtUVgQ9r008aFW8S10KMIGax_Ktn5kEmHQyNt50EmGeAdxd_WnbyRlZIznEne2JiqD5Pxlto4vpMpvhJvAlQ-DUq50dwHf5QFWtmFHsJ5nHmR-yVx9fLzV-9uMZxNC46RZUoDsRHqBsfs9e61jRa1umLy1OvSMSZyXI759E8tDF9paFuKBy-RwdSNf5avAlVBfXknoB3ch6j5qVxuFdI_MLBLHHGo7EWZ62ck_9C-C7IUlnF_s4SXKY5cwwzZ1lboIo3Cyf0iayfrcgzv1UW9JIu130Sv8DRqtT27uaX9Z5b2troMOrOxtse8uNgSZW2i_i4XewYDq4ZWJOASkyly4fwTn6w9g80cPjDB56HsA9OZNPHTGCAh04wmTj-xEDx6VI0uNNors5-jVJSyxoY8fZ1v2PDn0DTmwV0_hMCaqrhPPoeBRGHUU_N2Eh28&index=0&cpn=CJasUAqZQPKyVI6e&lact=375&ytr&vis=0&ad_block=1&tsla=0&bid=ERR_BID&dt=1589910012836&flash=0&frm=0&ca_type=image&u_tz=120&u_his=5&u_java=false&u_h=540&u_w=960&u_ah=540&u_aw=960&u_cd=24&u_nplug=0&u_nmime=0&p_w=960&p_h=540&c=TVHTML5&cver=6.20180913&m_pos_ms=0
05-19 19:40:18.560 28994 28994 W Tab.WebViewClient: network error: -1
05-19 19:40:18.560 28994 28994 W Tab.WebViewClient: ignore fake errors on Android 7.0
05-19 19:40:18.569  3701  9909 W ActivityManager:   Force finishing activity com.liskovsoft.videomanager/com.liskovsoft.smartyoutubetv.flavors.exoplayer.SmartYouTubeTV4K
05-19 19:40:18.572 28994 28994 D TwoFragmentsManagerActivity: Pausing...
05-19 19:40:18.572 28994 28994 D FragmentManagerActivity: Disabling screensaver...
05-19 19:40:18.572 28994 28994 D AppStateWatcherBase: App pausing... Calling handlers...
05-19 19:40:18.578  3355  3355 E lowmemorykiller: Error opening /dev/memcg/apps/uid_10085/pid_14721/memory.swappiness; errno=2


I am not sure if this lowmemorykiller is something!

Please reach out to me for any further details to debug this issue

[logcat.txt](https://github.com/yuliskov/SmartYouTubeTV/files/4652267/logcat.txt)

**Comment by TalelBM** [comment]
Since the latest update the app crashes randomly

**Comment by icemint-asa** [comment]
I'm having a similar issue.  It has been crashing randomly since update 6.17.519, especially on videos I've viewed previously. Cleared cache and data for the apk but that didn't help at all like in some previous versions. Live videos also have been crashing the apk for the last few updates. Have a decent amount of space left. 

Device: Mibox S (MDZ-22-AB)
Android Version: Android 9 (Build 2604)
Arch:  armeabi-v7a

**Comment by stauffenberg2020** [comment]
6.17.582 fixed only the live streaming in Pro Main. **But still the issue persists for the frequently seen videos**.
