### ISSUE TITLE
Crashes on LeEco TV super4 X40

### ISSUE THREAD

**Issue by pavankumarjs** [yuliskov/SmartYouTubeTV#54]
I have the crosswalk runtime installed.
After I open the app and select 720p or 1080p, it crashes.
Tried with both 32 and 64 bit crosswalk versions.

Can someone help me how to debug so that I can share the crash logs.

**Comment by yuliskov** [comment]
@pavankumarjs please? do the same things (run and select different versions) with the latest release. Logs are submitted automatically.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.42_2/SmartYouTubeTV_Orig_v6.12.42_r.apk

**Comment by pavankumarjs** [comment]
Looks like a false alarm.
It works with 32 bit crosswalk runtime perfectly!
