### ISSUE TITLE
Change default loading/placeholder image

### ISSUE THREAD

**Issue by saalmaan** [yuliskov/SmartYouTubeTV#55]
In an otherwise great app this (see attached) placeholder loading image have started to bother me recently.

Loader/placeholder image suggestions 
1) replace this image with just simple spinning loader on black screen
2) keep video's cover image showing until video starts playing. This is how YouTube app works.

Thanks

![5368268e-8d0b-4c01-af7a-f7374aef0bbe](https://user-images.githubusercontent.com/4620730/34905484-58810642-f851-11e7-9bd7-9228472ec90b.jpeg)

**Comment by yuliskov** [comment]
@saalmaan thanks. I think this will be pretty easy to fix.

**Comment by rodalpho** [comment]
I agree the current image is very low-resolution and ugly. Not a big deal, but it would be nice to use the video thumbnail.

**Comment by yuliskov** [comment]
Placeholder has been changed to the black screen in the latest update
