### ISSUE TITLE
Rewinding or scrubbing a Live Stream no longer works

### ISSUE THREAD

**Issue by thenextmans** [yuliskov/SmartYouTubeTV#566]
For the last few release versions of SmartYoutubeTV, the ability to rewind a live stream is no longer functioning.

Being able to rewind or scrub backwards on a live stream, and then playing it back at variable speeds to "catch-up" to the present moment on a live Youtube stream was one of this apps best features but unfortunately doesn't work at the moment.

Instead of being able to scrub backwards to the beginning of a live stream, at the moment it seems SmartYoutubeTV only allows you to rewind backwards for a 30 second buffer

it would be regrettable to lose this feature, so i hope the re-instatement of it is possible and an easy process

thanks so much for all your hard work on this excellent app!

**Comment by fgl27** [comment]
Have you check the stream on youtube page? can you do that on they site?

I think youtube changed how a live stream works and now only keeps the last 30s or so on the list.

this is how twitch does they only keep 30s or so, I don't think is app problem is just a change on youtube servers. this technical gives a better performance probably more noticeable on the server side probably the why they change it.

**Comment by thenextmans** [comment]
Yes, I have tested this issue on live videos where the stream is rewindable on the web version of YouTube. 

This limitation is a recent issue, I used to use this feature on SmartYoutubeTV on a daily basis.

**Comment by fgl27** [comment]
Share a live that has the issue only on this app and is OK on youtube page. so I can see what the issue is.

**Comment by fgl27** [comment]
Yes I found a stream that if I play the link that the app is playing it has 7 hours, but on the app is only 30s.

I don't know what @yuliskov changed if he was the one cause it, when he has time he will take a look.

If I find something I post here.
