### ISSUE TITLE
HDR on nvidia shield pro 2019

### ISSUE THREAD

**Issue by Theitfixer85** [yuliskov/SmartYouTubeTV#573]
The app can't play HDR videos on the nvidia shield pro 2019 due to missing hardware acceleration codecs

Can these codecs be included within the app to enable the playback of vp9 HDR

Note 4k vp9 plays fine - it's just the HDR that can't be played

**Comment by fgl27** [comment]
triplicated issue
https://github.com/yuliskov/SmartYouTubeTV/issues/315
https://github.com/yuliskov/SmartYouTubeTV/issues/390

**Comment by fgl27** [comment]
to be correct quadrupled
https://github.com/yuliskov/SmartYouTubeTV/issues/242

**Comment by fgl27** [comment]
quadrupled issue
https://github.com/yuliskov/SmartYouTubeTV/issues/242
https://github.com/yuliskov/SmartYouTubeTV/issues/315
https://github.com/yuliskov/SmartYouTubeTV/issues/390
https://github.com/yuliskov/SmartYouTubeTV/issues/573

can someone close those issue as makes no sense.
and can people be polite and stop open so many issues about the same thing.
