### ISSUE TITLE
Lite Main suddenly zoomed in

### ISSUE THREAD

**Issue by doktormerlin** [yuliskov/SmartYouTubeTV#575]
Suddenly Lite Main is zoomed in a bit in the menus if I watch a video its shifted upwards.

Device: Fire TV Stick 2
Resolution: 1080p
Lite Main and Pro Main, Alt works fine

**Comment by stauffenberg2020** [comment]
Not just Lite Mode. All the modes are suddenly zoomed in. Looks like a bug

**Comment by Maeldor** [comment]
Same here. Most of the UI is cut off which makes it impossible to use properly.

Didn't seem to happen immediately after updating to 6.17.691 but happened after I just restarted the app. Can't seem to fix it no matter what I do.

Using an Nvidia Shield TV Pro (2019).

**Comment by foreveryoungforty** [comment]
Same over here ... since a few hours.

**Comment by stauffenberg2020** [comment]
Exactly, it did not happen after the update, Just a couple of hours before. The UI is unusable. The videos are cropped in Lite Mode (But not in Main mode)

**Comment by foreveryoungforty** [comment]
With me videos show normal,  but the returning from a video to the app-ui goes slow (loading....) and the tabs/screens of the app itself are oversized.

**Comment by Maeldor** [comment]
Video is fine for me also. I've found I can navigate the UI outside videos by holding the direction buttons on my remote until it moves the zoomed in region around, but this is less than ideal.

Stock YouTube app looks fine.

**Comment by foreveryoungforty** [comment]
Perfect fix in 692 update - thanks !

**Comment by dxzhang456** [comment]
6.17.587  has the issue after running several hours.

**Comment by dxzhang456** [comment]
> Suddenly Lite Main is zoomed in a bit in the menus if I watch a video its shifted upwards.
> 
> Device: Fire TV Stick 2
> Resolution: 1080p
> Lite Main and Pro Main, Alt works 
reproduced on #587    
xiaomi 4a

**Comment by stodd3** [comment]
Same zoomed-in issue on both Nvidia Shield TV Pro (2019) and Galaxy S10e, haven't tried FireTV Stick 4K yet.

**Troubleshooting steps attempted without success:**
* Removed and reinstalled app.
* Opened app and clicked "Reset app".
* Cleared cache and data through the app settings.

**Device:** Galaxy S10e
**Android Version:** 10
**SYTTV Version:** 6.17.216
**Launcher:** Lite Main and Pro Main. Lite Alt and Pro Alt have no issues.

**Device:** Nvidia Shield TV Pro (2019)
**Android TV Version:** 8.1.1 (32.7.301.99)
**SYTTV Version:** 6.17.216
**Launcher:** Lite Main and Pro Main. Lite Alt and Pro Alt have no issues.

**Comment by foreveryoungforty** [comment]
To everybody.... please update to 6.17.692... there the zoom-issue is perfectly solved on my 4k Sony Android tv.

**Comment by doktormerlin** [comment]
Yes, seems fixed in latest release. I will close the issue
