### ISSUE TITLE
3-4 Seconds of black screen before playing

### ISSUE THREAD

**Issue by bagerfrede** [yuliskov/SmartYouTubeTV#579]
Whenever i start watching a video, first 3-4 seconds of the video is black and no sound is playing
The video starts, so i have to pause, go back and unpause before watching a video, which is a bit infuriating.

I run the PRO Alt Version on my Nvidia Shield (also happens in PRO Main, LITE Main and LITE Alt)  Version 6.17.692

Video of the glitch: https://i.imgur.com/6Fv04V1.mp4

**Comment by bagerfrede** [comment]
Adblock and minimum buffer is enabled

**Comment by yuliskov** [comment]
check under the video whether auto frame rate is enabled or not.

Regards, Yuriy

**Comment by bagerfrede** [comment]
https://imgur.com/MnQtKd1

**Comment by bagerfrede** [comment]
Wow, you are my hero

Thank you so much for creating this APK, i really love it

**Comment by yuliskov** [comment]
You're welcome. Is problem solved?

Regards, Yuriy
