### ISSUE TITLE
Persistent survey when trying to watch a video

### ISSUE THREAD

**Issue by gabriellluz** [yuliskov/SmartYouTubeTV#584]
Whenever I'm trying to watch a video on my Smart YouTube TV app, it asks me to complete a survey. My app is updated. Also, reinstalling won't solve the problem.
Ok. I choose one of the options but the survey won't finish and it won't let me watch the video.
So I close the video and try again!

But no, it opens up the survey again and I can't watch the video. I can always hear the sound but not see the video.

You can see the screenshots below:
![photo_2020-06-22_09-56-33](https://user-images.githubusercontent.com/6292535/85290100-d28bc900-b46e-11ea-9933-b1398ba0d661.jpg)
![photo_2020-06-22_09-56-45](https://user-images.githubusercontent.com/6292535/85290106-d586b980-b46e-11ea-92f0-d6104bc64f94.jpg)

**Comment by gabriellluz** [comment]
Latest update solved this issue.

**Comment by pacov2** [comment]
Have this issue....no matter what vídeo I pick the survey pops up.
