### ISSUE TITLE
SponsorBlock Integration

### ISSUE THREAD

**Issue by BlitW0** [yuliskov/SmartYouTubeTV#590]
SponsorBlock is an open-source crowdsourced browser extension that allows you to skip sponsor segments(also intros and credits segments) in youtube videos. It also has a [public API](https://sponsor.ajay.app/). This extension really makes watching videos on youtube a no-nonsense experience. Would it be possible to integrate it into smart youtube tv?

**Comment by fgl27** [comment]
Duplicated of https://github.com/yuliskov/SmartYouTubeTV/issues/314

**Comment by BlitW0** [comment]
Closing it in favor of #314.
