### ISSUE TITLE
Quick skip Back/Fwd suggestion

### ISSUE THREAD

**Issue by hiroo916** [yuliskov/SmartYouTubeTV#595]
Suggestion: (context: I'm using Nvidia Shield)

Can [left] and [right] be mapped to [skip back 10 sec] and [skip fwd 10 sec]? (additional nice: customizable time jump for the rew skip and the fwd skip)

Right now, [left], [right] and [down] all bring up the navigation UI, with Play/Pause selected, then to skip back, you have to go up to select the playhead, then left and right to go back or fwd, the select to jump there. That's a lot of clicks. 

Seems like [left] and [right] could be mapped to the skip 10 sec functions, while [down] would bring up the existing Nav UI where you can use the playhead to move over a larger time with thumbnail.

EDIT: changed my Left and Right and Down usages above to not Less-than or Greater-than angle brackets since that apparently causes the words inside to not be displayed.

**Comment by foreveryoungforty** [comment]
Nice suggestion, would be great if the time-lapse of skipping back/forward becoming user-adaptive

**Comment by fgl27** [comment]
What you are even requesting here?

The first post is so confusing.

Today if you left /right click twice it will skip back/forward 10 seconds and show the UI, if you hold the key more then 10 seconds will be skipped.

If you don't want see the UI you need a remote that has the media fast forward/backwards keys, as clicking those keys already do that but doesn't show the UI

So what is the point of this issue? All the features are already there, at least as far as I can understand what is be requested, but what is be requested is so confusing maybe I don't get it, so properly explain it.

BTW You can buy very cheap remote that have multiple media keys and they all work on this app making the experience of using not just this app any Android media app much better.

This model is the one I use
https://www.amazon.com/Rii-Multifunction-Wireless-Keyboard-3-Gsensor/dp/B01CL3ZXGO?ref_=fsclp_pl_dp_2

**Comment by hiroo916** [comment]
Sorry, I looked back on my post and noticed that because I used `<Left>`, etc. for my arrow key references, the forum software allows it in the editor text but completely removes those text from the displayed post.  So I can understand why the post with all the missing key words would be confusing. (I've edited my original post to fix the problem)

I did just go experiment using the suggestions given by fgl27:
- I did not know about the double-click for 10 sec skip existed.  So, this covers most of my request.
- I also found that clicking left or right from the playback screen pops up the UI, but with the playhead selected.  This is different from what I thought was happening, which was UI  pops up with play/pause selected (same as pressing Down).  My misunderstanding was that left, right, and Down all did the same thing as Down, so it would make sense for Left and Right to do something different.  However, since they are actually different, then no change is necessary.

None of my request was related to seeing the UI, just easier direct access to 10 sec skip.  Since that is in place,  I withdraw my request and apologize for the confusion caused by the angle-bracket non-display.

**Comment by fgl27** [comment]
Good that was just a harmless misunderstand, glad we manage to solve.

Those left/right clicks are really useful, but the app is missing a way to display/explain the controls and shortcuts maybe someday someone makes a in app help or at least a page on the project explaining it all.

I personalty learn as most probably do by mistake, one day I just hold the key and it just skipped, but after knowing it I use it a lot, as a simple click and hold for a second or two allows you to quickly skip 30 or so seconds of content, that allows you to quickly skip a intro for example.
