### ISSUE TITLE
Playback and performance issue

### ISSUE THREAD

**Issue by KohGeek** [yuliskov/SmartYouTubeTV#6]
On the normal version of SmartYoutubeTV, the video would continuously buffer, non-stop.

On the beta version, the playback works normally, but the rendering with the CrossWalk browser library is so stupendously slow you can see the columns refresh one by one...

So, I have checked and it seems that crosswalk is just having fun with some of it's lib, but it's the native browser app that got me curious, since it was absolutely fine until you try to playback.

**Comment by yuliskov** [comment]
Hi. I currently developing alternate version. Please, check it out.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.32/SmartYouTubeTV_Exoplayer_v6.8.32_r.apk

**Comment by yuliskov** [comment]
4K is intended to fix such problems. Pleas, check latest release.
