### ISSUE TITLE
Black screen when you press "save" button

### ISSUE THREAD

**Issue by p1r473** [yuliskov/SmartYouTubeTV#601]
Hello,
When you press the "save" button on a video, for example to add it to Favorites or Watch Later playlist, the screen turns black before showing the menu.
I believe the screen should not turn black, and this is a bug.

**Comment by foreveryoungforty** [comment]
@p1r473 just tested this on beta 702 and it works normal here like it always did

**Comment by p1r473** [comment]
Is screen going black for you?

**Comment by foreveryoungforty** [comment]
There comes an insert screen where you can choose to which list you want to save... as normally

**Comment by p1r473** [comment]
Yes, but before the insert screen comes, the video goes black.

**Comment by foreveryoungforty** [comment]
The video/screen is a little greyed out when you push save, because of the overlay ,  but no black screen on my sony android tv

**Comment by p1r473** [comment]
When I push save, for about 0.5-1second before the insert screen pops up, video is black, and remains black while the insert screen is up.

However, I can still hear the video, though I can't see the video.

I am using Nvidia Shield and a Samsung Q80 TV
