### ISSUE TITLE
Hide scrollbars in window

### ISSUE THREAD

**Issue by saalmaan** [yuliskov/SmartYouTubeTV#62]
Going back from video to home screen sometimes shows vertical and horizontal scrollbars in the window. hiding scrollbars will clean up the interface. see screenshot 

![img_6314](https://user-images.githubusercontent.com/4620730/35072615-3840fe34-fbdd-11e7-8263-d06b1c84d80a.JPG)

**Comment by TheRMaverick** [comment]
I can confirm the issue on 6.12.37 with Fire TV Stick.
Not every time, but it can happened.

**Comment by yuliskov** [comment]
Is this issue reproduced on the latest build?
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.47/SmartYouTubeTV_Orig_v6.12.47_r.apk

**Comment by TheRMaverick** [comment]
With 6.12.48 the issue is fixed for me. Who are you, @saalmaan ?

**Comment by saalmaan** [comment]
I can confirm that this is fixed now
