### ISSUE TITLE
Petition to build launcher for MiTV

### ISSUE THREAD

**Issue by saalmaan** [yuliskov/SmartYouTubeTV#63]
Hello, 

This is a petition to the developer (Yuriy Lyskov) of SmartYouTubeTV to start another opensource project to build a lightweight launcher for MiTV or make Android TV launcher compatible with MiTV.

its salient features should be
- playback from HDMI or other inputs
- Play Store and Amazon Store 
- Chromecast/Airplay support
- External Bluetooth keyboard/mouse support 

Other suggestions?

**Comment by yuliskov** [comment]
> playback from HDMI or other inputs

There are already apps that can add such functionality to any launcher.

> Chromecast/Airplay support

Not sure about Airplay but Google Cast (I suppose you mean this because Chromecast is a device not technology) capable to work only with certificated devices. It is even true when you have gapps installed.

> Play Store and Amazon Store

Not sure that I understood you correctly. You mean to develop custom store inside launcher? Why not to install Play Store that comes along with gapps?

> External Bluetooth keyboard/mouse support

What purpose of this? Navigate/search through the launcher?

**Comment by rodalpho** [comment]
Use this.

https://play.google.com/store/apps/details?id=com.awe.dev.pro.tv

**Comment by saalmaan** [comment]
Mian reason for this thread was to replace MiTV Chinese launcher with decent TV launcher who's roadmap is controlled by open source community.

I have tried launchers that are designed for phone and don't really work. @rodalpho 's suggestions is OK but not open source 

> There are already apps that can add such functionality to any launcher.
installing a HDMI playback apps inside a phone launcher on TV doesnt really help, TV launcher is what we need that should have this capability built in

> Play Store and Amazon Store
What I meant was that launcher should come with app store pre-installed so that users dont have to install Gapps and stuff

> Not sure about Airplay but Google Cast (I suppose you mean this because Chromecast is a device not technology) capable to work only with certificated devices. It is even true when you have gapps installed.
Chromecast support in the launcher will be great. MiTV launcher has also Apply play support having that will also be great.

> What purpose of this? Navigate/search through the launcher? Isn't there any other launcher that contain such functionality?
One big drawback of MiTV launcher is that you can control mouse cursor on the TV with MiTV app but you cant input from the app. It will be great if both cursor and keyboard input can be managed from an external app.

Should we have a slack channel to discuss things in realtime? I can also arrange for UX prototype for launcher if that helps with questions.

**Comment by WolfganP** [comment]
```
Use this as a leanback launcher. The rest of your stuff has nothing to do with the launcher.

[https://play.google.com/store/apps/details?id=com.awe.dev.pro.tv]
```

Good recommendation, I use the same launcher in my generic Android box with SmartYoutubeTV and other video apps, and works seamlessly.

**Comment by yuliskov** [comment]
Interesting launchers with source code.
AppStarter Launcher: https://github.com/sphinx02/AppStarter
Simple TV Launcher: https://github.com/alescdb/LauncherTV

**Comment by saalmaan** [comment]
I have tried Appstarter and it working fine. however there is no app or option to view TV from HDMI? is there an app that I need to install to view hdmi?

**Comment by yuliskov** [comment]
@saalmaan here my tweaks. They can by applied to any launcher. Read description in the main folder.
https://drive.google.com/open?id=1vl9InHLaqZygGe7RAvLB_8OIvEYVImyr

**Comment by saalmaan** [comment]
Excellent share @yuliskov now. I have added the apps you shared to Appstarter launcher and made the default. I am pretty happy with the setup so far. However, it's not for everyone. What I mean is that this is bit technical and experience can be further optimized when you compare it with Google launcher and Fire tv launcher.

is it worth forking AppStarter and build on top of it?

**Comment by saalmaan** [comment]
Update: I have managed to install [Google TV (Android TV) launcher](https://www.apkmirror.com/apk/google-inc/android-tv-launcher-android-tv/android-tv-launcher-android-tv-1-11-2-100-4443508-release/android-tv-launcher-android-tv-1-11-2-100-4443508-android-apk-download/) on MiTV3 (see screenshots). however, it's not fully functional. 
Issues:
- not all apps are showing
- launcher settings are not showing
- search button is not linking to correct google app

![img_6445](https://user-images.githubusercontent.com/4620730/35467763-a1494344-030a-11e8-967e-e1fbb18cc280.JPG)
![img_6446](https://user-images.githubusercontent.com/4620730/35467764-a15ce886-030a-11e8-93e4-51df50d76df3.JPG)
![img_6447](https://user-images.githubusercontent.com/4620730/35467765-a1718c28-030a-11e8-8c2c-4d0cc52a5c39.JPG)

Also, found an open source launcher ([Cat launcher](https://github.com/JackyAndroid/AndroidTVLauncher)) that looks and functions very similar to Google TV

Google's on [documentation](https://github.com/googlesamples/androidtv-Leanback) is pretty extensive as in how to build TV compatible apps

**Comment by yuliskov** [comment]
Not actual.
