### ISSUE TITLE
Sponsor block

### ISSUE THREAD

**Issue by Mushin** [yuliskov/SmartYouTubeTV#631]
Please can you add support for YouTube sponsor block? It's available as a chrome extension, and has also been incorporated into the latest version of vanced.

**Comment by foreveryoungforty** [comment]
@Mushin  I have no ads in SYTV and also not in the beta version (and not in vanced, where i did no't activate the new sponsorblock function).... can you explain what is the surplus and extra functionality and advantage of Sponsor block ?
Thanks for info. Regards, Rik

**Comment by Mushin** [comment]
Sponsor block allows automatic skipping of intros, outros, sponsored segments, etc. actually within the video itself. AFAIK it does this using user contributed data tagging these segments for each video. I just tested it on vanced and it works great.

**Comment by fgl27** [comment]
Quadruplicated issue BTW.

https://github.com/yuliskov/SmartYouTubeTV/issues/314

You can search before open a issue, do you know that?
https://github.com/yuliskov/SmartYouTubeTV/issues?q=Sponsor

**Comment by Mushin** [comment]
@fgl27 Yes, I searched for 'sponsor block' but there were no results.

**Comment by fgl27** [comment]
Wrong there is, search like this
https://github.com/yuliskov/SmartYouTubeTV/issues?q=sponsor+block

**Comment by Mushin** [comment]
The default search option is
is:issue is:open

Which is why it didn't find anything when I tried.

So no, not 'wrong', just a mistake.

Why not chill out with the attitude.

**Comment by fgl27** [comment]
The question is why the issue it's still open?
