### ISSUE TITLE
Captions / subtitle style cannot be configured, and will always be a ridiculous large size when enabled

### ISSUE THREAD

**Issue by demux4555** [yuliskov/SmartYouTubeTV#639]
I'm on an Nvidia Shield, and I'm finding it very frustrating not to be able to adjust the font size of the captions/subtitles in SmartYouTubeTV. The font size is huge. 1/3 of the bottom screen is used for captions when there are two lines of text. It's literally unusable with this font size. I have to keep going back to the original YouTube app whenever I want to watch something with subtitles.

Changing the captions style in the original YouTube app works fine there, but these settings are not used in SmartYouTubeTV.

Android accessibility captions settings do nothing at all, and to be honest, I can't find a single app where these settings apply.

Am I missing something here? Is there really no way to adjust the font size?

**Comment by begundal** [comment]
try lite launcher for configurable subtitle

**Comment by demux4555** [comment]
Hi there, thanks for the info. This resolved my problem. 

The website does not explain things like this. Perhaps an idea to include information about this in the "What to Choose?" section.
