### ISSUE TITLE
Mouse click don't work

### ISSUE THREAD

**Issue by clevertype** [yuliskov/SmartYouTubeTV#652]
On android tv, new update, don't work mouse click on button search and other. Fix please

**Comment by jonilaw** [comment]
Yes, it is, mouse click is not working on the latest update. Please help to fix it.

**Comment by Nzzyme** [comment]
I observed that after an update, when I click on the search button with the air mouse remote, it does not register as a click and it won't go to the search page. Please fix

**Comment by Nzzyme** [comment]
Was this closed as there was a new version which fixed this issue?
