### ISSUE TITLE
Can not watch live stream

### ISSUE THREAD

**Issue by xyzmodem** [yuliskov/SmartYouTubeTV#66]
Today when I upgrade to 6.12.51, the every youtube live stream can not watch but can hear sound track.

And first time play youtube video always can not watch but can hear sound track.
But push return button then enter video again, the video will normal.

https://imgur.com/ISKExmn

**Comment by yuliskov** [comment]
Hi. I would ask you to install some old versions from here, and check that problem still occurs https://github.com/yuliskov/SmartYouTubeTV/releases

**Comment by xyzmodem** [comment]
This version of 6.12.49 will not have this phenomenon.

**Comment by xyzmodem** [comment]
After updating to version 6.12.53, half the chance of this abnormal phenomenon.

**Comment by xyzmodem** [comment]
This problem no longer exists at 6.12.58
