### ISSUE TITLE
Mouse click and mouse move don't work on Android TV

### ISSUE THREAD

**Issue by clevertype** [yuliskov/SmartYouTubeTV#662]
Latest version mouse click on button search, click edit search question and other don't work. If back menu open, click work. Mouse down left button and move list video don't work across time, Focus change on list video and mouse move with left button mouse don't work. Backup prev version don't help. Fix please mouse all.

**Comment by shadowscott** [comment]
I believe this is due to the "youtube web version" that updated. Fire Stick is having the same issue where Play/Pause, FF, RW buttons do not work. Youtube web version updated to 20201006 and interferes with SYTV in Lite mode. Main is unaffected.
