### ISSUE TITLE
Mibox pro (not worked)

### ISSUE THREAD

**Issue by mmsean** [yuliskov/SmartYouTubeTV#67]
之前都版本.51，都可以播，現在最新5.3無法播，我的版本android5.01，謝謝您。

**Comment by yuliskov** [comment]
only in english, sry

**Comment by mmsean** [comment]
Prior to version 0.51, can broadcast, the latest 5.3 can not be broadcast, my version android5.01, thank you.

**Comment by yuliskov** [comment]
Could you record a video, pls?

**Comment by mmsean** [comment]
https://drive.google.com/file/d/1WLRocd9K3UxlHVrnW3ZNQwKbb3nT1VQA/view?usp=drivesdk

**Comment by mmsean** [comment]
Please help, thanks

**Comment by mmsean** [comment]
https://youtu.be/DAEP3KniKgA

**Comment by yuliskov** [comment]
@mmsean what about other versions: 720, 1080, 4k, 4k alt? All the same?

**Comment by yuliskov** [comment]
Is issue not fixed yet?
