### ISSUE TITLE
Fire tv

### ISSUE THREAD

**Issue by hamswolo** [yuliskov/SmartYouTubeTV#677]
When backing out or scrolling down while watching video get black loading screen.  App is also being sluggish sometime taking a long time to load video.  Ive reinstalled the app and this is happening on 2 different fire devices .

**Comment by master3243** [comment]
I'm using fire tv as well, black loading screen everytime I back out,
Happens with PRO/PRO Alt but not LITE. 
I noticed that it stays like that indefinitely until I press back again then it properly exits however if I press navigation buttons instead i can see the original youtube app's navigation UI which is strange (but should hopefully be a good hint to the developers on what is going on)
