### ISSUE TITLE
Spanish Language

### ISSUE THREAD

**Issue by jackiehhop** [yuliskov/SmartYouTubeTV#71]
Hello Friend

the Spanish language would be available in the app

[string Español.txt](https://github.com/yuliskov/SmartYouTubeTV/files/1685422/string.Espanol.txt)

**Comment by yuliskov** [comment]
I think there is needed some tool or something like that. Maybe this tool could help (not tested yet, though):
https://play.google.com/store/apps/details?id=th.berm.strings.xml&hl=en

Files to localize:
https://github.com/yuliskov/SmartYouTubeTV/blob/master/smartyoutubetv/src/main/res/values/strings.xml
https://github.com/yuliskov/SmartYouTubeTV/blob/master/appupdatechecker/src/main/res/values/strings.xml
https://github.com/yuliskov/SmartYouTubeTV/blob/master/browser/src/main/res/values/strings.xml
https://github.com/yuliskov/SmartYouTubeTV/blob/master/exoplayeractivity/src/main/res/values/strings.xml

**Comment by jackiehhop** [comment]
I'm going to translate everything and send it to you

**Comment by yuliskov** [comment]
Closed. No input

**Comment by juanrodgil** [comment]
I can help with the translation into Spanish. Is it still necessary to locate only those four files?

Is the system language detected the first time you start the application?
