### ISSUE TITLE
Nvidia Shield TV 2019 - Media keys like Play, Pause, FF, RW no longer work

### ISSUE THREAD

**Issue by echotron** [yuliskov/SmartYouTubeTV#711]
I don't know what happened, but media playback keys no longer work on my Nvidia Shield TV Pro 2019.

Until a few days ago, I had no problems using my Logitech Harmony remote to play, pause, fast forward and rewind videos in Smart YouTube, but now the media keys no longer work. However, they still work in the regular YouTube app on the Shield.

It's very frustrating because I've gotten used to using the playback keys on my remote, but now I have to use the direction pad instead, which is very bad for UX, in my opinion.

I hope this bug can be fixed quickly.

Thanks. 

UPDATE: I think I was accidentally using the LITE version instead of the PRO version. I don't know how it switched, because I normally use the PRO version, but I switched back to the PRO version, and now everything is working normally again. I also uninstalled and re-installed the app, so that may have had an effect, but I think it was more likely LITE vs PRO.

**Comment by hamswolo** [comment]
Check out his new app smarttube next its in beta but working and getting regular  updates.

**Comment by stodd3** [comment]
#647 Same issue.

**Comment by echotron** [comment]
> #647 Same issue.

Thanks. This would confirm that the issue was with the LITE version. Again, I don't know how I got switched to the LITE version, but using the PRO version, like I normally do, solved the issue for me (though the underlying issue in the LITE version remains).
