### ISSUE TITLE
Grey screen /w latest update

### ISSUE THREAD

**Issue by licronik** [yuliskov/SmartYouTubeTV#76]
I updated the app and now every video plays but the screen is grey. Its for the 720 firetv at version 6.12.61.

**Comment by yuliskov** [comment]
Many thanks for the early bug report. Please, test this build:
D:\other\me\proj_android\SmartYouTubeTV\smartyoutubetv\SmartYouTubeTV_Orig_v6.12.62_r.apk

**Comment by felix-fx** [comment]
I use the firetv too and v6.12.61 worked after autoframerate was enabled. But now with v6.12.62 the screen is gray with autoframerate on and off. App is no longer useable on firetv stick.

**Comment by felix-fx** [comment]
v6.12.64 works! normal playback now on firetv stick.

**Comment by yuliskov** [comment]
Hi, friends. Would you be so kind to test latest release on the FireTV. I need to know, whether this bug still exists here.
Link: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.68/SmartYouTubeTV_Orig_v6.12.68_r.apk

**Comment by licronik** [comment]
Just tested version 6.12.68, the bug still exists on the 720 version.

**Comment by yuliskov** [comment]
@licronik many thanks, friend. Maybe this release changes something for you.
Link: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.69/SmartYouTubeTV_Orig_v6.12.69_r.apk

**Comment by licronik** [comment]
Bug is still present in 6.12.69. Let me know if you want me to test more builds for you.

**Comment by yuliskov** [comment]
@licronik I'm very appreciate your help. Here the next release.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.70/SmartYouTubeTV_Orig_v6.12.70_r.apk

**Comment by licronik** [comment]
Ver pleased to say, as of 6.12.70 the bug is gone!

**Comment by TheRMaverick** [comment]
6.12.70 is not good on 4K Version for Fire TV Stick. Some videos stock after few seconds but the sound is still present. Statics from YouTube says climbing dropped frames till the video ends.
On the other hand some videos play well as before. Some problem with the codecs?

**Comment by TheRMaverick** [comment]
Example for a corrupt video:
https://youtu.be/8MPbR6Cbwi4

**Comment by yuliskov** [comment]
@TheRMaverick could you compare performance with this old stable version?
 https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.64/SmartYouTubeTV_Orig_v6.12.64_r.apk

**Comment by TheRMaverick** [comment]
@yuliskov
Performance with last stable version 6.12.64 is good. Dropped frames and freezes Videos only with 6.12.70 on 4K Version.

**Comment by yuliskov** [comment]
@licronik sorry for bothering you. Check pls, that our old problem not reappeared again.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.71/SmartYouTubeTV_Orig_v6.12.71_r.apk

@TheRMaverick this strange. Seems, that last changes to 4k were long time ago.

**Comment by TheRMaverick** [comment]
@yuliskov
Okay, now everything is good. No dropped frames. Tested with 6.12.70 and 6.12.71_2 for 4K Version.
Maybe temporary issue by YouTube.

**Comment by licronik** [comment]
I tried v6.12.71 and the bug is back again. Hope that helps

**Comment by WolfganP** [comment]
I'm suffering the same issue lately (cheap Android 4.4 box). When SmartYoutubeTV starts, the screen stays grey and the spinning wheel going round and round.
What I suspect is that it's somehow related to network detection, as my box have both wired ethernet (always connected) and wifi, and the app only starts properly if wifi is on (even if launching a browser or other apps work and connect OK as ethernet is working properly). 
Maybe something related to a network check that looks for wifi interface no matter what and ignores working wired connections?

**Comment by yuliskov** [comment]
The thread is outdated. I need some new info.
