### ISSUE TITLE
AD countdown?

### ISSUE THREAD

**Issue by Crock56** [yuliskov/SmartYouTubeTV#786]
Suddenly started showing the ad countdown, does not show ad but stops and instantly reloads what I am watching?

**Comment by ghost** [comment]
Having the same problem with ad loading message. Ad loading in 5, doesn't show ad but disrupts watching video.

**Comment by ghost** [comment]
> Suddenly started showing the ad countdown, does not show ad but stops and instantly reloads what I am watching?

Try smart youtube next, same developer much faster loading. Haven't noticed any ads.

**Comment by pdcweb** [comment]
> Try smart youtube next, same developer much faster loading. Haven't noticed any ads.

smart youtube next? do you have a link for that?

EDIT: https://github.com/yuliskov/SmartTubeNext

**Comment by ghost** [comment]
> > Try smart youtube next, same developer much faster loading. Haven't noticed any ads.
> 
> smart youtube next? do you have a link for that?
> 
> EDIT: https://github.com/yuliskov/SmartTubeNext

Yeah thats the one, been using it for a couple of hours. Quicker loading and not seen one ad pop up.

**Comment by Crock56** [comment]
Thanks for the help, downloaded Smarttubenext and  all now AOK!!!
