### ISSUE TITLE
Purchases don't play in All Modes

### ISSUE THREAD

**Issue by Malouff** [yuliskov/SmartYouTubeTV#79]
If you buy something (TV Show / Movie) from the Google Play Store they show up under 1) Library 2) Purchases

SmartYouTubeTV will display the correct place holder info but will not Play the Movie in any mode except for the 1080 one

Mode 1(720 MiBox) 
Nothing Plays says Loading... 

Stats for Nerds
Viewport 1920x1080
Current / Optimal Res 0x0
Volume / Normalized 100% / 100%

Mode 2 (1080 MiTV)
The Purchased Video Plays

Stats for Nerds
Viewport 1920x1080
Current / Optimal Results 854x480@24 / 854x480@24
Volume / Normalized 100% / 100%
Codecs av1.4d401e (223) / MP4 a.40.2 (149)
Protected com.wildvine.alpha/large/SD/AUDIO/UKS:
Host r1---sn-nx5e6nez

Mode 3 (4K MiTV)
No error displayed

Stats for Nerds
Player Paused false
Playback State Idle
Disney Mode ID 0

Video:
Quality set to Default Quality, Autoframerate is turned on, Hide Playback Errors is Turned off

Audio: 
Set to Default Quality 

Subtitles: 
Set to Default Quality 

Backing out it says viewport is 0x0

4) Mode 4 (4K alt) 
Is the same as above except when backing out the Stats for Nerds has full info but passes by to quickly 

Also, does not work in Firefox Browser 
Get the error: This Video Format is not Supported 
Please report this ID to help us fix the problem 
8PR3q794K1Wfarda

On Silk Browser get a prompt 

www.youtube.com wants to uniquely identify your device to play protected content.
The choice is Block or Allow

It will play the video 

Stats for nerds
Viewport 960x540*2
Current / Optimal Resolution 854x480@24 / 854x480 @24
Volume / Normalized 100% / 100%
Codecs a 1.4d401e (223) / mp4a.40.2 (149)
Protected com.wildvine.alpha/large/SD,AUDIO/UKS:
Host r1---sn.nx5e6nez

Also works in vTube for YouTube [FREE]
Stats for Nerds

Viewpoint 960x540*2
Current / Optimal Res 854x480@24 / 854x480@24
Volume / Normalized 100% / 100%
Codecs avc1.4d401e (223) / MP4a.40.2 (149)
Protected completely. wildfire. alpha/large/SD, AUDIO/UKS: 
Host r1---sn.nx5e6nez

Everything tested on a Amazon Fire TV 4K 2017 Edition

**Comment by yuliskov** [comment]
@Malouff thanks friend. It is definitely a very serious issue. Don't know how to deal with it, though.

**Comment by yuliskov** [comment]
Closed, since I can't test this mode
