### ISSUE TITLE
MITV4 No video when play video. 

### ISSUE THREAD

**Issue by liliass** [yuliskov/SmartYouTubeTV#8]
Dear Yuliskov, 

I just bought the MiTV4, App is perfect except blank screen/black screen when play video. 

Only sounds no video/graph. 

Thank you.

**Comment by yuliskov** [comment]
Hi, pls try beta from there: https://smartyoutubetv.github.io/en/

**Comment by liliass** [comment]
Hi Yuliskov, No,it doesn't works. :(

**Comment by yuliskov** [comment]
Here is a solution. Could you intall CPU-Z on your tv? I need a screen from
second tab named Device. Then I'll give you a temporal fix.

**Comment by liliass** [comment]
@yuliskov Thanks for the rapid response. u are awesome !
Below is the screenshot of the device name and etc.
http://imgur.com/4y96FwO
http://imgur.com/K3sJVNe
http://imgur.com/567RVR4

**Comment by liliass** [comment]
Done ? so exciting to try in my new tv .

**Comment by yuliskov** [comment]
Excellent. Now its my job. I'll send you apk for test soon.

**Comment by yuliskov** [comment]
apk to test:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.7/SmartYouTubeTV_v6.8.7.apk

**Comment by liliass** [comment]
Thanks @yuliskov

**Comment by liliass** [comment]
No, It doesn't work :(

Deleted the app, install new app provided above.

**Comment by liliass** [comment]
I realized the screen can scroll to left and right / up and down. 
Please refer to the youtube link. 

https://youtu.be/ZJXeJtkRf_E

http://imgur.com/a/ffJpG

**Comment by yuliskov** [comment]
It must being working. Please remove all previous version and install
provide apk again.

**Comment by liliass** [comment]
removed all, youtube app. 
reinstall and remain black screen.

**Comment by yuliskov** [comment]
ok, what now

**Comment by yuliskov** [comment]
test now:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.7/smartyoutubetv-originalFlavor-release.apk

**Comment by liliass** [comment]
@yuliskov Same. Blank screen

**Comment by yuliskov** [comment]
Your video must being opened through external player (e.g. MXPlayer). I
forced setting to do that. If got black screen then this trick did not
work. Hmm. Strange.

**Comment by liliass** [comment]
Does it mean I need to download MXPlayer app ? In order to make it works ?

**Comment by liliass** [comment]
installed MXplayer, not working as well. :(

**Comment by yuliskov** [comment]
I think you launching wrong apk. There definitely be a player select dialog after you clicked on video.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.7/smartyoutubetv-originalFlavor-release.apk

**Comment by yuliskov** [comment]
maybe now:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.8/SmartYouTubeTV_v6.8.8.apk

**Comment by liliass** [comment]
Yes, For temporarily solution. 

Now it pop up a windows then i have to select Mxplayer to play the video.

**Comment by liliass** [comment]
Thanks @yuliskov for your awesome work. 
May i know any new fix coming soon ? instead of focusing 3rd party video player  ?

**Comment by yuliskov** [comment]
> May i know any new fix coming soon ? instead of focusing 3rd party video player ?
I think, it might be today. I have some variants to the test.

**Comment by yuliskov** [comment]
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.9/SmartYouTubeTV_v6.8.9.apk
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.9/SmartYouTubeTV_Beta_v6.8.9.apk

**Comment by liliass** [comment]
Performance issue on VP9 codec ? 
There are a lot of dropped frame. 
http://imgur.com/a/efz1o

**Comment by yuliskov** [comment]
At least it performs better on your tv than avc codec. What about beta version?

**Comment by liliass** [comment]
@yuliskov both have the same issue. 360p and below no dropped frame. 

720/1080/1440 heavy dropped frame.

**Comment by yuliskov** [comment]
Did change in codec configs. Not sure that it helps though.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.10/SmartYouTubeTV_v6.8.10.apk
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.10/SmartYouTubeTV_Beta_v6.8.10.apk

**Comment by liliass** [comment]
@yuliskov  Black screen on 6.8.10 on both version.

**Comment by liliass** [comment]
Any workaround ?

**Comment by yuliskov** [comment]
Only workaround that I know is the version where playback goes through external player. I'll try to imrove it.

**Comment by liliass** [comment]
I'm happy if u can force the best video quality on external player.

**Comment by yuliskov** [comment]
Fixed in latest version.
