### ISSUE TITLE
Video stops sometimes and require to hit play again to start

### ISSUE THREAD

**Issue by fish7yu** [yuliskov/SmartYouTubeTV#80]
I have been running several versions of Smart YouTube TV on my Mi Box 3 Pro, the video plays for a while, then it will stop, I need to hit the stop button and then play button again to continue the video.

Currently running Smart YouTube TV 6.12.78, 720p version (not required crosswalk).

Thanks for your help in advance.

**Comment by yuliskov** [comment]
@fish7yu thanks for the feedback. Have you tested crosswalk based version? It is hard to understand from your post.

**Comment by fish7yu** [comment]
Thanks for your prompt reply.

I have not been able to find a version of crosswalk version that will run on my Mi Box 3 Pro, the Mi Box is a China version that does not have Google Play installed.

I will continue to try and find a crosswalk version that will run on my Mi Box.

For now, I suspect the video stopping may be due to ads popping up in Youtube but somehow not able to run therefore hangs the main video that is playing, have you experienced any issues on ads in Youtube interrupting the video?

Thanks!

**Comment by yuliskov** [comment]
@fish7yu I'm pretty sure that crosswalk version should run fine. You can find number of releases [here](https://drive.google.com/drive/folders/1_HM4DDAbCchAkCcAruWnJ4cGYDfXLEw9). I think that you could start off with the arm64 version. If no luck then try arm version.

**Comment by fish7yu** [comment]
Again, greatly appreciate your kind help, I will try crosswalk versions and let you know.  Thanks!

**Comment by fish7yu** [comment]
Hi, just like to let you know that I have installed the 64 bit version of Crosswalk, and now running the 1080p version of Smart Youtube TV for about 2 hours, no stoppage encountered yet, so far so good, looks like the problem has been solved.  Thanks a lot!
