### ISSUE TITLE
релиз 6.12.78 сломал масштаб на leeco tv x50

### ISSUE THREAD

**Issue by foozzi** [yuliskov/SmartYouTubeTV#81]
Привет земляк, юзал до 6.12.78, вчера обновился все же, оказалось что на 50" масштаб такой, будто разрешение намного меньше
Чуть позле пришлю фото, гляну еще код, если выйдет фиксануть, пришлю пул

UPD:
Странно, но я удалил приложение, очистил кеш и все встало окей, думаю стоит внести в доку, если случаются креши, возможно решит удаление приложения и установки свежей версии без обновления "по воздуху"
Конечно, быть может это проблемы китайского android, но все же

**Comment by yuliskov** [comment]
@foozzi привет. Огромное спасибо тебе за инфу. К сожалению, опоздал. Баг редкоуловимый. Хотел проверить один фикс.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.79/SmartYouTubeTV_Orig_v6.12.79_r.apk

**Comment by foozzi** [comment]
я попробую сегодня установить старый релиз (месячной давности) и обновиться по воздуху, буду ловить в общем, потом фикс пробну
