### ISSUE TITLE
No longer blocking any ads

### ISSUE THREAD

**Issue by JamesStreck** [yuliskov/SmartYouTubeTV#817]
I'm running Smart YouTube TV app on two different Amazon Firesticks, and neither is blocking any ads anymore as of 5/12/21.  I've tried all the different launchers, but they're all the same. The ads are numerous and frequent, just like in the standard Google YouTube app. 

Version web_20210512_10RC01

**Comment by ColinM9991** [comment]
Have you seen the ReadMe? This is no longer maintained

**Comment by JamesStreck** [comment]
> Have you seen the ReadMe? This is no longer maintained

I didn't. Thanks, I'll look at it.
