### ISSUE TITLE
Pro main and Pro Alt missing 

### ISSUE THREAD

**Issue by t-rocks** [yuliskov/SmartYouTubeTV#819]
The app updated this evening and now the both pro launchers are missing from the settings menu.  

I'm using an Nvidia Shield.

**Comment by webbrewer** [comment]
Same here - and the lite options don't support remote control of pause, ff etc. Going to look at smarttubenext.....

**Comment by ivytin** [comment]
same problem when upgraded to the last stable version. And my device is Sony A8H television.

**Comment by webbrewer** [comment]
Yes, latest version didn't fix anything for me either on a firetv but smarttubenext is the developer's new offering and it works great for me.

**Comment by jarrard** [comment]
yep missing for me also.

**Comment by webbrewer** [comment]
Get smarttubenext....don't think the original version is supported anymore.
