### ISSUE TITLE
The latest version of Smart YouTube TV is not running on Android 4.4.4

### ISSUE THREAD

**Issue by Hendrix500** [yuliskov/SmartYouTubeTV#831]
youtube was running fine till last night but this morning i opened youtube and i clicked on a video but the video didn't play. I tried again but it didn't work. I am So Sad I lost my youtube.
Please Help Me🙏🙏🙏
Android Version - 4.4.4 KitKat.

**Comment by fish7yu** [comment]
Same thing happened to me，YouTube videos does not play any more.

**Comment by Hendrix500** [comment]
> Same thing happened to me，YouTube videos does not play any more.
