### ISSUE TITLE
Low-Res Videos only show a corner of the screen

### ISSUE THREAD

**Issue by doktormerlin** [yuliskov/SmartYouTubeTV#85]
Older Videos only uploaded in Low Resolution only show a corner of the screen used. An example is this 10 year old Video: https://youtu.be/WsirCoxcfo4

Using Fire TV Stick 2 in 1080p mode

**Comment by yuliskov** [comment]
Hi. Is it not fixed yet?

**Comment by doktormerlin** [comment]
No, this is still present (just tested it in todays version). It is not present in 4k mode

**Comment by yuliskov** [comment]
Fixed in the latest version.

**Comment by yuliskov** [comment]
Fixed in the latest update.
