### ISSUE TITLE
[Request] Add Voice search

### ISSUE THREAD

**Issue by oroboros** [yuliskov/SmartYouTubeTV#87]
This is the one thing that keeps me away from using this app.

**Comment by SesioN** [comment]
+1 for this feature.

As this app is meant for TVs, having to search via a keyboard is just a no go and doesn't make fun at all. This should be a primary feature.

**Comment by tamamma** [comment]
It will be useful at least, find the way to open the links that Android TV Voice Search shows when using it with Smart YouTube. With normal YouTube uninstalled it doesn't open them with nothing.

**Comment by doktormerlin** [comment]
It would also be extremely nice if it would work with the FireTV Stick Alexa (but I don't know if it's possible. If I ask Alexa to search something on YouTube she just responds with "I can't do that on FireTV)

**Comment by yuliskov** [comment]
@doktormerlin there is possibility that voice search will be added but not for Alexa. It's hard to develop such features without real device on hands.

**Comment by Brandonv101** [comment]
Voice search works for me on the 4K Alt launcher using the Fire TV stick 4K. Just go up when typing in something and press the Alexa voice button.

**Comment by Brandonv101** [comment]
Voice search works for me on the 4K Alt launcher using the Fire TV stick 4K. Just go up when typing in something and press the Alexa voice button.

**Comment by yuliskov** [comment]
done
