### ISSUE TITLE
SMART YOUTUBE TEST FAMILY T18 CHALLENGER

### ISSUE THREAD

**Issue by jackiehhop** [yuliskov/SmartYouTubeTV#9]
HELLO DEAR FRIEND
I AM ANDRES HAVE TIME WRITTEN YOU WITH THE MAIL jackie.hhop@gmail.com
First of all let me congratulate you for the great work you have done with this app I liked the way you can watch youtube on my tv and other friends who have the same tv challenger T18 

The new apps you've made stopped working on the TV I would like to know if you would continue improving the app,And the app consumes a lot of RAM

Thanks a lot of success

I leave you an excel with the respective tests
[TEST SMART YOUTUBE TV.xlsx](https://github.com/yuliskov//files/1148994/TEST.SMART.YOUTUBE.TV.xlsx)

![img_20170714_111959](https://user-images.githubusercontent.com/30176097/28220973-191a06f2-6887-11e7-9137-9f8fc81229d4.jpg)
![img_20170714_112033](https://user-images.githubusercontent.com/30176097/28220932-ee318f1e-6886-11e7-9273-16afdbcd0840.jpg)
![img_20170714_112020](https://user-images.githubusercontent.com/30176097/28220937-f0c586b8-6886-11e7-8dfe-053b8b0cf50b.jpg)

**Comment by yuliskov** [comment]
Hi. Thank you too. I have memory efficient version of this app. It plays video through the external player. I think on your device it might work better. Link below.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.8/SmartYouTubeTV_v6.8.8_unlock2.apk

**Comment by jackiehhop** [comment]
Hi probe the application but it does not let me play complete lists of videos, the solution is very good but loses the interaction with youtube intelligent tv, As well as the option to send videos from my cell to the tv
:(

**Comment by jackiehhop** [comment]
The apcion of sending videos of mu cell is the most used for this tv but when I want to see another video I have to wait until I finish the one I had sent before taking control of the tv and leaving to play another video
Thank you for your great attention
![screenshot_2017-07-14-13-17-44](https://user-images.githubusercontent.com/30176097/28225224-7b777856-6897-11e7-8c65-784b35cf4866.png)

**Comment by yuliskov** [comment]
Thanks for the response. I'll try to find solution to playback issues. For now test these old versions.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/stable/SmartYoutubeTV_MULTI_3.0.apk
https://github.com/yuliskov/SmartYouTubeTV/releases/download/stable/Smart.YouTube.TV.6.8.5.apk
https://github.com/yuliskov/SmartYouTubeTV/releases/download/stable/Smart.YouTube.TV.Beta.6.8.2.apk

**Comment by jackiehhop** [comment]
Ok I will be attentive, thank you very much I will make the respective tests with the applications that you sent me I will be commenting you

**Comment by jackiehhop** [comment]
APK 1:  Smart Youtube TV_MULTI_3.0.apk NOT PLAY VIDEO "LOADING" VIDEO 
APK 2:  Smart YouTube TV.6.8.5 .apk NOT PLAY VIDEO "LOADING" VIDEO 
APK 3:  Smart YouTube TV.Beta.6.8.2.apk  THE VIDEO PAUSES OR THE VIDEO BLOCK  WHEN I VOLUME UP AND SCROLL
IN THIS DOCUMENT ARE THE TEST OF ALL VERSION APK  [TEST SMART YOUTUBE TV.xlsx](https://github.com/yuliskov/SmartYouTubeTV/files/1149638/TEST.SMART.YOUTUBE.TV.xlsx)

**Comment by yuliskov** [comment]
Hi. I currently developing version for devices with low ram. Please, check it out.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.32/SmartYouTubeTV_Exoplayer_v6.8.32_r.apk

**Comment by jackiehhop** [comment]
Hello

I have been testing the application version 6.8.37 and it works very well the bad thing is when I am playing videos from the cellular a list d reproduction only reproduces 1 video and leaves reproducirel rest of videos 

also the connection of the cell phone with the tv lasts between 3 to 4 minutes and then disconnects

**Comment by yuliskov** [comment]
@jackiehhop haw can I reproduce this bug? Could you give me exact steps?

**Comment by jackiehhop** [comment]
HELLO

HERE VIDEO PLAY
https://www.dropbox.com/s/pr96jvvys5ypq2h/mobizen_20170929_111409.mp4?dl=0

**Comment by yuliskov** [comment]
Thanks. I'll try to figure out what happens.

**Comment by jackiehhop** [comment]
HELLO 
VERSION 6.8.38 DOES NOT PLAY ON TV

**Comment by yuliskov** [comment]
App reworked. Feel free to submit any issues.
