### ISSUE TITLE
Long "Loading..." after pause and play again

### ISSUE THREAD

**Issue by byaka** [yuliskov/SmartYouTubeTV#90]
Anyone has same problem? or its limitation of used player?

**Comment by yuliskov** [comment]
@byaka this is definitely a case where system player cause such behavior. I'm not sure that I can deal with it.

**Comment by byaka** [comment]
crap.. thx for info
anyway its best youtube player for smart-tv :)

**Comment by yuliskov** [comment]
duplicate of #83
