### ISSUE TITLE
Somtimes video lag 3 seconds in Mibox3 enhance version

### ISSUE THREAD

**Issue by frankieyen** [yuliskov/SmartYouTubeTV#92]
half years ago , I used smartyoutubetv , it works fine but can't watch live stream channel .
about one month ago , I update my smartyoutubetv  , now live steam channel works ,
but Somtimes video lag 3 seconds (about 1 time per 10 mins) , I used 6.12.58 - 79 , It all have this problem ,
I'm not sure how to fix it . Just submit this try to get solution , thanks for your effort .

**Comment by frankieyen** [comment]
After install crosswalklib arm64 , the situation seems dissapear , I will keep watching .

reference : https://forum.xda-developers.com/fire-tv/development/app-youtube-tv-app-fire-tv-t3757074

**Comment by frankieyen** [comment]
oh oh , after watching for one week ... this situation still going ... I can't fix it by myself ...I will try the newest version again . Thanks .

**Comment by yuliskov** [comment]
duplicate of #74
