### ISSUE TITLE
click the video,show the loading interface，and stay there,like the app is downed.

### ISSUE THREAD

**Issue by itrustmchow** [yuliskov/SmartYouTubeTV#93]
and then show me the warning:javax.net.ssl.SSLException: Connection closed by peer。

my tv is sharp arm64.
app version:almost all

ths.the app is my only hope for using youtube in tv.

**Comment by yuliskov** [comment]
check out that you have setup time correctly

**Comment by itrustmchow** [comment]
i check the time a just now,is right time,i'm Chinese,the time is UTC+8,show me like PM 6:59

**Comment by itrustmchow** [comment]
i try the official youtube version,play normal,but login failure,your app is important to me.

thanks again.

**Comment by yuliskov** [comment]
@itrustmchow I'm pretty sure that the last version couldn't display ssl error. Instead you will face constant loading screen or something. BTW, what launcher are you using? Is that one, labeled as 720? Does 1080 launcher leads to same error?

**Comment by itrustmchow** [comment]
thanks for your replay,i try it again,the situation below:

720:Warnning and then wait a long time,then play with very low resolution ratio，some times play failure.

1080:controler lost control and warnning.

4K mitv:just like 720.

the option of the App is:
codec:no restrictions.
Autoframerate:checked.
update Check:checked.

**Comment by itrustmchow** [comment]
now is ok,thanks a lot.
