### ISSUE TITLE
AutoUpdateChecker:java.net.SocketTimeoutException:connect time out

### ISSUE THREAD

**Issue by helloljq** [yuliskov/SmartYouTubeTV#95]
AutoUpdateChecker:java.net.SocketTimeoutException:connect time out

SONY  55x7000D

No matter which mode is reporting this fault

I don't think it is a network problem, because other information can be loaded, including user settings, pictures, video lists, etc., but it cannot be played. And my native YouTube on this TV is playing normally。

![wechatimg3](https://user-images.githubusercontent.com/11308773/37911144-d5e8f35a-3141-11e8-81bc-b6772167b6ac.jpeg)

**Comment by helloljq** [comment]
I tried the following two versions ：
 SmartYouTubeTV_Orig_v6.12.58_r.apk
 SmartYouTubeTV_Orig_v6.12.82_r_autoapk.apk

**Comment by yuliskov** [comment]
@helloljq thanks, friend. Are you using VPN or something?

**Comment by helloljq** [comment]
Yes, I used shadowsocks on the router
emmmmm  because i am from china

**Comment by helloljq** [comment]
I tried both WiFi and cable

**Comment by yuliskov** [comment]
Thanks for the reply. My app gets updates through drive.google.com. Check
that this address is allowed in your router.

**Comment by helloljq** [comment]
Drive.google.com is accessible

**Comment by yuliskov** [comment]
@helloljq thanks, seems the bug somewhere on my side. I don't think that it could cost so much of the troubles since I'm not planning intensive updates here.

**Comment by helloljq** [comment]
@jjfflash 我后面重启了一波路由器，完了之后就好了。 不过不稳定，时不时的又播不了了，然后退出APP重新进入又好了，很怪，然后后面我就没折腾了，用原生的YouTube了。  打算过一阵买一个原生的盒子算了

**Comment by jjfflash** [comment]
@helloljq 谢谢。

**Comment by dahossie** [comment]
@yuliskov hi I'm having the same problem since pretty long time ago, my app became very unstable, having exactly the same issue with @helloljq, it won't update automatically and most of time it won't play normally, it will also randomly zoom in and out during the video once it played......

im Sony X55 9000e and also I'm using shadowsocks from China with no problem accessing google. 

Thanks!

**Comment by dahossie** [comment]
@helloljq 兄弟，我和你的情况一样，我想请教一下你是如何安装原生youtube的？谢谢！

**Comment by dahossie** [comment]
@helloljq 我的微信 Hossie 如方便我们沟通下，谢谢！

**Comment by yuliskov** [comment]
@dahossie hmm. Have you experience the same problems with original youtube client?

**Comment by helloljq** [comment]
@dahossie  原生的在apkmirror上下载一个包直接就可以安装 如果最新的安装不了就下载一个老一点的包  完了之后它会在网络空闲的时候自动更新的

**Comment by dahossie** [comment]
@yuliskov not really, but the problem for the original client is that its very old version plus since our TV in China don't have google framework meaning that we cannot logon to our account.

**Comment by dahossie** [comment]
@helloljq 明白，那我试过，可安装使用，不稳定且不能登录账号。。。。。

**Comment by helloljq** [comment]
@dahossie  额额额。。 我这边稳定倒是很稳定，不过登录账号的问题没法解决。。 我已经放弃折腾了。。。 准备之后买个盒子好了

**Comment by dahossie** [comment]
@yuliskov thats the strange part, that I cannot download xwalk from the client nor the update, which gives me the error that @helloljq experiencing, but I've double checked my router as well as trying to logon with my computer, both can access google doc. 

meaning that I could only try 720 and 4k version of the client, which gives me same error.

before I replied this thread my walk around was to downgrade to lower version, which is around 5 or 6 month ago(I can check the exact version when I got home), but whats annoying me is that every time I open the client it asked me upgrade :P, but there's no problem updating from that version...... once I upgraded it won't upgrade and it become very unstable playing clips

Thanks

**Comment by dahossie** [comment]
@helloljq 盒子有，但是就是不想用盒子，所以折腾，哈哈，我在盒子上面用没有任何问题（小米盒子）

**Comment by yuliskov** [comment]
@dahossie do manual install of xwalk client. Link below. Also, give me the version of that stable build.
https://drive.google.com/drive/folders/1_HM4DDAbCchAkCcAruWnJ4cGYDfXLEw9

**Comment by dahossie** [comment]
@yuliskov ok, I will try that tonight, also can you please let me know where do I put the file once I download the xwalk? thanks again

**Comment by yuliskov** [comment]
@dahossie nowhere. You need to install xwalk as regular apk.

**Comment by dahossie** [comment]
@yuliskov ive tried to install xwalk and it appears same as before... having the same error and still very unstable, btw the stable build is ver. 6.9.12, Thanks

**Comment by yuliskov** [comment]
@dahossie thanks for the feedback. New test release is here.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.89/SmartYouTubeTV_Orig_v6.12.89_r.apk

**Comment by dahossie** [comment]
@yuliskov Thanks for the update but no the exact issue is still there :(
after the update the error changes to unable to connect doc.google.com....... as of pic 1

![img_7416](https://user-images.githubusercontent.com/23035163/40061777-45f995f2-588c-11e8-8560-5ba0d6ee6ef6.JPG)
then the screen will turn into gray and like below
![img_8786](https://user-images.githubusercontent.com/23035163/40061779-4662ca40-588c-11e8-8b56-aa110d89d242.JPG)

then if I click any of the clip it will just says "loading" but won't load anything....

**Comment by dahossie** [comment]
@yuliskov well.. that's exactly what I am doing right now, I've spent the last 2 hours trying to install every single build and try the latest working stable version. the latest ive found is 6.12.36, after that there are some "test only versions" so far ive tested until 6.12.48. from 6.12.44 it gives the app update error but the the play back in pretty stable, meaning that the "perfect" version for me is 6.12.36, after that 40,41,42,43 will just crash after 20 secs when I open the client, .44 will start to give me the app update error and play back is fine. 
hope this will help you to identify the problem!
Thanks again

**Comment by yuliskov** [comment]
@dahossie many thanks!

**Comment by yuliskov** [comment]
@dahossie I've tried to fix some bugs. Pls check.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.90/SmartYouTubeTV_Orig_v6.12.90_r.apk

**Comment by dahossie** [comment]
@yuliskov smoothy as silk! only one thing that the pop update notification is still asking me to "upgrade" to .88 which I think its very easy for you to fix that

Thanks so much again!

**Comment by yuliskov** [comment]
@dahossie 

> pop update notification is still asking me to "upgrade"

I have to downgrade version id to see whether updates delivered as expected.

> what was the problem causing the networking issue?

I think that problem was caused by in-app dns resolver.

**Comment by dahossie** [comment]
@yuliskov great! I will wait for the next PERFECT update then! keep up for the great work!

**Comment by yuliskov** [comment]
@dahossie hmm, pushed 6.12.91 update ten hours ago

**Comment by dahossie** [comment]
@yuliskov hi it’s me again :(
I’ve away for the past week but once I got back today I’ve found this new error, and it will just hang there with a blank white screen, please have a look! Thanks!

**Comment by yuliskov** [comment]
@dahossie double check time on your tv. Wrong time may case such errors.

**Comment by dahossie** [comment]
@yuliskov Yeah, sorry I just realized that the dare&time was soooo wrong on my TV, thanks

**Comment by dahossie** [comment]
@yuliskov sorry to trouble you again in this thread, when I try to open the client tonite it just stopped at the "Press back button to regret to the launchers dialog" screen, and the circle just keep spinning won't load to next screen, can you advice me what do I need to do? Thanks again

**Comment by yuliskov** [comment]
@dahossie constant loading may be signature of bad internet connection

**Comment by yuliskov** [comment]
@aiddroid could you remember how this problem started to appear?

**Comment by aiddroid** [comment]
@yuliskov I'm new to SmartYouTubeTV, even didn't watch any movie, "unknown error" appeared after a long time "loading" on the main screen.

**Comment by yuliskov** [comment]
@aiddroid seems that some of the needed hosts have been blocked. I'll add there full list to your consideration.

**Comment by aiddroid** [comment]
@yuliskov Maybe you're right, but I have already used a Google Cloud Server as global proxy, and I can access to Youtube via the TV browser.

**Comment by yuliskov** [comment]
@aiddroid to be sure you need to check the next address via tv browser: https://youtube.com/tv

**Comment by aiddroid** [comment]
haha, Youtube's Tv page blocked my ip.I switched to another ip, now it works, thanks!!!
