### ISSUE TITLE
MiTV 4 - Frozen Screen 3840x2160 or higher

### ISSUE THREAD

**Issue by sirjman** [yuliskov/SmartYouTubeTV#96]
I have the app loaded on a Mi TV 4 (China UI) and only the first frame of the video will be shown when set to 3840x2160 or higher (23/60fps). The sound and subtitles will play but the screen will not move past the first frame. If you let the video continue to play, if the video would have faded to black, it will jump to the first frame after the black screen and then stop.

If you downgrade the video or select 'Default Quality; the video will play. 

I am using the Mi TV version of the app, as the Alt version does not load at all on the TV. Sits on a grey screen.

**Comment by yuliskov** [comment]
@sirjman Mi TV has performance issues related to vp9 codec. I'm afraid this could be fixed.

**Comment by rx2130** [comment]
I'm having the exact problem for the 4k vp9 codec.

**Comment by yuliskov** [comment]
@rx2130 it's hw issue not app problem
