### ISSUE TITLE
4K videos playing at 1080p on Sony Bravia with Android 7.0

### ISSUE THREAD

**Issue by Michelasso** [yuliskov/SmartYouTubeTV#97]
First I should say that it hangs on a grey screen if I select the 4K Alt Version, but if I select 4K MiTv and Legacy it starts and my Bravia TV switches to HDR. Actually I had to manually select the VP9.2 (HDR) stream the first time, but after that it always selects 2160p HDR as default if present.

Then, if I look at stats for nerds in a 4K 60 fps videos, it says:

Video/Display Resolution 3840x2160@60/1920x1080@60

It actually seems like the app isn't switching to a 4K display at all (while the standard one does, even with 1080p videos). Usually the apps, since the GPU on Bravia TVs is quite poor, default to 1080p indeed 

Hopefully it's an easy fix.

**Comment by yuliskov** [comment]
@Michelasso thanks for the feedback, friend. Your request will be processed when I will have some spare time.

**Comment by newkind** [comment]
Thanks @yuliskov. I can confirm the findings of @Michelasso - videos are being downscaled to 1080p - however HDR works great. The only issue is that the default colorspace is always BT.709 and you have to manually select BT.2020 for videos that support it.

**Comment by Michelasso** [comment]
Yeah, I confirm the BT.709 issue as well. But I am not sure it's caused by the app. Plex, with VP9.2 videos downloaded from YouTube does the same.

**Comment by SesioN** [comment]
@yuliskov I can also confirm the reported issue.

1) 4K alt leads to a gray screen
2) 4K MiTv leads to 
    a) first time having to manually change from 4k to 4k HDR in quality -> video
    b) then HDR does indeed load up, however Video/Display Resolution 3840x2160@60/1920x1080@60

Another thing that I am missing is the fact, that with your app I cannot use voice search. When I press the voice search button, the default google assistant search loads up. In the original YouTube app, you can press the same voice search button and have the voice search directly search in the YouTube App. 

Aside of that great work, thanks!

PS: I'll gladly help you debug / get log data if required to get this issue fixed.

**Comment by CiNcH83** [comment]
Everything is fine with resolution. A Sony Bravia always reports screen resolution as 1920x1080. Android and apps are rendered at that resolution which later gets upscaled to the native 4K panel resolution. You won't be able to render a 4K GUI on the slow SoC inside Sony. Video is different. A seperate 4K capable video pipeline is used to render that directly to the output (via MediaCodec API).

**Comment by CiNcH83** [comment]
Everything is fine with resolution. A Sony Bravia always reports screen resolution as 1920x1080. Android and app GUIs are rendered at that resolution which later gets upscaled to the native 4K panel resolution. You won't be able to render a 4K GUI on the slow MediaTek SoC inside Sony at a reasonable speed. 'Display Resolution' is basically only telling you at which resolution the GUI is being rendered.

Video is different. A seperate 4K capable pipeline is used to decode and render video directly to the 4K output (via MediaCodec API). So what SmartYouTubeTV reports is perfectly fine. You should only look at 'Video Resolution'. That's the stream selected by SmartYouTubeTV (as the Sony reported that it can do that) which is then handed over to MediaCodec which then does the rest in a proper way, which means decoding and rendering 4K video inside a dedicated hardware.

The color space issue obviously is Sony/MediaTek related, not making the right decisions based on the VP9.2 HDR metadata. That's nothing the app can decide or switch.

So the only relevant issue left is the grey screen in '4K Alt' mode.

**Comment by Michelasso** [comment]
@CiNcH83 Hmm.. Yeah, it seems I was wrong about the resolution. I have checked now with the 4K UHD Test Pattern video in YouTube, and switching the stream from 4K to 1080p (always V9) the 1px vertical lines become a kind of uniform grey. My fault, I have got confused by the different stats for nerds in the S-YouTube TV app. Also some videos had some (quite) bad artefacts, but at this point it may have been due to initial load? Or was it supposed to lag instead? I dunno, they looked different to me from what I have seen in the official app.

About the colour space issue.. Wouldn't it be possible for an app to "bypass" the API, meaning it could analyse first what's the video colour space and then force it no matter what on the device? I mean, just to avoid to do it manually.

**Comment by CiNcH83** [comment]
There is no API to switch color space in Nougat. It got added with Oreo. But I am sure Sony/MediaTek won't implement it.

**Comment by SesioN** [comment]
In that case, the only thing that is holding me off this app is the missing voice search. Sorry for the false confirmation.

**Comment by Michelasso** [comment]
@SesioN well, it is still great when one feels like to watch some YouTube videos in all its HDR glory! Just set manually the colour space to BT.2020 and start surfing (with the remote 🤣)!

**Comment by yuliskov** [comment]
Closed. Outdated
