### ISSUE TITLE
No adaptive streaming?

### ISSUE THREAD

**Issue by CiNcH83** [yuliskov/SmartYouTubeTV#99]
I played around a bit with SmartYouTubeTV and it looks as if it is based on the former native YouTube app 1.x. Finally 60p clips play fine again. The YouTube 2.0 Cobalt thingy is a disaster in that regard. As is Chromecast...

A problem that I have with SmartYouTubeTV is that adaptive streaming does not seem to be supported. My broadband connection is currently limited to 25mbps. Most 4K@60fps clips are bigger than that. Original YouTube app wouldn't go above 1440p60 for those. SmartYouTubeTV goes all the way up to the maximum which results in constant rebuffering. Doesn't the app support adaptive streaming? The original YouTube 1.x app did...

**Comment by CiNcH83** [comment]
Indeed. I checked that with YouTube 2.0. It mostly shows my internet speed to be at 18-19mbps. If I do a speedtest (speedtest.net, fast.com), I get the full 25mbps. Speed measurement probably is a bit conservative? Still it gives me better results than without it.

**Comment by yuliskov** [comment]
should be fixed in the latest beta
